### ISSUE TITLE
RuntimeException when getTypeface results in a native typeface cannot be made

### ISSUE THREAD

**Issue by gennadiiivanov** [intercom/intercom-android#107]
```
java.lang.RuntimeException: Unable to create service io.intercom.android.sdk.preview.PreviewService: java.lang.RuntimeException: native typeface cannot be made
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2812)
       at android.app.ActivityThread.access$1900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5586)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: native typeface cannot be made
       at android.graphics.Typeface.<init>(Typeface.java:334)
       at android.graphics.Typeface.createFromAsset(Typeface.java:308)
       at io.intercom.android.sdk.utilities.FontUtils.getTypeface(FontUtils.java:16)
       at io.intercom.android.sdk.preview.PreviewService.initializeChathead(PreviewService.java:230)
       at io.intercom.android.sdk.preview.PreviewService.onCreate(PreviewService.java:146)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2802)
       at android.app.ActivityThread.access$1900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5586)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Happened in 1.1.1 version.

**Comment by DaleCantwell** [comment]
@gennadiiivanov could I get some additional information on your integration. What IDE are you using? How are you integrating Intercom eg. if its in Gradle are you using transitive = true
Do you see this error all the time? Is it only happening on a specific device?

**Comment by gennadiiivanov** [comment]
> @gennadiiivanov could I get some additional information on your integration. What IDE are you using?

We are using Android Studio 1.1.0 buildToolsVersion 21.1.2.



> How are you integrating Intercom eg. if its in Gradle are you using transitive = true

Yes, we do

```
  compile ('io.intercom.android:intercom-sdk:1.1.1@aar') {
    // Please note that the same libraries from this build file and libraries from Intercom described in the following
    // section https://github.com/intercom/intercom-android#remote-dependencies should have the same version to avoid
    // crashes and unexpected behaviour.
    transitive = true
  }
```

> Do you see this error all the time? Is it only happening on a specific device?

It is happening randomly. We got only a few of this crash. No any specific devices.

**Comment by DaleCantwell** [comment]
@gennadiiivanov could you send me on any additional information you have on this issue. Even if its not one specific device could we get the list of devices (or at least a subset) for us to attempt to replicate the crash?
Thanks,
Dale

**Comment by gennadiiivanov** [comment]
This is not  a big crash. It happened only for 2 users from thousands of them:
1. TCL 6036A, Android 4
2. Samsung SM G900H, Android 4.

**Comment by DaleCantwell** [comment]
@gennadiiivanov could you link us to your application or send us an apk privately if you would prefer to. I can't recreate this issue. Any manipulation of our fonts leads to the asset not found error never the native typeface cannot be created. I am interested to see if this is related to an out of memory issue.

**Comment by gennadiiivanov** [comment]
> I am interested to see if this is related to an out of memory issue

Yes, it is. The amount of used RAM memory in the moment of crash is 99%.

**Comment by DaleCantwell** [comment]
@gennadiiivanov I have tried to replicate this issue on the same device you use and on a simulated version restricted to 256mb of RAM but I never hit that error.
Is it possible to get a breakdown of what process was using most of the memory just before the crash? If the application is hitting 99% memory usage loading any image or font would certainly be enough to cause the crash. If we are using an abnormally high amount of memory in your application we will look into what could be causing that.

**Comment by gennadiiivanov** [comment]
> @gennadiiivanov I have tried to replicate this issue on the same device you use and on a simulated version restricted to 256mb of RAM but I never hit that error.
> Is it possible to get a breakdown of what process was using most of the memory just before the crash? If the application is hitting 99% memory usage loading any image or font would certainly be enough to cause the crash. If we are using an abnormally high amount of memory in your application we will look into what could be causing that.

@DaleCantwell we are not able to replicate the issue in house. We can profile the memory usage in the app and see if your library uses abnormally high amount of memory. But I need some time for this because this is not the highest priority task for my team now.

**Comment by DaleCantwell** [comment]
@gennadiiivanov we are releasing a version an update on Monday (24th July 2015) that includes a fix for this issue. If the font can't be loaded we will return to the system default.

**Comment by gennadiiivanov** [comment]
thanks @DaleCantwell

**Comment by harkin** [comment]
v1.1.3 is live and will solve this
