### ISSUE TITLE
PreviewService rootview null if the service is created from the background

### ISSUE THREAD

**Issue by gennadiiivanov** [intercom/intercom-android#108]
```
java.lang.RuntimeException: Unable to start service io.intercom.android.sdk.preview.PreviewService@3a483d97 with Intent { cmp=com.livestream.livestream/io.intercom.android.sdk.preview.PreviewService }: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.setVisibility(int)' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3279)
       at android.app.ActivityThread.access$2200(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5835)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.RelativeLayout.setVisibility(int)' on a null object reference
       at io.intercom.android.sdk.preview.PreviewService.hideChathead(PreviewService.java:332)
       at io.intercom.android.sdk.preview.PreviewService.checkConversations(PreviewService.java:274)
       at io.intercom.android.sdk.preview.PreviewService.onStartCommand(PreviewService.java:158)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3262)
       at android.app.ActivityThread.access$2200(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5835)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

Happened in 1.1.1 version.

**Comment by DaleCantwell** [comment]
@gennadiiivanov thanks for reporting this to us. We are working on a solution now. Was there any reproducible steps that lead to this crash?

**Comment by gennadiiivanov** [comment]
> @gennadiiivanov thanks for reporting this to us. We are working on a solution now. Was there any reproducible steps that lead to this crash?

We could reproduce the issue. We got crash log into the crash reporting system from the released app.

**Comment by DaleCantwell** [comment]
@gennadiiivanov it was possible that the rootview of our PreviewService could be null. The circumstances to cause this are incredibly hard to reproduce. We have modified this section so that if the rootview is null that none of the children can ever be referenced.
Out of interest does your crash logging give you percentages or numbers to reflect how common this issue is?

**Comment by gennadiiivanov** [comment]
> Out of interest does your crash logging give you percentages or numbers to reflect how common this issue is?

@DaleCantwell this is one of the 2 main crashes (btw, another one also comes from Intercom) we have in the app. It happened for 15 users from thousands.

**Comment by gennadiiivanov** [comment]
@DaleCantwell , when do you plan to release this fix? I'd like to include it into the update of the app.

**Comment by adamkmccarthy** [comment]
Hi @gennadiiivanov, we're planning on doing a point release next Monday (27th August).

**Comment by harkin** [comment]
v1.1.3 is live and will solve this
