### ISSUE TITLE
Index out of bounds exception being thrown

### ISSUE THREAD

**Issue by gennadiiivanov** [intercom/intercom-android#113]
```
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at io.intercom.android.sdk.preview.PreviewService.onTouch(PreviewService.java:447)
       at android.view.View.dispatchTouchEvent(View.java:8102)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2144)
       at android.view.View.dispatchPointerEvent(View.java:8315)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4611)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4479)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4033)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4056)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4171)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4064)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4228)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4033)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4087)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4056)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4064)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4033)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6418)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6322)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6293)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6258)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6498)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:5356)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Happens on the latest 1.1.3 version

**Comment by harkin** [comment]
Thanks for letting us know about this, I'm looking into why this is happening now

**Comment by harkin** [comment]
this is fixed in the latest version
