### ISSUE TITLE
 E/AndroidRuntime﹕ FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by sumit1294** [intercom/intercom-android#118]
My app is crashing because of the following error.

```
java.lang.AbstractMethodError: abstract method not implemented
            at io.intercom.android.nexus.NexusSocket.onOpen(NexusSocket.java)
            at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:169)
            at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
            at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:170)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

I am not able to identify this issue. Is anyone else facing the this issue?

I am using following libraries in my gradle file.
```
 compile('io.intercom.android:intercom-sdk:1.0.0@aar')
 compile 'com.squareup:otto:1.3.7'
 compile 'com.squareup.okhttp:okhttp:2.4.0'
 compile 'com.squareup.okhttp:okhttp-ws:2.4.0'

```

**Comment by harkin** [comment]
v1.0.0 of the Intercom library had these dependencies: 
```
compile 'com.android.support:support-v4:22.1.1'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.squareup:otto:1.3.7'
    compile 'com.squareup.okhttp:okhttp:2.3.0'
    compile 'com.squareup.okhttp:okhttp-ws:2.3.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.google.android.gms:play-services-gcm:7.3.0'
```

You've got the wrong version of okhttp-ws and okhttp there. I'd recommend updating to the latest version, we've repackaged dependencies (excluding the play services lib) so you won't need to worry about our library relies on
