### ISSUE TITLE
java.lang.RuntimeException: An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by cazador4** [intercom/intercom-android#125]
Hi, I put this method "private void registerInBackground()" like it recommend here: http://docs.intercom.io/Install-on-your-mobile-product/using-google-cloud-messaging-gcm-with-intercom-for-android

any idea?

java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.&lt;init&gt;(Handler.java:200)
	at android.os.Handler.&lt;init&gt;(Handler.java:114)
	at com.tobuy.android.activity.HomeActivity$1.doInBackground(HomeActivity.java:148)
	at com.tobuy.android.activity.HomeActivity$1.doInBackground(HomeActivity.java:130)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by harkin** [comment]
That example is just to show how to run it in the background. It doesn't matter what method you use as long as it's not happening on the UI thread. 

I've never come across that error before (not a fan of asynctasks personally). It looks like maybe you're executing the asynctask on a background thread that hasn't prepared it's looper? If you're already on a background thread then you don't really need the asynctask. Are you trying to update the UI from the background thread maybe? That would cause a crash but I wouldn't expect it to look like this. 

There are loads of other strategies for running something in the background, you could use something like this:

```
Executors.newSingleThreadExecutor().submit(new Runnable() {
    @Override public void run() {
            //code                    
    }
})
```
