### ISSUE TITLE
SecureRandom crashes on some devices

### ISSUE THREAD

**Issue by dzeikei** [intercom/intercom-android#127]
This link has the fix:
http://android-developers.blogspot.com.au/2013/08/some-securerandom-thoughts.html

```
java.lang.SecurityException: Failed to read sufficient bytes from /dev/urandom. Expected: 1024, actual: 34
       at com.android.org.conscrypt.OpenSSLRandom.seedOpenSSLPRNGFromLinuxRNG(OpenSSLRandom.java:75)
       at com.android.org.conscrypt.OpenSSLRandom.selfSeedIfNotSeeded(OpenSSLRandom.java:61)
       at com.android.org.conscrypt.OpenSSLRandom.engineNextBytes(OpenSSLRandom.java:37)
       at java.security.SecureRandom.nextBytes(SecureRandom.java:271)
       at io.intercom.com.squareup.okhttp.ws.WebSocketCall.(SourceFile:66)
       at io.intercom.com.squareup.okhttp.ws.WebSocketCall.(SourceFile:56)
       at io.intercom.com.squareup.okhttp.ws.WebSocketCall.create(SourceFile:47)
       at io.intercom.android.nexus.NexusSocket$2.run(SourceFile:73)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by harkin** [comment]
Thanks for letting us know about this. 

We aren't using `SecureRandom` directly in this library. This crash came from the websockets library we're using `[okhttp-ws](https://github.com/square/okhttp/blob/master/okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java#L56)`. I'm a little hesitant to open an issue on their repo for a crash I can't reproduce myself. 

Do you have any figures for how frequently you're seeing this and on any devices in particular? From the blog post it seems like it's only an issue for phones <= API 17

**Comment by dzeikei** [comment]
Our crashlogs indicate that it has happened on 3 devices so far:
Sony C6903 (Experia Z1) on 5.0.2
Sony D5503 (Experia Z1 Compact) on 5.0.2
LG D855 (G3) on 5.0

We can just apply the PRNG fix on our Application class to initialise it properly on our app.

**Comment by harkin** [comment]
I think doing this on an app by app basis is the best move.

I'm don't think that installing a new PRNG would be good behaviour for this library

**Comment by DaleCantwell** [comment]
@dzeikei thanks again for raising this issue. As @harkin said we think this is best implemented on an app by app basis so for the time being we won't be making a code change to the Android integration. I'm going to close this issue for now but if you keep encountering this it may be worth opening this issue against https://github.com/square/okhttp. I looked at their issue tracker and it doesn't look like its been reported. Your stacktrace may be useful if they decide to tackle this issue.
