### ISSUE TITLE
java.lang.NoClassDefFoundError: io.intercom.android.sdk.R$drawable

### ISSUE THREAD

**Issue by danpe** [intercom/intercom-android#130]
I'm getting the following with the new 1.1.3 sdk version.

```
java.lang.NoClassDefFoundError: io.intercom.android.sdk.R$drawable
            at io.intercom.android.sdk.identity.AppConfig.createColoredAvatar(AppConfig.java:200)
            at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:65)
            at io.intercom.android.sdk.identity.AppIdentity.<init>(AppIdentity.java:28)
            at io.intercom.android.sdk.identity.IdentityStore.<init>(IdentityStore.java:19)
            at io.intercom.android.sdk.Bridge.<init>(Bridge.java:32)
            at io.intercom.android.sdk.Bridge.init(Bridge.java:41)
            at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:55)
            at io.intercom.android.sdk.Intercom.initialize(Intercom.java:45)
            at com.myapp.MyApplication.initSingletons(MyApplication.java:93)
            at com.myapp.MyApplication.onCreate(MyApplication.java:74)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
            at android.app.ActivityThread.access$1600(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
```

my build.gradle:

```
apply plugin: 'com.android.application'
repositories {
    maven { url 'https://dl.bintray.com/intercom/intercom-maven' }
}

android {
    useLibrary  'org.apache.http.legacy'
    compileSdkVersion 23
    buildToolsVersion '22.0.1'
    defaultConfig {
        applicationId "com.myapp"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 70
        versionName "1.0.5"
        // Enabling multidex support.
        multiDexEnabled true
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.android.support:design:23.0.0'
    compile 'com.google.android.gms:play-services:7.8.0'
    compile('io.intercom.android:intercom-sdk:1.1.3@aar') {
        exclude group: 'com.google.android.gms'
        transitive = true
    }
}
```

**Comment by harkin** [comment]
@danpe What devices and OS versions are you seeing this on? Can you reproduce it reliably?

**Comment by harkin** [comment]
It's possibly relevant that you aren't using the [support multidex library](https://developer.android.com/tools/building/multidex.html) so you'll experience weird bugs on pre lollipop devices if you've crossed the 65k method limit. (You'll need to extend/use the `MultiDexApplication` too)

**Comment by harkin** [comment]
Also pertinent v1.1.3 of the library has some permission bugs on M. I'm working on fixes (we're going through QA now) and there are more details in this issue https://github.com/intercom/intercom-android/issues/116

I doubt that's the problem here though since you aren't getting a security exception

**Comment by danpe** [comment]
Hey herkin,
You were right it was because of the 65k method limit. 
using  support multidex library solved it :)
Thanks !
