### ISSUE TITLE
NullPointerException - context looks to be null in startChatHeadService

### ISSUE THREAD

**Issue by yashwanthsandeep** [intercom/intercom-android#131]
After adding this in my Application class it crashes with NPE.
Intercom.initialize(this, "android_sdk-cc81315c533813afde2aba0414a0ebe0a987be9e", "sgmjau0c");

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
            at android.content.ComponentName.<init>(ComponentName.java:77)
            at android.content.Intent.<init>(Intent.java:4160)
            at io.intercom.android.sdk.Lifecycles.startChatHeadService(Lifecycles.java:40)
            at io.intercom.android.sdk.Lifecycles.onActivityStarted(Lifecycles.java:86)
            at android.app.Application.dispatchActivityStarted(Application.java:199)
            at android.app.Activity.onStart(Activity.java:1171)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:539)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
            at android.app.Activity.performStart(Activity.java:6006)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by harkin** [comment]
@yashwanthsandeep what version of the library are you seeing this on?

**Comment by yashwanthsandeep** [comment]
@harkin 
Hi,
io.intercom.android:intercom-sdk:1.0.0@aar

**Comment by harkin** [comment]
That's an old version of the library, I'd suggest upgrading to v1.1.3

That crash seems to indicate that your app hit the `onStart` of an activity before it had a valid context set on it. Are you using the standard `Activity` or some other version of it, are you doing anything unusual like calling `onStart` directly?

**Comment by harkin** [comment]
@yashwanthsandeep going to close this out for now, if you have any updates please reopen the issue
