### ISSUE TITLE
Unable to create service io.intercom.android.sdk.preview.PreviewService: java.lang.RuntimeException: Adding window failed

### ISSUE THREAD

**Issue by froxCZ** [intercom/intercom-android#132]
Hi,
after implementing intercom to our Android app we found this crash in our crash reports. It occured on HTC Sensation 4G with intercom 1.1.3 and Android 4.0.3. No intercom message or announcement was sent to that device. Would you have any idea why this crash happened and how to prevent this?

Thanks

```
0	java.lang.RuntimeException: Unable to create service io.intercom.android.sdk.preview.PreviewService: java.lang.RuntimeException: Adding window failed
1		at android.app.ActivityThread.handleCreateService(ActivityThread.java:2582)
2		at android.app.ActivityThread.access$1600(ActivityThread.java:139)
3		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
4		at android.os.Handler.dispatchMessage(Handler.java:99)
5		at android.os.Looper.loop(Looper.java:154)
6		at android.app.ActivityThread.main(ActivityThread.java:4944)
7		at java.lang.reflect.Method.invokeNative(Native Method)
8		at java.lang.reflect.Method.invoke(Method.java:511)
9		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
10		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
11		at dalvik.system.NativeStart.main(Native Method)
12	Caused by: java.lang.RuntimeException: Adding window failed
13		at android.view.ViewRootImpl.setView(ViewRootImpl.java:498)
14		at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:407)
15		at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:321)
16		at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:152)
17		at io.intercom.android.sdk.preview.PreviewService.init(PreviewService.java:206)
18		at io.intercom.android.sdk.preview.PreviewService.onCreate(PreviewService.java:123)
19		at android.app.ActivityThread.handleCreateService(ActivityThread.java:2560)
20		... 10 more
21	Caused by: android.os.TransactionTooLargeException
22		at android.os.BinderProxy.transact(Native Method)
23		at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:516)
24		at android.view.ViewRootImpl.setView(ViewRootImpl.java:488)
25		... 16 more
26	java.lang.RuntimeException: Adding window failed
27		at android.view.ViewRootImpl.setView(ViewRootImpl.java:498)
28		at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:407)
29		at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:321)
30		at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:152)
31		at io.intercom.android.sdk.preview.PreviewService.init(PreviewService.java:206)
32		at io.intercom.android.sdk.preview.PreviewService.onCreate(PreviewService.java:123)
33		at android.app.ActivityThread.handleCreateService(ActivityThread.java:2560)
34		at android.app.ActivityThread.access$1600(ActivityThread.java:139)
35		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
36		at android.os.Handler.dispatchMessage(Handler.java:99)
37		at android.os.Looper.loop(Looper.java:154)
38		at android.app.ActivityThread.main(ActivityThread.java:4944)
39		at java.lang.reflect.Method.invokeNative(Native Method)
40		at java.lang.reflect.Method.invoke(Method.java:511)
41		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
42		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
43		at dalvik.system.NativeStart.main(Native Method)
44	Caused by: android.os.TransactionTooLargeException
45		at android.os.BinderProxy.transact(Native Method)
46		at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:516)
47		at android.view.ViewRootImpl.setView(ViewRootImpl.java:488)
48		... 16 more
49	android.os.TransactionTooLargeException
50		at android.os.BinderProxy.transact(Native Method)
51		at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:516)
52		at android.view.ViewRootImpl.setView(ViewRootImpl.java:488)
53		at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:407)
54		at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:321)
55		at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:152)
56		at io.intercom.android.sdk.preview.PreviewService.init(PreviewService.java:206)
57		at io.intercom.android.sdk.preview.PreviewService.onCreate(PreviewService.java:123)
58		at android.app.ActivityThread.handleCreateService(ActivityThread.java:2560)
59		at android.app.ActivityThread.access$1600(ActivityThread.java:139)
60		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
61		at android.os.Handler.dispatchMessage(Handler.java:99)
62		at android.os.Looper.loop(Looper.java:154)
63		at android.app.ActivityThread.main(ActivityThread.java:4944)
64		at java.lang.reflect.Method.invokeNative(Native Method)
65		at java.lang.reflect.Method.invoke(Method.java:511)
66		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
67		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
68		at dalvik.system.NativeStart.main(Native Method)
```

**Comment by DaleCantwell** [comment]
There are a few potential causes. Are you using Android Studio? Have you been able to reproduce this in house? If so would you mind trying out our sample application here:
https://github.com/intercom/intercom-android/tree/master/samples/intercom-androidstudio-sample
You will need to change values in MainActivity and SampleApplication once you download it. It would be interesting to see if this issue is occurring in it on that device too.

Even though as you said "No intercom message or announcement was sent to that device" we add the service to check for intercom events and draw a chat preview if one is received. It seems in the crash report you sent that on that device there was a crash when adding our view to the window. 
I wouldn't think anything we do there could cause a TransactionTooLargeException but I'll look into solutions for that being thrown.

**Comment by harkin** [comment]
@froxCZ is the HTC sensation 4G the only phone you've seen this on?

**Comment by harkin** [comment]
I haven't been able to reproduce this on a HTC Sensation but I changing how previews (smarter, better, faster) work so this will soon be a non-issue.

**Comment by danpe** [comment]
I'm also getting this on Nexus 5 Android 6.0

**Comment by harkin** [comment]
'soon' might have been ambitious in my last update, I'm still working on this. We're in the middle of QA and hope to release this fix/rework 'soon'

**Comment by harkin** [comment]
version 1.1.8 had this change now, you won't see this issue again
