### ISSUE TITLE
Null pointer exception 

### ISSUE THREAD

**Issue by axay** [intercom/intercom-android#135]
I removed intercom from my build.gradle file but it's still crashing my app when I enable proguard. What am I missing ? Here is the stack trace.
```
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime: FATAL EXCEPTION: main
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime: Process: feed.brand, PID: 13202
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime: java.lang.RuntimeException: Unable to create application in.adister.brandfeed.BrandFeedApplication: java.lang.NullPointerException
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4377)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:141)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5049)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:  Caused by: java.lang.NullPointerException
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.identity.AppConfig$BaseColorObjects.replaceColor(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.identity.AppConfig$BaseColorObjects.<init>(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.identity.AppConfig$BaseColorObjects.<init>(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.identity.AppConfig.<init>(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.identity.AppIdentity.<init>(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.identity.IdentityStore.<init>(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.Bridge.<init>(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.Bridge.init(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.RealIntercom.<init>(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at io.intercom.android.sdk.Intercom.initialize(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at in.adister.brandfeed.BrandFeedApplication.onCreate(Unknown Source)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4374)
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread.access$1500(ActivityThread.java:141) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5049) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
10-03 23:43:24.311 13202-13202/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by harkin** [comment]
@axay That doesn't make sense. If the library isn't included it can't crash. It must be still included in your build somehow. Have you cleaned and rebuilt your project?

No line numbers make this a little harder to see exactly where it's breaking, I suspect it's not picking up the R values for the library. Is it only crashing when you have proguard enabled? Have you tried updating the version of the library you're using? 1.0.0 is a little dated now and we've fixed a lot of issues since that release, the latest is 1.1.7

**Comment by axay** [comment]
ok looks like I was using a library which had intercom as a transitive dependency.

**Comment by harkin** [comment]
@axay put of curiosity which library was that?

**Comment by axay** [comment]
It was some analytics library developed by the team here which is kind of an abstraction over GA, mixpanel, intercom, flurry and answers.
