### ISSUE TITLE
NPE in FileUtils#getPath

### ISSUE THREAD

**Issue by jfsso** [intercom/intercom-android#137]
We've been observing a few occurrences of this crash over the past few weeks. Also happened in SDK 1.1.7.

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
       at io.intercom.android.sdk.utilities.FileUtils.getPath(SourceFile:95)
       at io.intercom.android.sdk.utilities.FileUtils.getAbsolutePath(SourceFile:43)
       at io.intercom.android.sdk.attachments.AttachmentData.(SourceFile:32)
       at io.intercom.android.sdk.attachments.AttachmentPresenter$LoadFileTask.doInBackground(SourceFile:87)
       at io.intercom.android.sdk.attachments.AttachmentPresenter$LoadFileTask.doInBackground(SourceFile:84)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by DaleCantwell** [comment]
Hi @jfsso, 
Can you reproduce this in house? Do you have any specific devices so we can try reproduce this ourselves.

**Comment by jfsso** [comment]
@DaleCantwell No, we collected this with crashlytics and it's not reproducible with our devices. As I looked at the crash issue again, the statistics shows that 100% are rooted Jelly Bean devices.

**Comment by harkin** [comment]
> 100% are rooted Jelly Bean devices.

That makes this significantly easier to diagnose; they've all denied/removed the permission/ability to access external storage so uploading an attachment is going :boom:. 

We're currently handling the case correctly for Marshmallow but expecting to have permissions granted at install time for older versions of Android. I'm currently working on changing this. I'll also be looking at what we're doing in `FileUtils` and seeing if I can make that safer too. It's possible this isn't a permission issue but is instead an "I've done craaazy customisations to my rooted phone" issue.

**Comment by harkin** [comment]
I've added some more checks for correct permissions and nulls popping up instead of URIs when we try to add an attachment in 1.1.8 so this _should_ be fixed, I wasn't able to reproduce something exactly like this on a rooted phone though so it's possible there's another cause I missed. I'm going to close this for now and if you see this on 1.1.8 let us know and we'll reopen and look into this again

**Comment by jfsso** [comment]
Thanks! I'll let you know if this one happens again.
