### ISSUE TITLE
NPE in LightboxActivity

### ISSUE THREAD

**Issue by jfsso** [intercom/intercom-android#139]
```
java.lang.NullPointerException
       at io.intercom.android.sdk.conversation.lightbox.LightboxActivity$1.callback(SourceFile:44)
       at io.intercom.android.sdk.views.AttachedImageView.onAttachedToWindow(SourceFile:22)
       at android.view.View.dispatchAttachedToWindow(View.java:11967)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1199)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:621)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by harkin** [comment]
Looking into this

**Comment by harkin** [comment]
`getIntent().getExtras().getString(IMAGE_URL, "")` is the line it's crashing on

are you trying to launch the activity directly yourself? If not, any information about how this state came to be? It looks like the intent or the extras are null when they shouldn't be. We don't set a new intent or in any way mutate the extras

**Comment by jfsso** [comment]
@harkin Ha! Was looking more into the details of this crash, it looks like there were a few dozens instances trying to launch this activity from an android emulator (even before using the app). No idea why. I guess there's no user impact here, please ignore this one. :+1:

**Comment by harkin** [comment]
Oh I've actually seen that before myself! No clue why someone would want to launch activities like that. Let us know if there's anything else we can help with :+1:

**Comment by harkin** [comment]
I did a little looking into this, [one person suggests](http://stackoverflow.com/questions/26346336/unknown-device-in-the-crashlytics-log) it's part of the app publishing flow now where the Play Store runs a [monkey](http://developer.android.com/tools/help/monkey.html) around your app. @jfsso could you check if these crash reports line up with a release?

We weren't explicitly not exporting our activity (because the [docs](http://developer.android.com/guide/topics/manifest/activity-element.html#exported) say they should default to `exported=false`) but I've changed this now, the next version of the sdk (coming later this week) will not be exporting any activity. I'm interested if this will make any change whatsoever in these bogus crash reports

**Comment by jfsso** [comment]
It doesn't seem to be lined up with releases. In fact, a one month old version of our app reported this crash last week. Anyways, this seems to not impact users so we're not concerned too much but I will let you know if we find something related to it.

**Comment by scottlahay** [comment]
This still seems to be happening

**Comment by harkin** [comment]
@scottlahay do you have a crash log of it happening not from an android emulator?

**Comment by scottlahay** [comment]
@harkin Here you go

<pre>
Fatal Exception: java.lang.NullPointerException
       at io.intercom.android.sdk.conversation.lightbox.LightboxActivity$1.callback(LightboxActivity.java:44)
       at io.intercom.android.sdk.views.AttachedImageView.onAttachedToWindow(AttachedImageView.java:22)
       at android.view.View.dispatchAttachedToWindow(View.java:11967)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2426)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1199)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:621)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
</pre>

**Comment by harkin** [comment]
@scottlahay are you sure it isn't happening on an android emulator? This crash happens when someone starts that activity and doesn't pass the right extras with the intent. We make sure we don't do that in the sdk so it's almost certainly someone that isn't the Intercom library trying to start the activity. 

I do plan to refactor it a bit so that it doesn't crash if an extra is missing but it's very low priority for me so long as this is only crashing on emulators doing weird things with apps.

**Comment by scottlahay** [comment]
It happened while everyone was on holiday. So completely sure it didn't
come out of an emulator. I don't think I even start that intent in our app,
so I'm confused at why we get it in the first place.

**Comment by harkin** [comment]
@scottlahay v1.1.13 has some new checks in that activity so you shouldn't see any crashes on it however it's being launched

**Comment by scottlahay** [comment]
@harkin, awesome man, thanks!
