### ISSUE TITLE
Intercom.initialize crashes the app

### ISSUE THREAD

**Issue by tzahi-dapulse** [intercom/intercom-android#142]
java.lang.NoClassDefFoundError: io.intercom.android.sdk.R$drawable
	at io.intercom.android.sdk.identity.AppConfig.createColoredAvatar(AppConfig.java:236)
	at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:71)
	at io.intercom.android.sdk.identity.AppIdentity.<init>(AppIdentity.java:30)
	at io.intercom.android.sdk.identity.IdentityStore.<init>(IdentityStore.java:19)
	at io.intercom.android.sdk.Bridge.<init>(Bridge.java:35)
	at io.intercom.android.sdk.Bridge.init(Bridge.java:45)
	at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:60)
	at io.intercom.android.sdk.Intercom.initialize(Intercom.java:43)
	at com.dapulse.dapulse.app.App.onCreate(App.java:65)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4885)
	at android.app.ActivityThread.access$1600(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5748)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by tzahi-dapulse** [comment]
Fix the issue
http://stackoverflow.com/questions/32205938/java-lang-noclassdeffounderror-android-support-v4-view-layoutinflatercompathc-i

**Comment by DaleCantwell** [comment]
@tzahi-dapulse happy to hear you resolved the issue. Multidexing causes pleanty of headaches :smiley:
