### ISSUE TITLE
NPE cause crash in CallbackHolder

### ISSUE THREAD

**Issue by farukcankaya** [intercom/intercom-android#143]
java.lang.NullPointerException
       at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:43)
       at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:41)
       at io.intercom.android.sdk.api.Api$1.success(Api.java:196)
       at io.intercom.android.sdk.api.Api$1.success(Api.java:192)
       at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5405)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:838)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by harkin** [comment]
@farukcankaya what devices and versions of android are you seeing this on? Are those devices rooted?

**Comment by farukcankaya** [comment]
@harkin 
DEVICE: SM-G900H
ANDROID VERSION: 4.4.2
ROOTED

**Comment by harkin** [comment]
I figured it was rooted. Do you know what ROM is on the phone, and what other customisations have been made?  What I suspect is happening here is that someone has denied/removed a permission in an opaque way. 

We don't put high priority on issues from rooted phones; the customisations you can make are not always sane and if you make a customisation that breaks something on your phone, well that's kinda on you. It's on my backlog to investigate all the weird and zany things rooted phones can do, but it's not going to happen in the forseeable future and it's not something I can promise will _ever_ happen. 

If you can get some concrete details on what exactly the modifications, rom, xposed modules etc running on the phone are I can reopen this and look into exactly what happened here
