### ISSUE TITLE
Error when initialize intercom (intercom-sdk:1.1.3)

### ISSUE THREAD

**Issue by virengujariya** [intercom/intercom-android#161]
```java.lang.RuntimeException: Unable to create service io.intercom.android.sdk.preview.PreviewService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@2506b34 -- permission denied for this window type
                                                                              at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                                                                              at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@2506b34 -- permission denied for this window type
                                                                              at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                                                                              at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                                              at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                              at io.intercom.android.sdk.preview.PreviewService.init(PreviewService.java:206)
                                                                              at io.intercom.android.sdk.preview.PreviewService.onCreate(PreviewService.java:123)
                                                                              at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                                                                              at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)```

**Comment by virengujariya** [comment]
resolved with intercom-sdk:1.1.8 (referred to issue #116)
