### ISSUE TITLE
IllegalStateException in the FragmentManager

### ISSUE THREAD

**Issue by mevipul** [intercom/intercom-android#170]
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1343)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1361)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:729)
       at android.app.BackStackRecord.commit(BackStackRecord.java:705)
       at io.intercom.android.sdk.activities.MainActivity.displayFragment(MainActivity.java:102)
       at io.intercom.android.sdk.activities.MainActivity.transitionToConversation(MainActivity.java:123)
       at io.intercom.android.sdk.conversation.SmallAnnouncementFragment.transitionToFullConversation(SmallAnnouncementFragment.java:272)
       at io.intercom.android.sdk.conversation.SmallAnnouncementFragment.onClick(SmallAnnouncementFragment.java:264)
       at android.view.View.performClick(View.java:5254)
       at android.view.View$PerformClick.run(View.java:21203)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6897)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by harkin** [comment]
@mevipul I'll look into what's happening here.

Can you give any steps to reproduce this? What's the frequency with which you're seeing this, what devices and OS versions?

**Comment by mevipul** [comment]
@harkin You can find the details here 
http://crashes.to/s/f0c60d47827
Thanks

**Comment by harkin** [comment]
@mevipul that looks to be a separate crash to me. Could you make a new issue for it and include all the relative details, including how to reproduce

**Comment by DaleCantwell** [comment]
Regarding the issue mentioned in http://crashes.to/s/f0c60d47827 that has been resolved in release 1.1.13

**Comment by DaleCantwell** [comment]
@mevipul We have fixed the issue you linked in the crash report. The initial issue looks different but I haven't been able to reproduce it. 
Regarding the following issue: 
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
Do you have any additional information. Specifically steps to reproduce, OS version, device, frequency of the issue and if possible Intercom Android SDK version.

**Comment by DaleCantwell** [comment]
@mevipul Going to close this issue for now, we resolved the bug reported here http://crashes.to/s/f0c60d47827 in 1.1.13
We would need more information to take any action on the "java.lang.IllegalStateException" If you encounter it again reopen this issue with any information you can get.
Any of the following would help us out: steps to reproduce, Android OS version, Android device, frequency of the issue and if possible Intercom Android SDK version.

**Comment by jahunt1** [comment]
Ok, the original crash happened to one of my users as well (IllegalStateException in the Fragment Manager). The Intercom version included in that build was 1.1.15. Details can be seen here: http://crashes.to/s/dab2f12e811.
