### ISSUE TITLE
Crashed with android.os.BadParcelableException: ClassNotFoundException when unmarshalling: io.intercom.android.sdk.blocks.models.BlockAttachment

### ISSUE THREAD

**Issue by dsryang** [intercom/intercom-android#185]
Clicking on an in-app chat bubble for a new conversation that has a file attachment causes a crash. While investigating, I also noticed that if you open up the conversation through the conversations inbox, 2 copies of the attached file appears, even though I only attached the file once.

## Version info
  - Intercom for Android version: 1.1.16
  - Android OS version: 4.2.2 - 6.0.1
  - Android Device: Multiple

## Expected behaviour
Conversation opens.

## Actual behaviour
App crashes.

## Steps to reproduce
 1. Send a new message with a file attachment to a user
 2. Click on the in-app chat bubble notification

## Logs
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackagename/io.intercom.android.sdk.activities.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: io.intercom.android.sdk.blocks.models.BlockAttachment
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3184)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3294)
       at android.app.ActivityThread.access$1000(ActivityThread.java:210)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: io.intercom.android.sdk.blocks.models.BlockAttachment
       at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
       at android.os.Parcel.readParcelable(Parcel.java:2245)
       at android.os.Parcel.readValue(Parcel.java:2152)
       at android.os.Parcel.readListInternal(Parcel.java:2526)
       at android.os.Parcel.readList(Parcel.java:1661)
       at io.intercom.android.sdk.blocks.models.Block.<init>(Block.java:267)
       at io.intercom.android.sdk.blocks.models.Block$1.createFromParcel(Block.java:306)
       at io.intercom.android.sdk.blocks.models.Block$1.createFromParcel(Block.java:304)
       at android.os.Parcel.readParcelable(Parcel.java:2252)
       at android.os.Parcel.readValue(Parcel.java:2152)
       at android.os.Parcel.readListInternal(Parcel.java:2526)
       at android.os.Parcel.readList(Parcel.java:1661)
       at io.intercom.android.sdk.models.Part.<init>(Part.java:262)
       at io.intercom.android.sdk.models.Part$1.createFromParcel(Part.java:325)
       at io.intercom.android.sdk.models.Part$1.createFromParcel(Part.java:323)
       at android.os.Parcel.readParcelable(Parcel.java:2252)
       at android.os.Parcel.readValue(Parcel.java:2152)
       at android.os.Parcel.readListInternal(Parcel.java:2526)
       at android.os.Parcel.readList(Parcel.java:1661)
       at io.intercom.android.sdk.models.Conversation.<init>(Conversation.java:103)
       at io.intercom.android.sdk.models.Conversation$1.createFromParcel(Conversation.java:134)
       at io.intercom.android.sdk.models.Conversation$1.createFromParcel(Conversation.java:132)
       at android.os.Parcel.readParcelable(Parcel.java:2252)
       at android.os.Parcel.readValue(Parcel.java:2152)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.BaseBundle.containsKey(BaseBundle.java:269)
       at io.intercom.android.sdk.activities.MainActivity.initializeSDK(MainActivity.java:90)
       at io.intercom.android.sdk.activities.MainActivity.onCreate(MainActivity.java:52)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3137)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3294)
       at android.app.ActivityThread.access$1000(ActivityThread.java:210)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by harkin** [comment]
@dsryang Thanks for letting us know about this. I've reproduced the crash and formatting issues here, working on fixing it now

**Comment by harkin** [comment]
@dsryang this was a few things. The sdk got unexpected data from our server and unmarshalling the object went awry. We're going to fix that in the next release of the SDK. In the meantime, we've fixed the server code (Wednesday I believe, sorry for the delay in getting back!) so that that unexpected data won't be sent.

Thanks for reporting this!
