### ISSUE TITLE
NullPointerException at AttachmentPresenter.java line 37 (100% rooted)

### ISSUE THREAD

**Issue by VasiliyMikhailov** [intercom/intercom-android#187]
This collected with crashlytics and it's not reproducible with our devices. All devices are rooted. Android versions is 4.1.1 and 5.0.2.

intercom-sdk-1.1.16

```
Fatal Exception: java.lang.NullPointerException
       at io.intercom.android.sdk.attachments.AttachmentPresenter.sendClicked(AttachmentPresenter.java:37)
       at io.intercom.android.sdk.attachments.AttachmentActivity.onClick(AttachmentActivity.java:70)
       at android.view.View.performClick(View.java:4298)
       at android.view.ViewRootImpl.performClickHelper(ViewRootImpl.java:922)
       at android.view.ViewRootImpl.performClick(ViewRootImpl.java:931)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3123)
       at android.os.Handler.dispatchMessage(Handler.java:119)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4873)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:528)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by DaleCantwell** [comment]
@VasiliyMikhailov thanks for reporting this issue. I have three questions.
1. what file type were you able to reproduce the crash with? 
2. what size is the file? 
3. the phone you are using, is it rooted and if so what file manager does the attachment picker open to?
Thanks,
Dale

**Comment by VasiliyMikhailov** [comment]
Sorry. I do not have this information. This collected with crashlytics and it's not reproducible with our devices. This happened with two users. Once for every user. Both have rooted devices.

Devices:
Sumsung Galaxy Nenus
Motorola Nexus 6

**Comment by DaleCantwell** [comment]
Thanks for those details. I'll check those devices and see if I can reproduce it.

**Comment by DaleCantwell** [comment]
Hi @VasiliyMikhailov we have made some major changes to this class and how we display preview imaged on that screen. Check out our new release https://github.com/intercom/intercom-android/releases/tag/3.0.0 and let me know if the issue occurs again.
Thanks,
Dale
