### ISSUE TITLE
Facing `No Valid Small Icon` for push notiifcations

### ISSUE THREAD

**Issue by akshaydeo** [intercom/intercom-android#189]
Whenever I send a message in a conversation, and if the app is in the background,the push notification routine crashes with `No valid small icon` error,

## Version info
  - Intercom for Android version: 1.1.17
  - Android OS version: 6 
  - Android Device: Nexus 6

## Expected behavior
It should show the notification in the tray.
## Steps to reproduce
 1. Integrate intecome. [I have crittercism, mixpanel along with it, and also have a custom GCM handler where I have added `if (data.containsKey("receiver") && ntercom.GCM_RECEIVER.equals(data.getString("receiver"))) {return;}`]
 2. Send a reply to a conversation.
 3. App crashes in the background.

## Logs
```
04-04 13:13:18.611 21971-21971/com.simpl.android.staging W/MixpanelAPI.ConfigurationChecker: Receiver io.intercom.android.sdk.gcm.GcmBroadcastReceiver is not set with permission com.google.android.c2dm.permission.SEND
04-04 13:13:18.611 21971-21971/com.simpl.android.staging I/MixpanelAPI.ConfigurationChecker: Please add the attribute 'android:permission="com.google.android.c2dm.permission.SEND"' to your <receiver> tag
04-04 13:13:18.611 21971-21971/com.simpl.android.staging I/MixpanelAPI.API: Can't register for push notification services. Push notifications will not work.

```
```
04-04 12:59:02.501 11796-11802/com.simpl.android.staging W/art: Suspending all threads took: 28.885ms
04-04 12:59:04.205 11796-13854/com.simpl.android.staging E/AndroidRuntime: FATAL EXCEPTION: Thread-5567
                                                                           Process: com.simpl.android.staging, PID: 11796
                                                                           java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=1 contentView=com.simpl.android.staging/0x1090085 vibrate=default sound=default defaults=0x3 flags=0x11 color=0x00000000 vis=PRIVATE)
                                                                               at android.app.NotificationManager.notify(NotificationManager.java:222)
                                                                               at android.app.NotificationManager.notify(NotificationManager.java:194)
                                                                               at io.intercom.android.sdk.gcm.GcmNotificationManager.createNotification(GcmNotificationManager.java:55)
                                                                               at io.intercom.android.sdk.gcm.GcmIntentService.onHandleIntent(GcmIntentService.java:58)
                                                                               at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by DaleCantwell** [comment]
Thanks for reporting this issue. I'm going to investigate this today.

**Comment by akshaydeo** [comment]
Hey thank you for your prompt reply, but It was my configuration issue. Closing this.

**Comment by DaleCantwell** [comment]
Thanks @akshaydeo thats great news. If there is anything I can change in the docs to help this be avoided in the future please let me know.

**Comment by sydneyagcaoili** [comment]
@akshaydeo I want to know what configurationd did you miss.. I'm encountering same issue

**Comment by Kaushik1502** [comment]
@akshaydeo can you please tell I have same issue but can't figure it out how to resolve thanks

**Comment by pravin-mohol** [comment]
What is the resolution for this issue ? its happening on Android m only.

**Comment by mirrortowers** [comment]
@all : mandatory need set SmallIcon value, should not null.
