### ISSUE TITLE
Initialize causes crash

### ISSUE THREAD

**Issue by jonchui** [intercom/intercom-android#194]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:
compile ('io.intercom.android:intercom-sdk:1.+@aar') { 
        transitive = true
    }

  - Android OS version:
6.0.1(MMB29M)
  - Android Device:
Nexus 6p

## Expected behavior
Does not crash

## Actual behavior
crashes
## Steps to reproduce
 1. follow steps in 
https://docs.intercom.io/configuring-for-your-product-or-site/configuring-intercom-for-android#messaging
 2. start the app
 3. app crashes with 

                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                    at io.intercom.android.sdk.identity.AppConfig.createColoredAvatar(AppConfig.java:261)
                                                                                    at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:75)
                                                                                    at io.intercom.android.sdk.identity.AppIdentity.<init>(AppIdentity.java:30)
                                                                                    at io.intercom.android.sdk.identity.IdentityStore.<init>(IdentityStore.java:19)
                                                                                    at io.intercom.android.sdk.Bridge.<init>(Bridge.java:49)
                                                                                    at io.intercom.android.sdk.Bridge.init(Bridge.java:64)
                                                                                    at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:61)
                                                                                    at io.intercom.android.sdk.Intercom.initialize(Intercom.java:45)
                                                                                    at com.youmeforever.readscripture.MyApplication.initIntercom(MyApplication.java:24)
                                                                                    at com.youmeforever.readscripture.MyApplication.onCreate(MyApplication.java:20)
                                                                                    at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:326)
                                                                                    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                                    at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

## Logs

**Comment by harkin** [comment]
@jonchui those line numbers correspond to version 1.1.9. That bug was fixed in [1.1.15](https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md#version-1115).

Are you working offline, or behind a proxy or something that might be preventing you automatically grabbing the latest version? You could set it explicitly to `1.1.18`
