### ISSUE TITLE
NoClassDefFoundError: io.intercom.retrofit.RestAdapter$Builder

### ISSUE THREAD

**Issue by matejhacin** [intercom/intercom-android#196]
I am using Intercom in my app and it works good on newer devices, but it crashes on most older devices (Android version 4.2 for example).

>FATAL EXCEPTION: main
                                                                 java.lang.NoClassDefFoundError: io.intercom.retrofit.RestAdapter$Builder
                                                                     at io.intercom.android.sdk.api.Api.configureRestAdapter(Api.java:120)
                                                                     at io.intercom.android.sdk.api.Api.<init>(Api.java:84)
                                                                     at io.intercom.android.sdk.Bridge.<init>(Bridge.java:52)
                                                                     at io.intercom.android.sdk.Bridge.init(Bridge.java:64)
                                                                     at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:61)
                                                                     at io.intercom.android.sdk.Intercom.initialize(Intercom.java:45)
                                                                     at com.my.package.App.onCreate(App.java:30)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
                                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                     at dalvik.system.NativeStart.main(Native Method)

This happens on this exact line:

    Intercom.initialize(this, apiKey, appId);

This is how I have added Intercom to my dependencies:

    compile ('io.intercom.android:intercom-sdk:1.+@aar') { // Bundled package containing Intercom both base and GCM
        transitive = true
    }

And I have added this in the repositories:

    maven { url 'https://dl.bintray.com/intercom/intercom-maven' }

As I said, this crash only happens on older devices, or at least I haven't been able to recreate it yet on newer ones.

This seems to be Retrofit related, but I don't have Retrofit under my dependencies.

**Comment by harkin** [comment]
Hey @matejhacin thanks for letting us know about this. You're right, we use retrofit inside in our library.

This sounds like a multidex issue to me. Do you have multidexing enabled in your app?

**Comment by matejhacin** [comment]
Yes, I do have multidexing enabled.

**Comment by harkin** [comment]
Are you using version 1.0.1 of the support multidex library and using/extending the [MultiDexApplication](https://developer.android.com/intl/es/reference/android/support/multidex/MultiDexApplication.html) class for your app's application?

**Comment by matejhacin** [comment]
Ah! I was still using version 1.0.0 of support multidex library and I wasn't extending MultiDexApplication, just Application.

I changed those 2 things now and it works.

Thanks a lot for your help!

**Comment by harkin** [comment]
happy to help :)
