### ISSUE TITLE
Initialize error

### ISSUE THREAD

**Issue by sebikaplun** [intercom/intercom-android#202]
I added the dependency in the build.gradle file:
```compile ('io.intercom.android:intercom-sdk-base:1.1.18@aar') {
        transitive = true
    }```

And I run ```Intercom.initialize(this, "android_sdk-" + api_key, app_id);``` in the method onCreate on my Application class.

Im receiving this error (I only tried to initialize the intercom)

```05-29 08:22:56.307 23439-23439/com.app.local E/Intercom-Android: ERROR: Failed to register or update user:  Status: 401 Body: {"type":"error.list","request_id":"6a261951-044c-48d4-91ed-099caaebd512","errors":[{"code":"token_unauthorized","message":"Unauthorized token"}]}
05-29 08:27:43.321 25709-25709/com.app.local E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.RuntimeException: Unable to create application com.app.LocalApplication: java.lang.IllegalStateException: Please call Intercom.initialize() before requesting the client.
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4447)
                                                                         at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:525)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.IllegalStateException: Please call Intercom.initialize() before requesting the client.
                                                                         at io.intercom.android.sdk.Intercom.client(Intercom.java:63)
                                                                         at com.app.LocalApplication.onCreate(BGApplication.java:132)
                                                                         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
                                                                         at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                         at android.os.Looper.loop(Looper.java:137) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                         at dalvik.system.NativeStart.main(Native Method) ```

**Comment by ronocod** [comment]
Hi @sebikaplun,

Looks like you might be using an invalid API key or app ID there. Can you double check you're using the API key and app ID from your App Settings page in Intercom?

**Comment by sebikaplun** [comment]
@ronocod checking. thanks

**Comment by ronocod** [comment]
@sebikaplun did you manage to solve this?

**Comment by sebikaplun** [comment]
@ronocod yes! Fixed.
