### ISSUE TITLE
Beta - Error inflating class android.support.design.widget.CollapsingToolbarLayout

### ISSUE THREAD

**Issue by Mathbl** [intercom/intercom-android#209]
## Version info
  - Intercom for Android version: 3.0.0-beta4
  - Android OS version: 6.0
  - Android Device: Emulator 2.0

## Actual behavior
When I try to use the beta, it crashes when I call displayMessageComposer() (stack trace below).

It looks like a clash with support libraries or something. 

I use these version:
```gradle
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
```
and my intercom dependency looks like this:
```gradle
compile ('io.intercom.android:intercom-sdk:3.0.0-beta4') { transitive = true }
```

## Logs
```java
06-14 16:28:07.425 7121-7121/com.myapp.android E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.myapp.android, PID: 7121
  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.android/io.intercom.android.sdk.activities.IntercomMessengerActivity}: android.view.InflateException: Binary XML file line #15: Binary XML file line #20: Error inflating class android.support.design.widget.CollapsingToolbarLayout
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
      at android.app.ActivityThread.-wrap11(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5417)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
   Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #20: Error inflating class android.support.design.widget.CollapsingToolbarLayout
      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
      at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(ConversationFragment.java:254)
      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2058)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1099)
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1281)
      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1666)
      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610)
      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
      at android.app.Activity.performStart(Activity.java:6253)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5417) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
   Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class android.support.design.widget.CollapsingToolbarLayout
      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
      at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(ConversationFragment.java:254) 
      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2058) 
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1099) 
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1281) 
      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1666) 
      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610) 
      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
      at android.app.Activity.performStart(Activity.java:6253) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5417) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
   Caused by: java.lang.reflect.InvocationTargetException
      at java.lang.reflect.Constructor.newInstance(Native Method)
      at android.view.LayoutInflater.createView(LayoutInflater.java:619)
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
      at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(ConversationFragment.java:254) 
      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2058) 
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1099) 
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1281) 
      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1666) 
      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610) 
      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
      at android.app.Activity.performStart(Activity.java:6253) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5417) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
   Caused by: java.lang.NoSuchMethodError: No static method setLayoutDirection(Landroid/graphics/drawable/Drawable;I)V in class Landroid/support/v4/graphics/drawable/DrawableCompat; or its super classes (declaration of 'android.support.v4.graphics.drawable.DrawableCompat' appears in /data/app/com.myapp.android-2/base.apk:classes13.dex)
      at android.support.design.widget.CollapsingToolbarLayout.setStatusBarScrim(CollapsingToolbarLayout.java:663)
      at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:197)
      at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:132)
      at java.lang.reflect.Constructor.newInstance(Native Method) 
      at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
      at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
      at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(ConversationFragment.java:254) 
      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2058) 
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1099) 
      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1281) 
      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1666) 
      at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610) 
      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237) 
      at android.app.Activity.performStart(Activity.java:6253) 
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:148) 
      at android.app.ActivityThread.main(ActivityThread.java:5417) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
I will be glad to give more info if needed. Thanks!

**Comment by ronocod** [comment]
Hi @Mathbl,

This does look like a support library clash. Can you try including your Intercom dependency like this?

```gradle
compile('io.intercom.android:intercom-sdk:3.0.0-beta4') {
    transitive = true
    exclude group: 'com.android.support'
}
```

I'll also update our support library dependencies to `23.4.0` as we're currently using `23.3.0` in `beta4`.

**Comment by Mathbl** [comment]
@ronocod I had the opportunity to do some debugging and found the cause: one of my dependency used + in version number for support library. 

It looks like every support library dependencies were forced/overridden to 24.0.0-alpha1. Now intercom is working.

**Comment by ronocod** [comment]
Ah that makes sense. Thanks for letting us know 👍
