### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by cazador4** [intercom/intercom-android#213]
## Version info
  - Intercom for Android version: 1.1.21
  - Android OS version: 6.0.1
  - Android Device: samsung SM-G925I, samsung SM-G928G, samsung SM-G925F

## Additional info
We use splunk for errors.

## Logs
```
0 java.util.ConcurrentModificationException

1	at java.util.HashMap$HashIterator.remove(HashMap.java:806)

2	at com.splunk.mint.network.MonitorRegistry.getMetricsForName(MonitorRegistry.java:32)

3	at com.splunk.mint.network.socket.MonitoringSocketImpl.connect(MonitoringSocketImpl.java:139)

4	at java.net.Socket.connect(Socket.java:884)

5	at io.intercom.com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:197)

6	at  io.intercom.com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:137)

7	at io.intercom.com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)

8	at 
io.intercom.com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)

9	at io.intercom.com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)

10	at io.intercom.com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)

11	at io.intercom.com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)

12	at io.intercom.com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)

13	at io.intercom.com.squareup.okhttp.Call.getResponse(Call.java:286)

14	at io.intercom.com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)

15	at io.intercom.com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)

16	at io.intercom.com.squareup.okhttp.Call.access$100(Call.java:35)

17	at io.intercom.com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)

18	at io.intercom.com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)

19	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

20	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

21	at java.lang.Thread.run(Thread.java:818)
```

**Comment by ronocod** [comment]
This is an issue with Splunk's library, it's intercepting some of our networking code and causing a crash. Are you running the latest version of the Splunk library?

**Comment by cazador4** [comment]
Hi, We are using Splunk 4.0.7. Right now I'm updating to 5.0.0.
Do you want to close this issue?
Maybe if it comes back I will reopen the issue.

**Comment by ronocod** [comment]
Sure, I'll close this now. If it comes back again let us know :)
