### ISSUE TITLE
Photo Upload: Null Pointer Exception

### ISSUE THREAD

**Issue by szingel** [intercom/intercom-android#214]
## Version info
  - Intercom for Android version: 3.0.0-beta4
  - Android OS version: 6.0.1
  - Android Device: Samsung SM-G925A

## Logs
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.addView(android.view.View)' on a null object reference
       at io.intercom.android.sdk.photoview.PhotoViewAttacher.animateImageLoadIn(PhotoViewAttacher.java:242)
       at io.intercom.android.sdk.photoview.PhotoViewAttacher.<init>(PhotoViewAttacher.java:547)
       at io.intercom.android.sdk.blocks.NetworkImage.displayImage(NetworkImage.java:49)
       at io.intercom.android.sdk.blocks.NetworkImage.access$100(NetworkImage.java:39)
       at io.intercom.android.sdk.blocks.NetworkImage$1$1.onClick(NetworkImage.java:113)
       at android.view.View.performClick(View.java:5697)
       at android.view.View$PerformClick.run(View.java:22526)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ronocod** [comment]
Thanks for reporting this, this will be fixed in the next beta release.

**Comment by DaleCantwell** [comment]
Hi @szingel 
We are out of beta! This issue is now fixed in our new release 3.0.0 https://github.com/intercom/intercom-android/releases/tag/3.0.0
Thanks again for letting us know about the issue.
