### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError in NexusSocket.java line 55

### ISSUE THREAD

**Issue by bendikv** [intercom/intercom-android#221]
Intercom causes crash the app very frequently

## Version info
  - Intercom for Android version: latest (1.x)
  - Android OS version: 6.x
  - Android Device: Samsung, LGE, Sony and other...

## Logs

`
Fatal Exception: java.lang.OutOfMemoryError: Could not allocate JNI Env
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at io.intercom.android.sdk.nexus.NexusSocket.<init>(NexusSocket.java:55)
       at io.intercom.android.sdk.nexus.NexusClient.connect(NexusClient.java:39)
       at io.intercom.android.sdk.NexusWrapper.connect(NexusWrapper.java:19)
       at io.intercom.android.sdk.NexusWrapper.cycle(NexusWrapper.java:31)
       at io.intercom.android.sdk.identity.AppConfig.update(AppConfig.java:129)
       at io.intercom.android.sdk.identity.AppIdentity.updateAppConfig(AppIdentity.java:41)
       at io.intercom.android.sdk.identity.IdentityStore.setAppConfig(IdentityStore.java:55)
       at io.intercom.android.sdk.api.CallbackHolder.updateAppConfig(CallbackHolder.java:131)
       at io.intercom.android.sdk.api.CallbackHolder.updateBaseResponseObjects(CallbackHolder.java:123)
       at io.intercom.android.sdk.api.CallbackHolder.access$000(CallbackHolder.java:31)
       at io.intercom.android.sdk.api.CallbackHolder$3.onSuccess(CallbackHolder.java:67)
       at io.intercom.android.sdk.api.CallbackHolder$3.onSuccess(CallbackHolder.java:64)
       at io.intercom.android.sdk.api.BaseCallback.success(BaseCallback.java:22)
       at io.intercom.retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
`

**Comment by DaleCantwell** [comment]
@bendikv thanks for reporting the issue to us. I believe the root cause of the issue is the same as these:
https://github.com/intercom/intercom-android/issues/197
https://github.com/intercom/intercom-android/issues/136
We have resolved the issue in our next major release. That release is currently in beta and will be available very soon.

**Comment by ronocod** [comment]
We've released version 3.0.0 which fixes this by using less threads and limiting the number of threads we create. If you still see this issue after updating to 3.0.0 please let us know.
