### ISSUE TITLE
Invalid key: name IllegalArgumentException in Phrase.java

### ISSUE THREAD

**Issue by farukcankaya** [intercom/intercom-android#227]
## Version info
- Intercom for Android version: 3.0.2
- Android OS version: 6.0.1
- Android Device: HTC M8
## Actual behavior

throws exception when _setInAppMessageVisibility_ method is called.

It says "Invalid key: name", I've debugged io.intercom.android.sdk.utilities.Phrase.put(String key, CharSequence value) method. The key was "name", values was "Faruk". But I don't set a key named "name". I've only send these attributes "User Id", "First Name", "Last Name", "Full Name", "E-mail Address".. as a user attribute. 

I don't understand the problem.
## Logs

```
07-28 16:52:47.912 9943-9943/ E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: , PID: 9943
                                                                       java.lang.IllegalArgumentException: Invalid key: name
                                                                           at io.intercom.android.sdk.utilities.Phrase.put(Phrase.java:138)
                                                                           at io.intercom.android.sdk.preview.Overlay.getHeaderText(Overlay.java:164)
                                                                           at io.intercom.android.sdk.preview.StackableSnippet.setViewData(StackableSnippet.java:81)
                                                                           at io.intercom.android.sdk.preview.StackableSnippet.display(StackableSnippet.java:44)
                                                                           at io.intercom.android.sdk.preview.NotificationManager.addNewNotifications(NotificationManager.java:191)
                                                                           at io.intercom.android.sdk.preview.NotificationManager.displayPreviews(NotificationManager.java:160)
                                                                           at io.intercom.android.sdk.preview.NotificationManager.access$000(NotificationManager.java:38)
                                                                           at io.intercom.android.sdk.preview.NotificationManager$3.run(NotificationManager.java:93)
                                                                           at io.intercom.android.sdk.utilities.ViewUtils$1.onGlobalLayout(ViewUtils.java:25)
                                                                           at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2051)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1162)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6229)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:676)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:168)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

**Comment by ronocod** [comment]
The key `name` is used in our localisation system, it's not related to user attributes. What system language was the device using at the time?

**Comment by farukcankaya** [comment]
@ronocod French

**Comment by farukcankaya** [comment]
But it's not related with language. I've got another crash now when I tried to open message composer.

`````
FATAL EXCEPTION: main
 Process: com.twentify.bounty.dev, PID: 11595
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.twentify.bounty.dev/io.intercom.android.sdk.activities.IntercomMessengerActivity}: java.lang.IllegalArgumentException: Invalid key: name
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2484)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
     at android.app.ActivityThread.access$900(ActivityThread.java:150)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:168)
     at android.app.ActivityThread.main(ActivityThread.java:5845)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
  Caused by: java.lang.IllegalArgumentException: Invalid key: name
     at io.intercom.android.sdk.utilities.Phrase.put(Phrase.java:138)
     at io.intercom.android.sdk.activities.IntercomMessengerActivity.setUpToolBar(IntercomMessengerActivity.java:301)
     at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:76)
     at android.app.Activity.performCreate(Activity.java:6248)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
     at android.app.ActivityThread.access$900(ActivityThread.java:150) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:168) 
     at android.app.ActivityThread.main(ActivityThread.java:5845) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
`````

In this code block below, the variable `keys` always stays empty maybe this could help you to fix issue.
`````
public Phrase put(String key, CharSequence value) {
        if(!this.keys.contains(key)) {
            throw new IllegalArgumentException("Invalid key: " + key);
        } else if(value == null) {
            throw new IllegalArgumentException("Null value for \'" + key + "\'");
        } else {
            this.keysToValues.put(key, value);
            this.formatted = null;
            return this;
        }
    }
`````

**Comment by ronocod** [comment]
That's unusual, it doesn't seem to be reading the parameter keys in the translation strings. The `{name}` key seems to be present in the actual strings so it mustn't be loading the strings correctly. Investigating now. If you are debugging it again, it might be helpful to see what value the `pattern` field has, it should have text with `{name}` in it, like `Conversations avec {name}`.

**Comment by ronocod** [comment]
Does this still happen in 3.0.4? We made some changes to the handling of our `Resources` objects so this might be fixed.

**Comment by ronocod** [comment]
We haven't been able to reproduce this and I think the Resources change in 3.0.4 will have fixed this. If you see it happening again please let us know.

**Comment by vahidlazio** [comment]
this issue is happening over and over again even with the latest sdk update. please follow up.

**Comment by harkin** [comment]
@vahidlazio thanks for letting us know, is it the same issue as described in the first few reports? 

Do you have any additional details you could add like what languages you're seeing it for, or anything? We weren't able to reproduce locally and had changed how we did some resource handling in a way that we _thought_ would make this safer. Steps to reproduce the crash in a small sample app would be greatly appreciated if you could provide that.

**Comment by vahidlazio** [comment]
The language of the user at the time of crash was arabic, the stack trace is as the following .

Exception java.lang.IllegalArgumentException: Invalid key: name
io.intercom.android.sdk.utilities.Phrase.put ()
io.intercom.android.sdk.inbox.InboxFragment.displayEmptyView ()
io.intercom.android.sdk.inbox.InboxFragment.onStateChange ()
io.intercom.android.sdk.inbox.InboxFragment.onStateChange ()
io.intercom.android.sdk.utilities.ChangeSubscriber.onStateChange ()
io.intercom.android.sdk.store.Store$1.dispatch ()
io.intercom.android.sdk.store.Store$2.dispatch ()
io.intercom.android.sdk.middleware.LoggerMiddleware.dispatch ()
io.intercom.android.sdk.store.Store$3.dispatch ()
io.intercom.android.sdk.store.Store.dispatch ()
io.intercom.android.sdk.api.CallbackHolder$4.onSuccess ()
io.intercom.android.sdk.api.CallbackHolder$4.onSuccess ()
io.intercom.android.sdk.api.BaseCallback.onResponse ()
io.intercom.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run ()
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7229)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by ronocod** [comment]
@vahidlazio Which version of the SDK are you running? It looks like it might not be the latest version.

**Comment by ronocod** [comment]
That error message was changed in version 3.0.13 of the SDK, so you must be running an older version. Please try the latest version and let us know if you have any problems.
