### ISSUE TITLE
Application crashes when back button clicked in a chat conversation 

### ISSUE THREAD

**Issue by apo1981** [intercom/intercom-android#248]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.0.4
  - Android OS version: 6.0.1
  - Android Device: Nexus 6P

## Expected behavior
Close the chat conversation without crashing the app

## Actual behavior
App crashes when Up back button is pressed in a chat conversation.
Let me also indicates that rest of functionality seems to work correctly: in-app notes, in-app post, push messages and email messages

## Steps to reproduce
 1. Send a chat in-app message to a user (this user is an Unidentified User)
 2. Open the chat in your app
 3. Press back button on the left-up side (see screenshot below)

![screenshot_20160823-181051](https://cloud.githubusercontent.com/assets/21215494/17923633/587ee7a0-69e5-11e6-8862-ab6f781c54e9.png)

## More Information
Application is built with:
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:recyclerview-v7:24.2.0'

compileSdkVersion: 24
buildToolsVersion: 24.0.1
minSdkVersion: 15

## Logs

Fatal Exception: android.view.InflateException: Binary XML file line #44: Binary XML file line #44: Error inflating class android.support.design.widget.FloatingActionButton
       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at io.intercom.android.sdk.inbox.ConversationsListFragment.onCreateView(ConversationsListFragment.java:112)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by android.view.InflateException: Binary XML file line #44: Error inflating class android.support.design.widget.FloatingActionButton
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at io.intercom.android.sdk.inbox.ConversationsListFragment.onCreateView(ConversationsListFragment.java:112)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at io.intercom.android.sdk.inbox.ConversationsListFragment.onCreateView(ConversationsListFragment.java:112)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NoSuchMethodError: No direct method <init>(Landroid/widget/ImageView;Landroid/support/v7/widget/AppCompatDrawableManager;)V in class Landroid/support/v7/widget/AppCompatImageHelper; or its super classes (declaration of 'android.support.v7.widget.AppCompatImageHelper' appears in /data/data/example.intercom.app/files/instant-run/dex/slice-com.android.support-appcompat-v7-24.2.0_410d52b8fd7997122f7913342dc7d8429ee6c357-classes.dex)
       at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:170)
       at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:147)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at io.intercom.android.sdk.inbox.ConversationsListFragment.onCreateView(ConversationsListFragment.java:112)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Please, do not hesitate to request more information if required

**Comment by ronocod** [comment]
3.0.4 uses version 24.1.1 of the support library, I'd imagine this is caused by conflicts with 24.2.0. We'll release a new version using 24.2.0 soon, and I'll update this issue when it's out.

**Comment by apo1981** [comment]
Thank you, fixed changing support library version
Please, let me suggest to indicate in next release note what support library versions are compatible

**Comment by ronocod** [comment]
We list our dependencies and the versions we use at the bottom of our README.md file: https://github.com/intercom/intercom-android/#dependency-graph

**Comment by apo1981** [comment]
Ok, thks. Sorry for that comment. Will have in mind next time. Again, thks for your quick and efficient support

**Comment by ronocod** [comment]
No problem 😄

**Comment by ronocod** [comment]
We now use version 24.2.0 of the support library 🎉
