### ISSUE TITLE
FCM Integration

### ISSUE THREAD

**Issue by ktalmeida** [intercom/intercom-android#249]
## Version info
  - Intercom for Android version: 3.0.4
  - Android OS version: 6.0.3
  - Android Device: Sony Xperia Z3 Compact

## Actual behavior
After migrating my project to fcm, my devices do not appear inside the audience part when I try to send a push notification. Already updated google-services.json, changed the server key and they still do not appear. 
Also tried to create a new fcm project from scratch. 
Still no success, my user appears inside Users page but not as an option inside Send Manual Message. 

Another thing: Inside Firebase console interface I can send a push notification correctly. Seems like intercom is not getting user's token.

**Comment by hemb** [comment]
I have the same problem with FCM. I just started using Intercom, so haven't used GCM before. My user says "ENABLED PUSH MESSAGING: Unknown".

I can also send push messages from the Firebase console.

**Comment by hemb** [comment]
It looks like the FCM token is set correctly on my Intercom user now.

When I try to send a manual message nothing is displayed, but I get the following log output:

`08-30 11:19:21.834 5941-5941/? W/ResourceType: No known package when getting value for resource number 0xffffffff
08-30 11:19:21.837 5941-5941/? W/ImageView: Unable to find resource: -1
  android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
      at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
      at android.content.res.Resources.getDrawable(Resources.java:766)
      at android.content.Context.getDrawable(Context.java:525)
      at android.widget.ImageView.resolveUri(ImageView.java:840)
      at android.widget.ImageView.setImageResource(ImageView.java:439)
      at o.ex.setImageResource(SourceFile:267)
      at java.lang.reflect.Method.invoke(Native Method)
      at android.widget.RemoteViews$ReflectionAction.apply(RemoteViews.java:1410)
      at android.widget.RemoteViews.performApply(RemoteViews.java:3428)
      at android.widget.RemoteViews.reapply(RemoteViews.java:3382)
      at android.appwidget.AppWidgetHostView.applyRemoteViews(AppWidgetHostView.java:439)
      at android.widget.RemoteViewsAdapter$RemoteViewsFrameLayout.onRemoteViewsLoaded(RemoteViewsAdapter.java:306)
      at android.widget.RemoteViewsAdapter.getView(RemoteViewsAdapter.java:1110)
      at android.widget.AbsListView.obtainView(AbsListView.java:2360)
      at android.widget.ListView.makeAndAddView(ListView.java:1972)
      at android.widget.ListView.fillDown(ListView.java:704)
      at android.widget.ListView.fillSpecific(ListView.java:1412)
      at android.widget.ListView.layoutChildren(ListView.java:1708)
      at android.widget.AbsListView.onLayout(AbsListView.java:2161)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
      at android.appwidget.AppWidgetHostView.onLayout(AppWidgetHostView.java:248)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at o.fh.onLayout(SourceFile:205)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at com.android.launcher3.CellLayout.onLayout(SourceFile:1066)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at o.I9.onLayout(SourceFile:1229)
      at com.android.launcher3.Workspace.onLayout(SourceFile:2012)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
      at com.android.launcher3.DragLayer.onLayout(SourceFile:611)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
      at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
      at android.view.View.layout(View.java:17519)
      at android.view.ViewGroup.layout(ViewGroup.java:5612)
      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2342)
      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
08-30 11:19:21.838 5941-5941/? W/ImageView:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
      at android.view.Choreographer.doCallbacks(Choreographer.java:683)
      at android.view.Choreographer.doFrame(Choreographer.java:619)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
      at android.os.Handler.handleCallback(Handler.java:751)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6077)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by DaleCantwell** [comment]
Hi @hemb,

The issue in that trace looks like there is a missing image resource. Do you have an asset named intercom_push_icon.png in your all your drawable dpi folders?

Are you extending FirebaseMessagingService in a class in your own app? If so you will need to manually pass on the push to us.

```JAVA
  private final IntercomPushClient intercomPushClient = new IntercomPushClient();
  public void onMessageReceived(RemoteMessage remoteMessage) {
      Map<String, String> message = remoteMessage.getData();
      if (intercomPushClient.isIntercomPush(message)) {
          intercomPushClient.handlePush(getApplication(), message);
      } else {
          //DO HOST LOGIC HERE
     }
 }
```

**Comment by jessexx** [comment]
Hi @hemb, I'm having the issue where I can send push messages from the Firebase console but am not able to send user-specific push messages via Intercom.  Can you tell me how you set the FCM token on an Intercom user?

**Comment by ktalmeida** [comment]
That's exactly my problem @jessexx, I rechecked 100 times my token inside Intercom's interface, also config.json files and nothing.

**Comment by CliveTeow** [comment]
I having the same problem.

**Comment by hemb** [comment]
@jessexx, @ktalmeida, @CliveTeow I have got it working now. I'm not 100% that it's necessary, but inside my `FirebaseInstanceIdService.onTokenRefresh()` I copied the code from Intercom's `IntercomFcmInstanceIdService.sendTokenToIntercom()`

```
if (!DeviceData.hasCachedPushToken(context, token)) {
    Injector.get().getApi().setDeviceToken(token);
    DeviceData.cachePushToken(context, token);
}
```

I'm also passing on the push message to Intercom in my `FirebaseMessagingService` as suggested by @DaleCantwell 

@ktalmeida Where can you check the token in Intercoms's interface?

@DaleCantwell I think the stack trace I posted was related to something else. Do we need to pass on the push token to you if we extend `FirebaseInstanceIdService`?

**Comment by CliveTeow** [comment]
@hemb Thanks a lot.  :) 
I have also figured out this just now. For those who has subclass of FirebaseInstanceIdService, should pass the token to intercom.
    @Override
    public void onTokenRefresh() {
        String refreshedToken = FirebaseInstanceId.getInstance().getToken();

        if(TextUtils.isEmpty(refreshedToken)) {
            IntercomLogger.e("Intercom push registration failed. Please make sure you have added a google-services.json file");
        } else {
            this.sendTokenToIntercom(refreshedToken);
            // own logic
        }
    }

    private void sendTokenToIntercom(String token) {
        Context context = this.getApplicationContext();
        if(!DeviceData.hasCachedPushToken(context, token)) {
            Injector.get().getApi().setDeviceToken(token);
            DeviceData.cachePushToken(context, token);
        }

    }

**Comment by AkhilDad** [comment]
@hemb Thanks it worked for me. I was struggling from yesterday.

**Comment by ktalmeida** [comment]
Thanks a lot! This should be documented =)

**Comment by DaleCantwell** [comment]
Thanks for the feedback everyone. We have released [3.0.7 ](https://github.com/intercom/intercom-android/releases/tag/3.0.7) today and it has updated our IntercomPushClient class to allow you to pass us on your device token. Updating docs today but for anyone who wants to update I have attached instructions below. Let us know if you run into any difficulty.

**Using Intercom with other FCM setups**

This only applies to applications that also use FCM for their own content, or use a third party service for FCM. You will need update your FirebaseInstanceIdService and FirebaseMessagingService.

You should have a class that extends FirebaseInstanceIdService. That service is where you get the device token to send to your backend to register for push. To register for Intercom push set up your FirebaseInstanceIdService like this:

```JAVA
private final IntercomPushClient intercomPushClient = new IntercomPushClient();

@Override public void onTokenRefresh() {
    String refreshedToken = FirebaseInstanceId.getInstance().getToken();
    pushClient.sendTokenToIntercom(getApplication(), refreshedToken);
   //DO HOST LOGIC HERE
}
```

You should have a class that extends FirebaseMessagingService. That service will consume pushes intended for Intercom. To allow us to draw the Intercom push set up your FirebaseMessagingService like this:

```JAVA
private final IntercomPushClient intercomPushClient = new IntercomPushClient();

public void onMessageReceived(RemoteMessage remoteMessage) {
    Map<String, String> message = remoteMessage.getData();
    if (intercomPushClient.isIntercomPush(message)) {
        intercomPushClient.handlePush(getApplication(), message);
    } else {
        //DO HOST LOGIC HERE
    }
}
```

**Comment by eoinahern** [comment]
so essentially. i have to call my own backend api AFTER intercom messages my app? or can i just get the message direct from intercom and handle it in an android service to show a notification on the home screen. NOT in app. thanks

**Comment by aman-oodles** [comment]
DeviceData.hasCachedPushToken,DeviceData.cachedPushToken not found in my project, can you please help me to fix this issue
