### ISSUE TITLE
Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException

### ISSUE THREAD

**Issue by Mathbl** [intercom/intercom-android#251]
Saw this crash from Crashlytics. Only 1 device/user for now. This happened in my signOut method in which I call `Intercom.client().reset();`. Here are the info I have:

## Version info
  - Intercom for Android version: 3.0.4
  - Android OS version: 6.0.1
  - Android Device: SM-G920W8 (S6)

## Logs
```java
Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8181)
       at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1307)
       at android.view.ViewGroup.invalidateChild(ViewGroup.java:5428)
       at android.view.View.invalidateInternal(View.java:13932)
       at android.view.View.invalidate(View.java:13896)
       at android.view.View.invalidate(View.java:13880)
       at android.widget.ImageView.invalidateDrawable(ImageView.java:262)
       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:844)
       at android.graphics.drawable.Drawable.setVisible(Drawable.java:1575)
       at android.graphics.drawable.LayerDrawable.setVisible(LayerDrawable.java:1231)
       at android.widget.ImageView.onDetachedFromWindow(ImageView.java:1511)
       at android.view.View.dispatchDetachedFromWindow(View.java:15851)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3372)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3372)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3372)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4950)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4923)
       at android.view.ViewGroup.removeView(ViewGroup.java:4854)
       at io.intercom.android.sdk.preview.PreviewManager.conditionallyRemovePreview(PreviewManager.java:287)
       at io.intercom.android.sdk.preview.PreviewManager.reset(PreviewManager.java:135)
       at io.intercom.android.sdk.RealIntercom.reset(RealIntercom.java:319)
       at com.myapp.android.models.Session.signOut(Session.java:355)
       at com.myapp.android.models.Session$5.run(Session.java:400)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by ronocod** [comment]
Thanks for reporting this, we're looking into it now.

**Comment by ronocod** [comment]
This part of the code is called from the main thread in 3.0.6, updating to that version should fix this.
