### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError android.view.ViewGroup.isInLayout

### ISSUE THREAD

**Issue by yonatancups** [intercom/intercom-android#252]
## Version info
  - Intercom for Android version: 3.0.5
  - Android OS version: 4.1.2
  - Android Device: LG-P714

## Steps to reproduce
 1. Open intercom
 2. Go into conversation from the list
 3. App crashes

## Logs
Fatal Exception: java.lang.NoSuchMethodError: android.view.ViewGroup.isInLayout
       at io.intercom.android.sdk.profile.TeammateProfileToolbarBehavior.onOffsetChanged(TeammateProfileToolbarBehavior.java:141)
       at android.support.design.widget.AppBarLayout.dispatchOffsetUpdates(AppBarLayout.java:464)
       at android.support.design.widget.AppBarLayout.access$000(AppBarLayout.java:104)
       at android.support.design.widget.AppBarLayout$Behavior.setHeaderTopBottomOffset(AppBarLayout.java:1149)
       at android.support.design.widget.AppBarLayout$Behavior.getScrollRangeForDragFling(AppBarLayout.java:755)
       at android.support.design.widget.HeaderBehavior.setHeaderTopBottomOffset(HeaderBehavior.java:194)
       at android.support.design.widget.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1048)
       at android.support.design.widget.AppBarLayout$Behavior.getScrollRangeForDragFling(AppBarLayout.java:755)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:852)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1003)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1680)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1538)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1451)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
       at android.view.View.layout(View.java:13844)
       at android.view.ViewGroup.layout(ViewGroup.java:4364)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1892)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1708)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1009)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4248)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4929)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ronocod** [comment]
We've merged a fix for this and will be releasing 3.0.6 today with it included.

**Comment by ronocod** [comment]
3.0.6 is now released and fixes this issue.
