### ISSUE TITLE
Crash at SoundPlayer.java line 26

### ISSUE THREAD

**Issue by chuyeoh** [intercom/intercom-android#266]
## Version info
- Intercom for Android version: 3.0.5
- Android OS version: 7.0
- Android Device: Nexus 6P
## Logs

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: unable to stat file for the library "/system/lib/libsoundpool.so": Bad file descriptor
       at java.lang.Runtime.loadLibrary0(Runtime.java:999)
       at java.lang.System.loadLibrary(System.java:1530)
       at android.media.SoundPool.<clinit>(SoundPool.java:115)
       at io.intercom.android.sdk.conversation.SoundPlayer.<init>(SoundPlayer.java:26)
       at io.intercom.android.sdk.Injector.getPreviewManager(Injector.java:149)
       at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:70)
       at io.intercom.android.sdk.Intercom.initialize(Intercom.java:43)
       at com.homepass.agent.app.HomepassApplication.onCreate(HomepassApplication.java:70)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ronocod** [comment]
Has this crash been happening often? If `libsoundpool` can't be found then I would imagine a lot of apps would crash when trying to play sound on that device.

**Comment by chuyeoh** [comment]
As The OS version is 7.0, we only have one client experiencing this.

**Comment by ronocod** [comment]
This sounds like a really isolated case, possibly where the user has a broken custom ROM installed.  `libsoundpool` is shipped with all Android we support (including 7.0) and is [depended on in the Android codebase](http://androidxref.com/7.0.0_r1/xref/frameworks/base/media/java/android/media/SoundPool.java#115) so I can't imagine any working devices that would not have it present. Are you happy to close this, and we can investigate more if the problem comes up again?

**Comment by ronocod** [comment]
Closing this as it looks like an isolated case of a broken OS installation.

**Comment by razmaimon** [comment]
we had one issue like this as well.
[com.hp.printosforpsp_issue_411_crash_595E5A66019000012C6EDCE9B8C07A89_19016c19626211e78a2556847afe9799_0_v2.txt](https://github.com/intercom/intercom-android/files/1158330/com.hp.printosforpsp_issue_411_crash_595E5A66019000012C6EDCE9B8C07A89_19016c19626211e78a2556847afe9799_0_v2.txt)
