### ISSUE TITLE
Couldn't find io.intercom.retrofit2.http.POST.value

### ISSUE THREAD

**Issue by Digisha** [intercom/intercom-android#277]
We are recently getting following errors in our app:

## Version info
  - Intercom for Android version: 3.0.8
  - Android OS version: 5.0.1
  - Android Device: SCH-R970

## Expected behavior
App crashes

## Actual behavior
App should not crash

## Logs

```
java.lang.IncompatibleClassChangeError: Couldn't find io.intercom.retrofit2.http.POST.value
1	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
2	at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
3	at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
4	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:293)
5	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:104)
6	at java.lang.reflect.AbstractMethod.getAnnotations(AbstractMethod.java:187)
7	at java.lang.reflect.Method.getAnnotations(Method.java:89)
!	8	at io.intercom.retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:230)
9	at io.intercom.retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:160)
10	at io.intercom.retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
11	at io.intercom.retrofit2.Retrofit$1.invoke(Retrofit.java:145)
12	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
13	at io.intercom.android.sdk.api.$Proxy2.sendMetrics(.java)
14	at io.intercom.android.sdk.api.Api.sendMetrics(Api.java:445)
15	at io.intercom.android.sdk.metrics.MetricsStore.sendMetrics(MetricsStore.java:70)
16	at io.intercom.android.sdk.metrics.MetricsStore$4.run(MetricsStore.java:130)
17	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
18	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
19	at java.lang.Thread.run(Thread.java:818)
```

and

```
java.lang.IncompatibleClassChangeError: Couldn't find io.intercom.retrofit2.http.PUT.value
1	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
2	at libcore.reflect.AnnotationAccess.annotationSetToAnnotations(AnnotationAccess.java:633)
3	at libcore.reflect.AnnotationAccess.getDeclaredAnnotations(AnnotationAccess.java:161)
4	at java.lang.reflect.Method.getDeclaredAnnotations(Method.java:293)
5	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:104)
6	at java.lang.reflect.AbstractMethod.getAnnotations(AbstractMethod.java:187)
7	at java.lang.reflect.Method.getAnnotations(Method.java:89)
!	8	at io.intercom.retrofit2.ServiceMethod$Builder.<init>(ServiceMethod.java:154)
9	at io.intercom.retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
10	at io.intercom.retrofit2.Retrofit$1.invoke(Retrofit.java:145)
11	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
12	at io.intercom.android.sdk.api.$Proxy2.deleteDeviceToken(.java)
13	at io.intercom.android.sdk.api.Api.removeGcmDeviceToken(Api.java:133)
14	at io.intercom.android.sdk.RealIntercom.reset(RealIntercom.java:296)
15	at com.mobiledefense.lean.intercom.IntercomGatewayImpl.registerUser(IntercomGatewayImpl.java:44)
```

**Comment by ronocod** [comment]
Is your app using Proguard or Multidex?

**Comment by Digisha** [comment]
Yes, Proguard and Multidex are enabled in our builds.

**Comment by ronocod** [comment]
Is this happening on one particular device or many devices of that model?

**Comment by Digisha** [comment]
Looks like different devices of Samsung Galaxy S4 running 5.0.1

**Comment by ronocod** [comment]
Looks like a system bug on those devices: https://code.google.com/p/android/issues/detail?id=172339

I'll keep looking into this to see if there's a fix we can implement.

**Comment by ronocod** [comment]
Is this affecting all S4 devices running 5.0.1 or just some? I'm not sure we'll be able to fix this, but I'll continue investigating it.

**Comment by Digisha** [comment]
Some of s4 devices running 5.0.1.

Also, We are seeing following on S4 too. It has different stacktrace but caused by `java.lang.IncompatibleClassChangeError`

```
java.lang.IncompatibleClassChangeError: Couldn't find io.intercom.com.a.a.a.c.a
1	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
2	at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
3	at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
4	at java.lang.reflect.Field.getAnnotation(Field.java:242)
!	5	at io.intercom.com.a.a.b.a.i.a(ReflectiveTypeAdapterFactory.java:72)
6	at io.intercom.com.a.a.b.a.i.a(ReflectiveTypeAdapterFactory.java:159)
7	at io.intercom.com.a.a.b.a.i.a(ReflectiveTypeAdapterFactory.java:100)
8	at io.intercom.com.a.a.e.a(Gson.java:423)
9	at io.intercom.com.a.a.e.a(Gson.java:886)
10	at io.intercom.com.a.a.e.a(Gson.java:852)
11	at io.intercom.com.a.a.e.a(Gson.java:801)
12	at io.intercom.com.a.a.e.a(Gson.java:773)
13	at io.intercom.android.sdk.metrics.MetricsStore.readMetricsFromDisk(MetricsStore.java:153)
14	at io.intercom.android.sdk.metrics.MetricsStore.access$200(MetricsStore.java:25)
15	at io.intercom.android.sdk.metrics.MetricsStore$4.run(MetricsStore.java:129)
16	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
17	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
18	at java.lang.Thread.run(Thread.java:818)
```

**Comment by ronocod** [comment]
We've looked into this and I don't think we'll be able to fix this issue on our side. The issue present in these OS versions means that annotation-based code can fail. This affects a lot of essential code in the Messenger and there's no way for us to prevent it without a large rewrite. The fact that this is only happening on some S4 devices implies that this was fixed in an OS update that some users don't have.

If you can detect the devices running those faulty OS versions and not call any Intercom-related code on them then the rest of your app should work as normal.
