### ISSUE TITLE
Crash: Could not dispatch event: class io.intercom.android.sdk.conversation.events.SendingEvent

### ISSUE THREAD

**Issue by appmagnetics** [intercom/intercom-android#285]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.0.12
  - Android OS version: 6.0.1
  - Android Device: ONEPLUS A30000

## Expected behavior
No crash 

## Actual behavior
Crash (at customer's device) 

## Steps to reproduce
Impossible to obtain (caught over fabric.io)

## Logs

Fatal Exception: java.lang.RuntimeException: Could not dispatch event: class io.intercom.android.sdk.conversation.events.SendingEvent to handler [EventHandler public void io.intercom.android.sdk.conversation.ConversationFragment.sendMessage(io.intercom.android.sdk.conversation.events.SendingEvent)]: length=0; index=0
       at io.intercom.com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
       at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:387)
       at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
       at io.intercom.com.squareup.otto.Bus.post(Bus.java:337)
       at io.intercom.android.sdk.MainThreadBus.post(MainThreadBus.java:18)
       at io.intercom.android.sdk.conversation.ComposerInputView.onClick(ComposerInputView.java:100)
       at android.view.View.performClick(View.java:5233)
       at android.view.View$PerformClick.run(View.java:21209)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:152)
       at android.app.ActivityThread.main(ActivityThread.java:5507)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at io.intercom.android.sdk.conversation.ConversationFragment.onRequestPermissionsResult(ConversationFragment.java:1126)
       at android.support.v4.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:911)
       at android.app.Activity.requestPermissions(Activity.java:3876)
       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:45)
       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
       at android.support.v4.app.FragmentActivity.requestPermissionsFromFragment(FragmentActivity.java:1001)
       at android.support.v4.app.FragmentActivity$HostCallbacks.onRequestPermissionsFromFragment(FragmentActivity.java:1060)
       at android.support.v4.app.Fragment.requestPermissions(Fragment.java:1067)
       at io.intercom.android.sdk.conversation.ConversationFragment.attachmentTapped(ConversationFragment.java:1112)
       at io.intercom.android.sdk.conversation.ConversationFragment.sendMessage(ConversationFragment.java:1100)
       at java.lang.reflect.Method.invoke(Method.java)
       at io.intercom.com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
       at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:385)
       at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
       at io.intercom.com.squareup.otto.Bus.post(Bus.java:337)
       at io.intercom.android.sdk.MainThreadBus.post(MainThreadBus.java:18)
       at io.intercom.android.sdk.conversation.ComposerInputView.onClick(ComposerInputView.java:100)
       at android.view.View.performClick(View.java:5233)
       at android.view.View$PerformClick.run(View.java:21209)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:152)
       at android.app.ActivityThread.main(ActivityThread.java:5507)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by ronocod** [comment]
Thanks for reporting this, we're looking into a fix now.

**Comment by ronocod** [comment]
This is fixed in 3.0.13.
