### ISSUE TITLE
Unable to resolve buildConfigField after Intercom integration

### ISSUE THREAD

**Issue by stoichoandreev** [intercom/intercom-android#290]
## Version info
  - Intercom for Android version: 3.+
  - Android OS version: 4.4.4
  - Android Device: Genymotion (HTC One)

## Expected behavior
The app should start normal

## Actual behavior
The app is crashing when start
## Steps to reproduce
 1. Implement Intercom SDK with firebase messaging
 2. Include Intercom firebase dependancies into build gradle ('io.intercom.android:intercom-sdk-base:3.+' and 'io.intercom.android:intercom-sdk-fcm:3.+')
 3. Add Intercom.initialize(this, "your_key", "your_app_id"); into custom application class
4. My build gradle has build types config like this:
`buildTypes {
            debug {
                debuggable true
                applicationIdSuffix ".debug"
                versionNameSuffix "-debug"
                buildConfigField 'okhttp3.logging.HttpLoggingInterceptor.Level', 'RETROFIT_LOG_LEVEL', 'okhttp3.logging.HttpLoggingInterceptor.Level.BODY'
                buildConfigField 'boolean', 'ENABLE_USER_CREADITIONALS', 'true'
            }
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                buildConfigField 'okhttp3.logging.HttpLoggingInterceptor.Level', 'RETROFIT_LOG_LEVEL', 'okhttp3.logging.HttpLoggingInterceptor.Level.NONE'
                buildConfigField 'boolean', 'ENABLE_USER_CREADITIONALS', 'false'
            }
}`
5. I am not using any proguard rules at the moment!
6. In my custom application class I have something like that:
`@Override
    public void onCreate() {
        super.onCreate();

        instance = this;
        FacebookSdk.sdkInitialize(getApplicationContext());
        AppEventsLogger.activateApp(this);
        Fresco.initialize(getApplicationContext());
        Intercom.initialize(this, "key", "app_id");
        //setup Realm
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .schemaVersion(DatabaseRealm.REALM_VERSION)
                .deleteRealmIfMigrationNeeded()
                .build();

        Realm.setDefaultConfiguration(realmConfiguration);

        Fabric.with(this, new Crashlytics());

        //Use Stetho only for debug
        if(BuildConfig.DEBUG) {
            Stetho.initialize(
                    Stetho.newInitializerBuilder(this)
                            .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                            .enableWebKitInspector(RealmInspectorModulesProvider.builder(this).build())
                            .build());
        }

        ApplicationLifeCycleHandler lifeCycleHandler = new ApplicationLifeCycleHandler();
        registerActivityLifecycleCallbacks(lifeCycleHandler);
        registerComponentCallbacks(lifeCycleHandler);

    }`
7. If I remove the two new dependancies coming from Intercom integration , all looks good and all works perfect like it was before!
Thanks for you help.

## Logs
W/dalvikvm: VFY: unable to resolve static field 41255 (BODY) in Lokhttp3/logging/HttpLoggingInterceptor$Level;
D/dalvikvm: VFY: replacing opcode 0x62 at 0x0009
W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Ljavva/com/appscrollider/placed/BuildConfig;
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4c90b20)
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: javva.com.appscrollider.placed.debug, PID: 3579
                                                                                    java.lang.NoClassDefFoundError: okhttp3.logging.HttpLoggingInterceptor$Level
                                                                                        at javva.com.appscrollider.placed.BuildConfig.<clinit>(BuildConfig.java:17)
                                                                                        at javva.com.appscrollider.placed.PlacedApp.onCreate(PlacedApp.java:52)
                                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
                                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by ronocod** [comment]
Are you using Multidex with your app?

**Comment by stoichoandreev** [comment]
yes (multiDexEnabled =  true)

**Comment by ronocod** [comment]
Is your Application class extending `MultiDexApplication`? For MultiDex support on devices running 4.4 or below you need to use the MultiDex support library: https://developer.android.com/studio/build/multidex.html#mdex-pre-l

**Comment by stoichoandreev** [comment]
Yes , that was the issue, I forgot to extend from MultiDexApplication because, I just included multidex support before coupe of days. Need proguard rules. Thanks a lot!

**Comment by ronocod** [comment]
No problem :)
