### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by nerdmed** [intercom/intercom-android#298]
Dear Intercom Team,

we are are having trouble with the current android version. A lot of angry customers as we are serving tablets and a lot are stuck on Android <=4.4

This is what i get from the google Reports:

```
org.xmlpull.v1.XmlPullParserException
in android.graphics.drawable.Drawable.createFromXmlInner
```

## Version info
We are using: cordova-plugin-intercom@3.0.23

  - Intercom for Android version: 3.0.17
  - Android OS version: 4.4
  - Android Device: Galaxy Note 8.0 (konawifi)

## Expected behavior
I would expect the app to not crash 👍 
Maybe intercom exceptions can be generally caught, would be great for the user if the app at least works. 

## Actual behavior
App crashes on startup.

## Logs

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.NAME.app/io.intercom.android.sdk.activities.IntercomMessengerActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
	at android.app.ActivityThread.access$900(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f020052
	at android.content.res.Resources.loadDrawable(Resources.java:3066)
	at android.content.res.Resources.getDrawable(Resources.java:1627)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:723)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
	at io.intercom.android.sdk.activities.IntercomBaseActivity.onCreate(IntercomBaseActivity.java:21)
	at io.intercom.android.sdk.activities.IntercomMessengerActivity.onCreate(IntercomMessengerActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:5451)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
	... 11 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
	at android.content.res.Resources.loadDrawable(Resources.java:3062)
	... 31 more
```

**Comment by ronocod** [comment]
Are you using the latest versions of Cordova and the Cordova Android plugin? Older versions have issues with vector drawables on 4.4 devices.

**Comment by nerdmed** [comment]
@ronocod we are using the cordova android 5.2.2 version and Cordova 6.3.1 - do you know if these versions are affected?

**Comment by ronocod** [comment]
There's a good chance that Cordova Android versions below 6 will be affected, those use older versions of the Android build tools. Can you try updating Cordova Android to 6.1.0?

**Comment by nerdmed** [comment]
Unfortunately we are bound to the version [meteor](https://github.com/meteor/meteor) uses. But we have found a quick fix for that by adding the following to our `build.gradle`

```
 android {  
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }
```
