### ISSUE TITLE
Android base sdk warning: can't call method in a scroll callback.

### ISSUE THREAD

**Issue by jiaokang** [intercom/intercom-android#301]
When I  open the conversation list and scroll to the end, it loading more data.At this point , android report warning that you can't call this method in a scroll callback.  

## Version info
  - Intercom for Android version: intercom-sdk-base:3.+
  - Android OS version: Android 5.0
  - Android Device:Xiaomi 2s

## Steps to reproduce
 1. open the conversation list
 2. scroll to the end , and more data is loading.
 3. report warning

## Logs

 W/RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks might be run during a measure & layout pass where you cannot change the RecyclerView data. Any method call that might change the structure of the RecyclerView or the adapter contents should be postponed to the next frame.
                                                           java.lang.IllegalStateException: 
                                                               at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2463)
                                                               at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:4785)
                                                               at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:10769)
                                                               at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6347)
                                                               at io.intercom.android.sdk.inbox.InboxFragment.onStateChange(InboxFragment.java:339)
                                                               at io.intercom.android.sdk.inbox.InboxFragment.onStateChange(InboxFragment.java:54)
                                                               at io.intercom.android.sdk.utilities.ChangeSubscriber.onStateChange(ChangeSubscriber.java:33)
                                                               at io.intercom.android.sdk.store.Store$1.dispatch(Store.java:49)
                                                               at io.intercom.android.sdk.store.Store$2.dispatch(Store.java:63)
                                                               at io.intercom.android.sdk.middleware.PingMiddleware.dispatch(PingMiddleware.java:20)
                                                               at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:71)
                                                               at io.intercom.android.sdk.middleware.LoggerMiddleware.dispatch(LoggerMiddleware.java:17)
                                                               at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:71)
                                                               at io.intercom.android.sdk.store.Store.dispatch(Store.java:78)
                                                               at io.intercom.android.sdk.inbox.InboxFragment.onLoadMore(InboxFragment.java:284)
                                                               at io.intercom.android.sdk.views.EndlessRecyclerScrollListener.onScrolled(EndlessRecyclerScrollListener.java:36)
                                                               at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4389)
                                                               at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4634)
                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                               at android.view.Choreographer.doFrame(Choreographer.java:549)
                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by DaleCantwell** [comment]
@jiaokang thanks for reporting the issue, the fix will be included in 3.0.18
