### ISSUE TITLE
NPE on IntercomPushBroadcastReceiver

### ISSUE THREAD

**Issue by jackcsk** [intercom/intercom-android#304]
## Version info
  - Intercom for Android version: 3.0.10
  - Android OS version: 4.3.1
  - Android Device: Batmobile XT320

## Expected behavior
We've received NPE from IntercomPushBroadcastReceiver.
Not sure how to reproduce the issue as it was received from Crashlytics.
We will keep tracking if there are additional crash report.

## Logs
Fatal Exception: java.lang.RuntimeException: Unable to start receiver io.intercom.android.sdk.push.IntercomPushBroadcastReceiver: java.lang.NullPointerException
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2431)
       at android.app.ActivityThread.access$1500(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at io.intercom.android.sdk.push.PushBroadcast.<init>(PushBroadcast.java:21)
       at io.intercom.android.sdk.push.PushReceiverDelegate.dismissIntent(PushReceiverDelegate.java:117)
       at io.intercom.android.sdk.push.IntercomPushBroadcastReceiver.dismissIntent(IntercomPushBroadcastReceiver.java:35)
       at io.intercom.android.sdk.push.IntercomPushBroadcastReceiver.onReceive(IntercomPushBroadcastReceiver.java:21)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2424)
       at android.app.ActivityThread.access$1500(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by jackcsk** [comment]
In addition, we'll upgrade Intercom sdk to 3.0.18 on next app release.

**Comment by bboyle18** [comment]
Hi @jackcsk 

Thanks for reporting this issue. 👍 
We'll look into it.

Brian

**Comment by ronocod** [comment]
Fixed in 3.0.19.

**Comment by jackcsk** [comment]
wonderful. thx @bboyle18 & @ronocod
