### ISSUE TITLE
Crash when activity is destroyed

### ISSUE THREAD

**Issue by raedur** [intercom/intercom-android#305]
Getting a crash with stacktrace:
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
	at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.b(SourceFile:134)
	at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.a(SourceFile:102)
	at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.a(SourceFile:87)
	at io.intercom.com.bumptech.glide.Glide.b(SourceFile:629)
	at io.intercom.android.sdk.blocks.Video.createThumbnail(SourceFile:175)
	at io.intercom.android.sdk.blocks.Video$2$1.run(SourceFile:159)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7231)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Looks like it is related to https://github.com/bumptech/glide/issues/803https://github.com/bumptech/glide/issues/803. Creating a thumbnail should check to see if the activity is destroyed before loading it via Glide.

## Version info
  - Intercom for Android version: 3.0.18
  - Android OS version: 6.0.1
  - Android Device:  Samsung Galaxy Tab S2

**Comment by ronocod** [comment]
Fixed in 3.0.19.
