### ISSUE TITLE
NullPointerException File.getAbsolutePath() on Vodafone device

### ISSUE THREAD

**Issue by frogermcs** [intercom/intercom-android#309]
Hey! We found an issue (NPE exception) during Intercom initialisation process. Problem occurs on one device (at least the one we captured in our crash reports).

Here is stacktrace:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at io.intercom.android.sdk.api.ApiFactory.createHttpClient(ApiFactory.java:53)
	at io.intercom.android.sdk.api.ApiFactory.create(ApiFactory.java:36)
	at io.intercom.android.sdk.Injector.getApi(Injector.java:137)
	at io.intercom.android.sdk.IntercomLifecycleTracker.appEnteredForeground(IntercomLifecycleTracker.java:95)
	at io.intercom.android.sdk.IntercomLifecycleTracker.onActivityStarted(IntercomLifecycleTracker.java:112)
	at android.app.Application.dispatchActivityStarted(Application.java:205)
	at android.app.Activity.onStart(Activity.java:1158)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:595)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
	at ***.BaseActivity.onStart(BaseActivity.java:133)
	at ***.BasePresenterActivity.onStart(BasePresenterActivity.java:55)
	at ***.onStart(***Activity.java:23)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6311)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	... 9 more
```

## Version info
  - Intercom for Android version: 3.0.10
  - Android OS version: Android 6.0
  - Android Device: Vodafone Smart ultra 6 (P839V55)

## Expected behavior
App is not crashing.
## Actual behavior
App is crashing during initialisation process.

## Steps to reproduce
 1. Launch app on specific device. 

## Logs

**Comment by DaleCantwell** [comment]
Hi @frogermcs 
Thanks for reporting the issue. I see it happened on 3.0.10. We have since added protection against this. Updating to 3.0.20 will solve this issue. Sorry for any inconvenience caused.
