### ISSUE TITLE
IllegalStateException: Cache is Closed on SDK 3.0.20

### ISSUE THREAD

**Issue by jackcsk** [intercom/intercom-android#310]
## Version info
  - Intercom for Android version: 3.0.20
  - Android OS version: Android 4.4.4
  - Android Device: Samsung Galaxy Core Prime

## Expected behavior
Operation completes successful.
(This is a crash log received via Fabric Crashlytics)

## Actual behavior
Crashed with `java.lang.IllegalStateException: cache is closed`

## Steps to reproduce
 1. (I'm not sure, as this is a crash log received via Fabric Crashlytics)

## Logs
```
Fatal Exception: java.lang.IllegalStateException: cache is closed
       at io.intercom.okhttp3.internal.cache.DiskLruCache.checkNotClosed(DiskLruCache.java:646)
       at io.intercom.okhttp3.internal.cache.DiskLruCache.remove(DiskLruCache.java:608)
       at io.intercom.okhttp3.Cache.remove(Cache.java:258)
       at io.intercom.okhttp3.Cache.put(Cache.java:225)
       at io.intercom.okhttp3.Cache.access$000(Cache.java:136)
       at io.intercom.okhttp3.Cache$1.put(Cache.java:148)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.maybeCache(CacheInterceptor.java:173)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:143)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.ShutdownInterceptor.intercept(ShutdownInterceptor.java:35)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.RetryInterceptor.intercept(RetryInterceptor.java:21)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.UserIdentityInterceptor.intercept(UserIdentityInterceptor.java:29)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
       at io.intercom.okhttp3.RealCall.access$100(RealCall.java:33)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by ronocod** [comment]
How often is this crash happening?

**Comment by jackcsk** [comment]
So far we have 4 crashed instances within 5 days, with the following devices:
  * Sony Xperia Z3 Compact
  * Samsung Galaxy Core Prime
  * TCL 5054N
  * WIKO RIDGE 4G

On the following OS versions:
  * 4.4.4
  * 5.0.2
  * 5.1.1

**Comment by ronocod** [comment]
We're investigating this now, I'll keep you updated on any progress.

**Comment by ronocod** [comment]
Can you update to 3.1.1 and try this? We're now using a newer version of OkHttp which may fix this.

**Comment by jackcsk** [comment]
Ok, I will update and check.

**Comment by ronocod** [comment]
Closing for now, if this happens again we can reopen.

**Comment by razmaimon** [comment]
happened to me on 3.1.3, see new ticket.

**Comment by ronocod** [comment]
Thanks for letting us know, I'll re-open this issue and close the new one.

**Comment by ronocod** [comment]
This should be fixed in 4.x versions of the SDK, the OkHttp code around this has been updated.
