### ISSUE TITLE
Permission crash: java.lang.SecurityException: Permission Denial

### ISSUE THREAD

**Issue by Kaminiak** [intercom/intercom-android#318]
## Version info
  - Intercom for Android version: 3.1.0
  - Android OS version: 4.4
  - Android Device: Emulator (Nexus S)

## Expected behavior
Intercom chat is opened when `Intercom.client().displayMessenger();` is called. 

## Actual behavior
Everything works fine on Android API 24. But I tested the same code on older Android versions (19), and app starting to crash because of Intercom. 

## Steps to reproduce
 1. Run application on Android 4.4
 2. Application shouldn't have been granted `android.permission.READ_EXTERNAL_STORAGE` permission (because docs says that this permission is optional, and I don't want to include it in my application)
 3. Try to open Intercom messenger via `Intercom.client().displayMessenger();`
 4. Crash :cry: 

## Logs
```
03-14 06:48:53.432 1855-1867/android.process.media E/DatabaseUtils: Writing exception to parcel
                                                                    java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=8662, uid=10057 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:467)
                                                                        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:394)
                                                                        at android.content.ContentProvider$Transport.query(ContentProvider.java:194)
                                                                        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
                                                                        at android.os.Binder.execTransact(Binder.java:404)
                                                                        at dalvik.system.NativeStart.run(Native Method)
03-14 06:48:53.432 8662-8662/com.appnroll.nord.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.appnroll.nord.debug, PID: 8662
                                                                       java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=8662, uid=10057 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                           at android.os.Parcel.readException(Parcel.java:1465)
                                                                           at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
                                                                           at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
                                                                           at android.content.ContentProviderProxy.query(ContentProviderNative.java:413)
                                                                           at android.content.ContentResolver.query(ContentResolver.java:461)
                                                                           at android.content.ContentResolver.query(ContentResolver.java:404)
                                                                           at com.intercom.input.gallery.LocalImagesDataSource.getCount(LocalImagesDataSource.java:78)
                                                                           at com.intercom.input.gallery.GalleryInputFragment.onViewCreated(GalleryInputFragment.java:226)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                           at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                           at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1979)
                                                                           at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                                           at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                           at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                           at android.view.View.measure(View.java:16497)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                       	at android.widget.FrameLayou

```

**Comment by DaleCantwell** [comment]
@Kaminiak I'll look into this right away

**Comment by ronocod** [comment]
Can you try this in 3.1.1? It should be fixed in that version

**Comment by Kaminiak** [comment]
Now it looks like everything works fine :tada: Thanks :)
