### ISSUE TITLE
ArrayIndexOutOfBoundsException in Intercom background thread, kills app

### ISSUE THREAD

**Issue by marcomorain** [intercom/intercom-android#319]
## Version info
  - Intercom for Android version: `1121` ? Hard to tell. See below.
  - Android OS version:  `5.1 (22)` kernel `3.4.94`
  - Android Device: Samsung `unia_x86 (GI-I9500_TMMARS)` i686

## Intercom Version

I'm not sure that version of the Intercom JAR I end up with - I'm install Intercom using the recommended syntax:

```Groovy
 dependencies {
        compile('io.intercom.android:intercom-sdk:1.+@aar') {
            transitive = true
        }
    }
```

Looking at my fastlane/gradle logs on CircleCI for this build of the app, I can see the following:
```
[17:55:28]: ▸ :app:prepareIoIntercomAndroidIntercomSdk1121Library UP-TO-DATE
[17:55:28]: ▸ :app:prepareIoIntercomAndroidIntercomSdkBase1121Library UP-TO-DATE
[17:55:28]: ▸ :app:prepareIoIntercomAndroidIntercomSdkGcm1121Library UP-TO-DATE
```

So I would guess `1121`

## Expected behavior
No crash!

## Actual behavior
Crash!

## Steps to reproduce
None - this happens in the wild. I caught it with Sentry.

## Callstack

```
java.lang.ArrayIndexOutOfBoundsException: length=2048; regionStart=0; regionLength=-1
    at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
    at libcore.io.IoBridge.write(IoBridge.java:491)
    at java.io.FileOutputStream.write(FileOutputStream.java:186)
    at java.util.MarsUtils.write(MarsUtils.java:33)
    at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:704)
    at io.intercom.okio.Okio$2.read(Okio.java:139)
    at io.intercom.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at io.intercom.okio.RealBufferedSource.request(RealBufferedSource.java:71)
    at io.intercom.okio.RealBufferedSource.require(RealBufferedSource.java:64)
    at io.intercom.com.squareup.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:113)
    at io.intercom.com.squareup.okhttp.internal.framed.FramedConnection$Reader.execute(FramedConnection.java:606)
    at io.intercom.com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by marcomorain** [comment]
This seems related: https://github.com/square/okio/issues/163

**Comment by ronocod** [comment]
Can you update to version 3 of the SDK? You can drop the `transitive = true` part too so you just need:
```groovy
dependencies {
    compile 'io.intercom.android:intercom-sdk:3.+'
}
```

**Comment by marcomorain** [comment]
I'm not sure when I will get time to upgrade - I understand there are breaking changes? If I get time soon I'll let you know how I get on.

**Comment by skylerwshaw** [comment]
Hi @marcomorain, the API has breaking changes with the 3.x version, but many of the changes are intuitive and visible in the [Intercom.h header file](https://github.com/intercom/intercom-ios/blob/master/Intercom.framework/Headers/Intercom.h). You can find the documentation for installation and integration here:
[Intercom for Mobile - iOS: Installation](https://developers.intercom.com/docs/ios-installation)
[Intercom for Mobile - iOS: Configuration](https://developers.intercom.com/docs/ios-configuration)
[Intercom for Mobile - Push implementation](https://developers.intercom.com/docs/intercom-mobile-push-notifications)

Feel free to message in through the Intercom in-app messenger if you have any questions on making the update.
