### ISSUE TITLE
AsyncTimeout exeption at Intercom.client().displayConversationsList();

### ISSUE THREAD

**Issue by peddiraju211** [intercom/intercom-android#323]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:  compile 'io.intercom.android:intercom-sdk:3.+' , compile 'io.intercom.android:intercom-sdk-fcm:3.+'
  - Android OS version:  v.4.4.4.
  - Android Device: Samsung Galaxy Tab E (SM-T560)

## Expected behavior
Non crash
## Actual behavior
crash
## Steps to reproduce
 unable to reproduce 

## Logs
OkHttp https://nexus-websocket-b.intercom.io/...
       at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:689)
       at io.intercom.okio.Okio$2.read(Okio.java:138)
       at io.intercom.okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
       at io.intercom.okio.RealBufferedSource.request(RealBufferedSource.java:66)
       at io.intercom.okio.RealBufferedSource.require(RealBufferedSource.java:59)
       at io.intercom.okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:115)
       at io.intercom.okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:104)
       at io.intercom.okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
       at io.intercom.okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
       at io.intercom.okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
       at io.intercom.okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by ronocod** [comment]
Can you update to version 3.1.1 of the library? The websocket code has changed a lot in that version. It could take a while to see if that version fixes it so I'll close this off for now, feel free to reopen if this occurs again.
