### ISSUE TITLE
WebView InflateException

### ISSUE THREAD

**Issue by andrei-egeniq** [intercom/intercom-android#332]
## Version info
  - Intercom for Android version: 3.1.2
  - Android OS version: 5.0.1
  - Android Device: HUAWEI  P8 Lite

## Expected behavior
SDK working

## Actual behavior
SDK crashes

## Steps to reproduce
Issue occurs in production, not replicated on development devices.

## Logs
Fatal Exception: android.view.InflateException: Binary XML file line #78: Error inflating class android.webkit.WebView
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:935)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
       at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(Unknown Source)
       at android.support.v4.app.Fragment.performCreateView(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.BackStackRecord.executeOps(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:626)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:935)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
       at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(Unknown Source)
       at android.support.v4.app.Fragment.performCreateView(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.BackStackRecord.executeOps(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by android.content.res.Resources$NotFoundException: String resource ID #0x3040002
       at android.content.res.HwResources.getText(HwResources.java:1252)
       at android.content.res.Resources.getString(Resources.java:374)
       at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:948)
       at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:848)
       at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649)
       at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:788)
       at com.android.org.chromium.android_webview.AwContents.(AwContents.java:635)
       at com.android.org.chromium.android_webview.AwContents.(AwContents.java:573)
       at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:315)
       at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:100)
       at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:267)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:127)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:114)
       at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:111)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:264)
       at android.webkit.WebView.(WebView.java:548)
       at android.webkit.WebView.(WebView.java:483)
       at android.webkit.WebView.(WebView.java:466)
       at android.webkit.WebView.(WebView.java:453)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:626)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at com.android.internal.policy.impl.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:75)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:701)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:828)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:935)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
       at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(Unknown Source)
       at android.support.v4.app.Fragment.performCreateView(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.BackStackRecord.executeOps(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5538)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by ronocod** [comment]
We've released 3.1.3 which should fix this issue.

**Comment by mpuchala** [comment]
Hey @ronocod 

Sorry for off topic but I'm facing same problem, and unfortunately I'm not able to reproduce it. I'll be very grateful if you can share any advice or tip how did you resolve that issue (I wasn't able to find any info about that). As far as I can see it' related usually to Huawei devices.

Thanks in advance

**Comment by ronocod** [comment]
Unfortunately we didn't find out the cause of the issue, the WebView-related code was just disabled.

**Comment by mpuchala** [comment]
Thanks for that information:)

**Comment by b95505017** [comment]
This issue happened on help center using Android 5.x as well.
