### ISSUE TITLE
Crash at ConversationFragment

### ISSUE THREAD

**Issue by peddiraju211** [intercom/intercom-android#333]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 3.1.2
  - Android OS version:  5.1 
  - Android Device: GenyMotion Google Nexus 7 2010 - 5.1.0 

## Expected behavior

Display chat window with conversions list

## Actual behavior

Crash

## Logs
      
04-13 06:56:39.405 26143-26143/com.app.android.homepad.pro E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.app.android.homepad.pro, PID: 26143
                                                                             android.view.InflateException: Binary XML file line #78: Error inflating class <unknown>
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                 at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
                                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                 at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(ConversationFragment.java:223)
                                                                                 at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                 at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
                                                                                 at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
                                                                                 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
                                                                                 at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
                                                                                 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008)
                                                                                 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                 at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55) 
                                                                                 at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                                 at io.intercom.android.sdk.conversation.ConversationFragment.onCreateView(ConversationFragment.java:223) 
                                                                                 at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189) 
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595) 
                                                                                 at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757) 
                                                                                 at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355) 
                                                                                 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146) 
                                                                                 at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098) 
                                                                                 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2008) 
                                                                                 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710) 
                                                                                 at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
                                                                              Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
                                                                                 at android.content.res.Resources.getText(Resources.java:299)
                                                                                 at android.content.res.Resources.getString(Resources.java:385)
                                                                                 at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
                                                                                 at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
                                                                                 at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:631)
                                                                                 at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:780)
                                                                                 at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:619)
                                                                                 at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:556)
                                                                                 at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:311)
                                                                                 at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:96)
                                                                                 at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:263)
                                                                                 at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:123)
                                                                                 at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:110)
                                                                                 at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
                                                                                 at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:107)
                                                                             	at com.android.webview.

**Comment by ronocod** [comment]
This looks similar to https://github.com/intercom/intercom-android/issues/332 which was fixed in version 3.1.3, can you try updating to that version?

**Comment by peddiraju211** [comment]
ok, Thank you @ronocod
