### ISSUE TITLE
OutOfMemoryError -  Failed due to fragmentation 

### ISSUE THREAD

**Issue by peddiraju211** [intercom/intercom-android#334]
```
## Version info
  # Intercom for Android version: 3.1.2
  # Date: 2017-03-31T12:52:06Z
  # OS Version: 6.0.1
  # Device: SM-T550
  # RAM Free: 32.3%
  # Disk Free: 58.7%
```

## Logs
```
#0. Crashed: OkHttp Dispatcher: 0 0 0x0000000000000000
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
       at java.lang.StringBuilder.append(StringBuilder.java:216)
       at libcore.io.IoBridge.connectDetail(IoBridge.java:176)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
       at libcore.io.IoBridge.connect(IoBridge.java:122)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
       at java.net.Socket.connect(Socket.java:884)
       at io.intercom.okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
       at io.intercom.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220)
       at io.intercom.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at io.intercom.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

--

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 202 byte allocation with 3434440 free bytes and 3MB until OOM; failed due to fragmentation (required continguous free 16384 bytes for a new buffer where largest contiguous free 0 bytes)
       at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
       at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:146)
       at java.lang.StringBuilder.append(StringBuilder.java:216)
       at libcore.io.IoBridge.connectDetail(IoBridge.java:176)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
       at libcore.io.IoBridge.connect(IoBridge.java:122)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
       at java.net.Socket.connect(Socket.java:884)
       at io.intercom.okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
       at io.intercom.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220)
       at io.intercom.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at io.intercom.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by skylerwshaw** [comment]
@peddiraju211 Unfortunately we don't have enough information in your report for any action on our side. It's unclear if this is due to the SDK and is more likely a device-specific condition.

Please provide additional information such as:
1. Frequency of occurrence
2. Number of unique users affected
3. Unique devices affected

**Comment by peddiraju211** [comment]
@skylerwshaw  PFA Stacktrace details 
- Number of unique users affected - 1
- Unique devices affected - 1

[com.app.android.homepad.pro_issue_305_crash_58DE2244022900017FACE1A9F7C87A6B_3c6773f5a3ba4dd6bef4634a4c993d09_0_v1.txt](https://github.com/intercom/intercom-android/files/921800/com.app.android.homepad.pro_issue_305_crash_58DE2244022900017FACE1A9F7C87A6B_3c6773f5a3ba4dd6bef4634a4c993d09_0_v1.txt)
