### ISSUE TITLE
Could not dispatch event: class io.intercom.android.sdk.models.events.ConversationEvent...

### ISSUE THREAD

**Issue by alexblack** [intercom/intercom-android#335]
A few of our users are experiencing this crash.  We're using SDK 3.0.14
 
http://crashes.to/s/6cfe43f9f16

```
Fatal Exception: java.lang.RuntimeException: Could not dispatch event: class io.intercom.android.sdk.models.events.ConversationEvent to handler [EventHandler public void io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(io.intercom.android.sdk.models.events.ConversationEvent)]: Attempt to invoke interface method 'android.view.View io.intercom.android.sdk.blocks.blockInterfaces.NotificationChannelsCardBlock.addNotificationChannelsCardBlock(io.intercom.android.sdk.blocks.models.NotificationChannelsCard, boolean, boolean, android.view.ViewGroup)' on a null object reference
       at io.intercom.com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
       at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:387)
       at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
       at io.intercom.com.squareup.otto.Bus.post(Bus.java:337)
       at io.intercom.android.sdk.MainThreadBus.post(MainThreadBus.java:18)
       at io.intercom.android.sdk.api.CallbackHolder$6.onSuccess(CallbackHolder.java:117)
       at io.intercom.android.sdk.api.CallbackHolder$6.onSuccess(CallbackHolder.java:113)
       at io.intercom.android.sdk.api.BaseCallback.onResponse(BaseCallback.java:31)
       at io.intercom.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View io.intercom.android.sdk.blocks.blockInterfaces.NotificationChannelsCardBlock.addNotificationChannelsCardBlock(io.intercom.android.sdk.blocks.models.NotificationChannelsCard, boolean, boolean, android.view.ViewGroup)' on a null object reference
       at io.intercom.android.sdk.blocks.BlockType$6.generateView(BlockType.java:45)
       at io.intercom.android.sdk.blocks.Blocks.createBlocks(Blocks.java:29)
       at io.intercom.android.sdk.conversation.ConversationFragment.createMessageUi(ConversationFragment.java:1228)
       at io.intercom.android.sdk.conversation.ConversationFragment.createConversationUi(ConversationFragment.java:828)
       at io.intercom.android.sdk.conversation.ConversationFragment.setupWithConversation(ConversationFragment.java:819)
       at io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(ConversationFragment.java:737)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at io.intercom.com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
       at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:385)
       at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
       at io.intercom.com.squareup.otto.Bus.post(Bus.java:337)
       at io.intercom.android.sdk.MainThreadBus.post(MainThreadBus.java:18)
       at io.intercom.android.sdk.api.CallbackHolder$6.onSuccess(CallbackHolder.java:117)
       at io.intercom.android.sdk.api.CallbackHolder$6.onSuccess(CallbackHolder.java:113)
       at io.intercom.android.sdk.api.BaseCallback.onResponse(BaseCallback.java:31)
       at io.intercom.retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ronocod** [comment]
This was fixed in 3.0.16, if you update to the latest version it'll fix this.
