### ISSUE TITLE
Crash in io.intercom.android.sdk.nexus.NexusEventType.toStringEncodedJsonObject

### ISSUE THREAD

**Issue by hanspeide** [intercom/intercom-android#345]
## Version info
  - Intercom for Android version: 3.1.1
  - Android OS version: 5.0
  - Android Device: Galaxy XCover 3

## Expected behavior
No crash

## Actual behavior
Crashes

## Steps to reproduce
 1. Unknown. Reported through Crashlytics.

## Logs
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 60 byte allocation with 8 free bytes and 8B until OOM
       at java.util.ArrayList.add(ArrayList.java:118)
       at org.json.JSONStringer.open(JSONStringer.java:179)
       at org.json.JSONStringer.object(JSONStringer.java:158)
       at org.json.JSONObject.writeTo(JSONObject.java:718)
       at org.json.JSONObject.toString(JSONObject.java:689)
       at io.intercom.android.sdk.nexus.NexusEventType.toStringEncodedJsonObject(NexusEventType.java:206)
       at io.intercom.android.sdk.nexus.NexusEvent.toStringEncodedJsonObject(NexusEvent.java:125)
       at io.intercom.android.sdk.nexus.NexusSocket$3.onOpen(NexusSocket.java:156)
       at io.intercom.okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:197)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by DaleCantwell** [comment]
Hi @hanspeide, thanks for getting in touch. Can you see how frequently this crash is happening? 

Looking at the numbers in the logs:
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 60 byte allocation with 8 free bytes and 8B until OOM`
It looks like the app didn't have much memory available to work with at the time. 

Nexus is our real time system and the events it creates should have a tiny memory footprint but with only 8 bytes free nearly any allocation would put the app in risk of an OOM.
Is there any other OutOfMemoryError showing up in Crashlytics? It's possible something else is causing high memory usage here.

**Comment by hanspeide** [comment]
I've currently only seen it once. Our app is relatively memory hungry, but I haven't seen other OOM errors. I'll close the issue and report back if I see more of these pop up.

**Comment by DaleCantwell** [comment]
Thanks @hanspeide, definitely let us know if you see anything else. Hopefully it was just a once off.
