### ISSUE TITLE
[CRASH] java.lang.NoClassDefFoundError: io.intercom.android.sdk.identity.AppIdentity

### ISSUE THREAD

**Issue by eneskaya** [intercom/intercom-android#348]
I'm experiencing a crash with Android 4.4 (API-Level 19) when integrating the Android SDK. For Android Version 5.0 and above everything works as expected - the app does not crash.
What did I do wrong? It worked like 1 week ago. I also tried downgrading Intercom version, didn't do the trick.

## Version info
  - Intercom for Android version: 3.2.2
  - Android OS version: 4.4
  - Android Device: Samsung GT-I19505

## Expected behavior
Not to crash

## Actual behavior
Crash 😄 

## Steps to reproduce
 1. Integrate Intercom SDK as described in README
 2. Start app

## Logs

(switched out bundle identifier with `com.example

```
05-15 12:46:24.631 7116-7116/com.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.example, PID: 7116
                                                               java.lang.NoClassDefFoundError: io.intercom.android.sdk.identity.AppIdentity
                                                                   at io.intercom.android.sdk.Injector.initWithAppCredentials(Injector.java:84)
                                                                   at io.intercom.android.sdk.RealIntercom.create(RealIntercom.java:68)
                                                                   at io.intercom.android.sdk.Intercom.initialize(Intercom.java:72)
                                                                   at com.example.MainApplication.onCreate(MainApplication.java:87)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:144)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5146)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
                                                                   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ronocod** [comment]
Are you using multidex? If so, have you set up the multidex support library up correctly? https://developer.android.com/studio/build/multidex.html#mdex-pre-l

**Comment by eneskaya** [comment]
Thanks for the quick answer. Need to check that thoroughly, will report!

**Comment by eneskaya** [comment]
So, I just thought I enabled multidex, however that was not the case. Thanks a lot!
