### ISSUE TITLE
RuntimeException when initializing library from background thread

### ISSUE THREAD

**Issue by brianmuse** [intercom/intercom-android#35]
If I initialize Intercom from any thread outside the main thread I get the below trace. If this is a limitation of the library, it should probably be noted in the readme somewhere. 

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.<init>(Handler.java:200)
       at android.os.Handler.<init>(Handler.java:114)
       at intercom.intercomsdk.presentation.PresentationManager.<init>(PresentationManager.java:148)
       at intercom.intercomsdk.presentation.PresentationManager.getInstance(PresentationManager.java:129)
```

Otherwise, you could ensure something is run on the main thread with:

```java
    Handler handler = new Handler(Looper.getMainLooper());
    handler.post(new Runnable() {
      public void run() {
        doSomething();
      }
    });
```

**Comment by DaleCantwell** [comment]
Hi Brian,
You are right in that we should document this. We need to run on the main thread as we need to draw UI. Is there a particular use case that would make you prefer to run Intercom on a background thread? We run all of our networking on a background thread anyway so we wouldn't block the main thread.
Thanks for logging this issue
Dale

**Comment by brianmuse** [comment]
Hey Dale, I guess the strange thing is that it needs to be initialized on the main thread. Not sure why it would need UI for that. In general I would think that you'd _only_ want to do UI stuff on the main thread, otherwise intercom functionality may become blocking for the app.

The reason I ran into this because we're wrapping the Intercom client in our own class that can be instantiated and injected and not accessed through static methods exclusively. We're doing a lazy instantiation of this wrapper, so it's not instantiated until it's first requested. We use async tasks for a lot of things... network requests, when I/O needs to happen (eg. sqlite usage), so we often lazily instantiate when we're ready to being the user's intercom session, which may happen in one of these background thread.

Our workaround is basically what I posted above, ensuring that our wrapper always runs intercom methods on the main thread.

Hope this helps.

**Comment by DaleCantwell** [comment]
Hi @brianmuse ,
Thanks for the feedback. That is a fair use case, we were focusing our efforts on getting our current version 0.9.1 out. With that done I will add this issue to our internal issue tracker for version 1.0.0
Thanks again for the detail provided in the issue, I will let you know when have this resolved.

**Comment by DaleCantwell** [comment]
I am going to close out this issue for the time being. Not being able to initialize Intercom from a background thread will remain on our internal feature request backlog but its not something we plan on tackling for the time being. 
Thank you for pointing out the RuntimeException, we will add this as a known limitation to our Github.
