### ISSUE TITLE
ConcurrentModificationException in ScreenshotObserver

### ISSUE THREAD

**Issue by adrien-aubel** [intercom/intercom-android#359]
Hi! I saw that the code seemed to have changed in the latest version (3.2.4), but I wanted to make sure this has been addressed. Also, is it possible to disable this `FileWatcher` / now `ContentObserver` watcher?

## Version info
  - Intercom for Android version: 3.2.3
  - Android OS version: 7.0
  - Android Device: LG G5
  - Rooted: No
  - App in focus: No

## Expected behavior
Intercom shuts down correctly when the application stops

## Actual behavior
Intercom crashes the app with a ConcurrentModificationException

## Steps to reproduce
(see stack trace below, this happened to one of our users after a limited rollout yesterday while the app was )

## Logs
```
java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at android.os.FileObserver.stopWatching(FileObserver.java:219)
       at io.intercom.android.sdk.overlay.ScreenshotObserver.stopWatching(ScreenshotObserver.java:76)
       at io.intercom.android.sdk.middleware.ScreenshotMiddleware.dispatch(ScreenshotMiddleware.java:27)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.FirstMessageMiddleware.dispatch(FirstMessageMiddleware.java:29)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.AudioMiddleware.dispatch(AudioMiddleware.java:32)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.OverlayManagerMiddleware.dispatch(OverlayManagerMiddleware.java:71)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.NexusClientMiddleware.dispatch(NexusClientMiddleware.java:30)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.UserUpdateBatcherMiddleware.dispatch(UserUpdateBatcherMiddleware.java:28)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.ApiMiddleware.dispatch(ApiMiddleware.java:20)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.LoggerMiddleware.dispatch(LoggerMiddleware.java:20)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.store.Store.dispatch(Store.java:81)
       at io.intercom.android.sdk.LifecycleTracker.onActivityStopped(LifecycleTracker.java:98)
       at android.app.Application.dispatchActivityStopped(Application.java:234)
       at android.app.Activity.onStop(Activity.java:1815)
```

**Comment by ronocod** [comment]
Hi, this has been addressed. This code was rewritten in 3.2.4 and is now disabled by default.

**Comment by adrien-aubel** [comment]
Awesome, thank you for the fast reply!
