### ISSUE TITLE
sendTokenToIntercom() crashes without proguard config

### ISSUE THREAD

**Issue by milechainsaw** [intercom/intercom-android#369]
Registring Firebase push notification token with intercom crashes in 'minifyEnabled = true' builds.
Issue is resolved by adding this line to proguard conf:
-keep class io.intercom.android.** { *; }

You should add this to readme.

## Version info
  - Intercom for Android version: 3.2.6
  - Android OS version: 6,7,8.
  - Android Device: Nexus 5x, Samsung S6, S7, Emulator

## Expected behavior
Intercom library sends Firebase token without additional proguard config.

## Actual behavior
Crashes when sending Firebase token.

## Steps to reproduce
 1. Build app with minifyEnabled = true, debuggable = false
 2. Try to register Firebase token

## Logs
E/AndroidRuntime: FATAL EXCEPTION: main
Process: ch.myapplication.android, PID: 7903
java.lang.RuntimeException: Unable to start activity ComponentInfo{...}
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
    at io.intercom.android.sdk.user.DeviceData.hasCachedDeviceToken(DeviceData.java:38)
    at io.intercom.android.sdk.push.PushHandler.shouldSendDeviceToken(PushHandler.java:20)
    at io.intercom.android.sdk.push.IntercomPushClient.sendTokenToIntercom(IntercomPushClient.java:69)
    at ch.myapplication.android.util.g.a(IntercomUtils.java:32)
    at ch.myapplication.android.activity.myapplication.onCreate(myapplication.java:37)
    at android.app.Activity.performCreate(Activity.java:6682)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6121) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ronocod** [comment]
We already use that Proguard rule. The issue here seems to be that you called `sendTokenToIntercom()` with a null token. Can you check the value before you pass it in?

We'll also add stricter null checking for this method.

**Comment by milechainsaw** [comment]
Ok thanks. I think you close this issue as WAI
