### ISSUE TITLE
IllegalStateException when starting ChatHeadService (causes crash)

### ISSUE THREAD

**Issue by brianmuse** [intercom/intercom-android#37]
I don't have much extra info here, but ran into this crash today:

```
    java.lang.RuntimeException: Unable to start service intercom.intercomsdk.presentation.ChatHeadService@9676d97 with Intent { cmp=com.mypackage/intercom.intercomsdk.presentation.ChatHeadService (has extras) }: java.lang.IllegalStateException: PresentationManager
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2881)
            at android.app.ActivityThread.access$2100(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalStateException: PresentationManager
            at intercom.intercomsdk.presentation.PresentationManager.getInstance(PresentationManager.java:139)
            at intercom.intercomsdk.ViewManagers.ChatheadManager.<init>(ChatheadManager.java:99)
            at intercom.intercomsdk.presentation.ChatHeadService.onStartCommand(ChatHeadService.java:54)
            at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2864)
            at android.app.ActivityThread.access$2100(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by DaleCantwell** [comment]
@brianmuse thank you for reporting the issue and getting us the crash log. We have totally revamped the classes responsible for that crash with a big push on improving stability. I will let you know as soon as we are releasing the update.
