### ISSUE TITLE
  java.lang.NoSuchMethodError: com.google.firebase.iid.zzg.zzabU

### ISSUE THREAD

**Issue by jcaiqueoliveira** [intercom/intercom-android#375]
I get this error using the intercom in my app. I'm using firebase with intercom to push notification

## Version info
  - Intercom for Android version: base-sdk 3+ , sdk-fcm 3+ 
  - Android OS version: 4.4.2
  - Android Device: Emulator

## Steps to reproduce
 1. Start a conversation with push notification configured in app
 2. Close the intercom activity and wait in mainactivity
 3.  Respond for chat in website
 4 . After seconds this error appear

## Logs
```
FATAL EXCEPTION: main
                                                                Process: br.com.buy4.flip, PID: 6248
                                                                java.lang.NoSuchMethodError: com.google.firebase.iid.zzg.zzabU
                                                                    at com.google.firebase.messaging.FirebaseMessagingService.zzD(Unknown Source)
                                                                    at com.google.firebase.iid.zzb.onStartCommand(Unknown Source)
                                                                    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2702)
                                                                    at android.app.ActivityThread.access$2100(ActivityThread.java:135)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by skylerwshaw** [comment]
@jcaiqueoliveira Are you using and calling Firebase elsewhere in your application? Do you know what `iid.zzg.zzabU` is referring to? This `NoSuchMethodError` doesn't appear to be a result of an Intercom call from what I can see.

**Comment by DaleCantwell** [comment]
@jcaiqueoliveira typically this error is a result of conflicting versions of firebase. 

If the answer to Skyler's question of if you are using Firebase elsewhere in your application is yes, could you let us know what versions you are using for:
`com.google.gms:google-services`
`com.google.firebase:firebase-messaging`

**Comment by jcaiqueoliveira** [comment]
@DaleCantwell you right!
I can update all dependencies of firebase to version 11?
