### ISSUE TITLE
SecurityException: Not allowed to start service intent

### ISSUE THREAD

**Issue by MiralDesai** [intercom/intercom-android#383]
## Version info
  - Intercom for Android version: 3.1.5
  - Android OS version: 7.0
  - Android Device: Galaxy S7 Edge

## Expected behavior

For the app to not crash.

## Actual behavior

Fatal Exception: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java)
       at android.app.ContextImpl.startService(ContextImpl.java)
       at android.content.ContextWrapper.startService(ContextWrapper.java)
       at com.google.android.gms.iid.zze.zzb(Unknown Source)
       at com.google.android.gms.iid.zze.zza(Unknown Source)
       at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
       at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
       at io.intercom.android.sdk.gcm.IntercomGcmRegistrationService.onHandleIntent(SourceFile:34)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.os.HandlerThread.run(HandlerThread.java)

## Steps to reproduce
 This is a crash report I received in production, first time I've ever seen it, no steps to reproduce because I didn't invoke the crash. It's only happened once, but worth mentioning it here.

**Comment by DaleCantwell** [comment]
Thanks for reporting the issue. It looks very similar to https://github.com/intercom/intercom-android/issues/373 which was O specific.
I'll have a look into them and update the issues.

**Comment by DaleCantwell** [comment]
I've investigated this and can't see anything that would cause this. Has this just happened the one time?

**Comment by MiralDesai** [comment]
It's happened twice now, from the same user.

I have since updated intercom to 3.2.6, so it could be something from that version of intercom. Will continue to monitor.

**Comment by DaleCantwell** [comment]
Awesome thanks, let us know if you still see it once that user is on the new version.

**Comment by ronocod** [comment]
@MiralDesai Is this bug still happening since you updated to the newer version?

**Comment by MiralDesai** [comment]
No, have not seen it happen again.
