### ISSUE TITLE
Intercom transitive library is crashing with 26.0.0

### ISSUE THREAD

**Issue by virengujariya** [intercom/intercom-android#392]
Intercom for Android transitive library (3+) is crashing with Android Support Libraries 26.0.0

`Fatal Exception: java.lang.NoSuchMethodError: No virtual method onNestedFling(Landroid/support/design/widget/CoordinatorLayout;Landroid/support/design/widget/AppBarLayout;Landroid/view/View;FFZ)Z in class Landroid/support/design/widget/AppBarLayout$Behavior; or its super classes (declaration of 'android.support.design.widget.AppBarLayout$Behavior' appears in /data/app/me.latergram.latergramme-2/base.apk)
       at io.intercom.android.sdk.profile.ProfilePresenter.flingProfile(ProfilePresenter.java:201)
       at io.intercom.android.sdk.profile.ProfilePresenter.flingProfileOpen(ProfilePresenter.java:185)
       at io.intercom.android.sdk.profile.ProfilePresenter.profileAutoOpened(ProfilePresenter.java:176)
       at io.intercom.android.sdk.conversation.ConversationFragment$8.run(ConversationFragment.java:673)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

Any updates on when it will start supporting 26.0.0 ?

**Comment by DaleCantwell** [comment]
Hi @virengujariya 
We expect to have a release shortly. I'll close the issue when that version is shipped.
Thanks,
Dale

**Comment by Bringoff** [comment]
@DaleCantwell when will it be released? Because we have already made support for android 8.0 notification channels in our app, but it require 26.0 supports version, so we can't release this update because of intercom crashes. And it's difficult to downgrade because of changes in notifications logic.

**Comment by ktchernov** [comment]
Any update?

Best practice is to try the Alphas & Betas Google releases ahead of time rather than wait until after the final release and breaking on default developer settings. Google gives SDK developers plenty of notice.

**Comment by ppamorim** [comment]
Any update? My app is crashing due this problem.

**Comment by DaleCantwell** [comment]
We have just released [4.0.0](https://github.com/intercom/intercom-android/releases/tag/4.0.0) which supports 26.0.0
