### ISSUE TITLE
0. Crash: java.lang.RuntimeException: Adding window failed

### ISSUE THREAD

**Issue by noinlijin** [intercom/intercom-android#394]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:3.2.8
  - Android OS version:4.2.2
  - Android Device:OPPO R827T

## Expected behavior
I want talk nothing, just look logs, every time I test my app in 30 devices, there were this crash
## Steps to reproduce
 1. 
 2. 
 3. 

## Logs
```
08-04 15:31:24.269   872 19082 I am_crash: [10547,com.security.xvpn.z35kb1,572998,android.os.TransactionTooLargeException,Adding window failed,Binder.java,-2]
=========================================================================================================
08-04 15:33:09.369   872 12219 I am_crash: [14292,com.security.xvpn.z35kb1,572998,android.os.TransactionTooLargeException,Adding window failed,Binder.java,-2]
=========================================================================================================
08-04 15:31:24.149 10547 10547 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x414f3438)
08-04 15:31:24.149 10547 10547 W System.err: java.lang.RuntimeException: Adding window failed
08-04 15:31:24.149 10547 10547 W System.err: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:574)
08-04 15:31:24.159 10547 10547 W System.err: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:326)
08-04 15:31:24.159 10547 10547 W System.err: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:224)
08-04 15:31:24.159 10547 10547 W System.err: 	at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:149)
08-04 15:31:24.169 10547 10547 W System.err: 	at android.view.Window$LocalWindowManager.addView(Window.java:547)
08-04 15:31:24.169 10547 10547 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2646)
08-04 15:31:24.169 10547 10547 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
08-04 15:31:24.169 10547 10547 W System.err: 	at android.app.ActivityThread.access$600(ActivityThread.java:133)
08-04 15:31:24.169 10547 10547 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
08-04 15:31:24.179 10547 10547 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 15:31:24.189 10547 10547 W System.err: 	at android.os.Looper.loop(Looper.java:137)
08-04 15:31:24.189 10547 10547 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:4794)
08-04 15:31:24.199 10547 10547 W System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)
08-04 15:31:24.199 10547 10547 W System.err: 	at java.lang.reflect.Method.invoke(Method.java:511)
08-04 15:31:24.199 10547 10547 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-04 15:31:24.199 10547 10547 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
08-04 15:31:24.199 10547 10547 W System.err: 	at dalvik.system.NativeStart.main(Native Method)
08-04 15:31:24.199 10547 10547 W System.err: Caused by: android.os.TransactionTooLargeException
08-04 15:31:24.209 10547 10547 W System.err: 	at android.os.BinderProxy.transact(Native Method)
08-04 15:31:24.209 10547 10547 W System.err: 	at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:534)
08-04 15:31:24.209 10547 10547 W System.err: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:563)
08-04 15:31:24.209 10547 10547 W System.err: 	... 16 more
08-04 15:31:24.209 10547 10547 W FlurryAgent: Error logged: uncaught
08-04 15:31:24.239 10547 10547 E AndroidRuntime: FATAL EXCEPTION: main
08-04 15:31:24.239 10547 10547 E AndroidRuntime: java.lang.RuntimeException: Adding window failed
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:574)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:326)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:224)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:149)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.view.Window$LocalWindowManager.addView(Window.java:547)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2646)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.app.ActivityThread.access$600(ActivityThread.java:133)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:137)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:4794)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:511)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.os.BinderProxy.transact(Native Method)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:534)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:563)
08-04 15:31:24.239 10547 10547 E AndroidRuntime: 	... 16 more
=================================================================================================
08-04 15:33:09.219 14292 14292 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x414f3438)
08-04 15:33:09.219 14292 14292 W System.err: java.lang.RuntimeException: Adding window failed
08-04 15:33:09.239 14292 14292 W System.err: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:574)
08-04 15:33:09.239 14292 14292 W System.err: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:326)
08-04 15:33:09.249 14292 14292 W System.err: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:224)
08-04 15:33:09.249 14292 14292 W System.err: 	at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:149)
08-04 15:33:09.249 14292 14292 W System.err: 	at android.view.Window$LocalWindowManager.addView(Window.java:547)
08-04 15:33:09.259 14292 14292 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2646)
08-04 15:33:09.259 14292 14292 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
08-04 15:33:09.259 14292 14292 W System.err: 	at android.app.ActivityThread.access$600(ActivityThread.java:133)
08-04 15:33:09.269 14292 14292 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
08-04 15:33:09.269 14292 14292 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 15:33:09.269 14292 14292 W System.err: 	at android.os.Looper.loop(Looper.java:137)
08-04 15:33:09.269 14292 14292 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:4794)
08-04 15:33:09.269 14292 14292 W System.err: 	at java.lang.reflect.Method.invokeNative(Native Method)
08-04 15:33:09.279 14292 14292 W System.err: 	at java.lang.reflect.Method.invoke(Method.java:511)
08-04 15:33:09.279 14292 14292 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-04 15:33:09.279 14292 14292 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
08-04 15:33:09.279 14292 14292 W System.err: 	at dalvik.system.NativeStart.main(Native Method)
08-04 15:33:09.279 14292 14292 W System.err: Caused by: android.os.TransactionTooLargeException
08-04 15:33:09.289 14292 14292 W System.err: 	at android.os.BinderProxy.transact(Native Method)
08-04 15:33:09.289 14292 14292 W System.err: 	at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:534)
08-04 15:33:09.289 14292 14292 W System.err: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:563)
08-04 15:33:09.289 14292 14292 W System.err: 	... 16 more
08-04 15:33:09.299 14292 14292 W FlurryAgent: Error logged: uncaught
08-04 15:33:09.319 14292 14292 E AndroidRuntime: FATAL EXCEPTION: main
08-04 15:33:09.319 14292 14292 E AndroidRuntime: java.lang.RuntimeException: Adding window failed
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:574)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:326)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:224)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:149)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.view.Window$LocalWindowManager.addView(Window.java:547)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2646)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.app.ActivityThread.access$600(ActivityThread.java:133)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:137)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:4794)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:511)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.os.BinderProxy.transact(Native Method)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.view.IWindowSession$Stub$Proxy.add(IWindowSession.java:534)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:563)
08-04 15:33:09.319 14292 14292 E AndroidRuntime: 	... 16 more
=================================================================================================


```

**Comment by DaleCantwell** [comment]
Hi @noinlijin 
I can't see any mention of Intercom in that crash log. Is there anything else in the crash logs that points to Interco being the cause of the TransactionTooLargeException?
Thanks,
Dale

**Comment by noinlijin** [comment]
@DaleCantwell I guess it is by intercom, I find this crash in stackoverflow with someone talk,our app never transaction file or bitmap from service, I want to close GIF action in intercom,How can I do it .

https://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception

**Comment by DaleCantwell** [comment]
Can you reproduce this yourself? The initial report said 
"every time I test my app in 30 devices, there were this crash"
What was the test? Did that test open Intercom and try to use the GIF input?

**Comment by noinlijin** [comment]
Hi @DaleCantwell there have a crash capture   
![image](https://user-images.githubusercontent.com/3073370/28996067-ee6ac508-7a2a-11e7-9f2a-0f2a01227e2f.png)

**Comment by noinlijin** [comment]
this device info ：三星 SM-J5108 6.0.1 720x1280 armeabi-v7a
I also find more info to solve this issue    

```   
详细说明
问题分析：

RuntimeException是运行时异常，是java编译器事先不可预见的异常。RuntimeException的子类众多，这里列举一些比较常见的子类：

BufferOverflowException当相关 put 操作达到目标缓冲区限制时，抛出此未经检查的异常。

ArrayStoreException试图将错误类型的对象存储到一个对象数组时抛出的异常。

ArithmeticException当出现异常的运算条件时，抛出此异常。例如，一个整数“除以零”时，抛出此类的一个实例。

BufferUnderflowException当相关 get 操作达到源缓冲区限制时，抛出此未经检查的异常。

IndexOutOfBoundsException 指示某排序索引（例如对数组、字符串或向量的排序）引用时超出范围时抛出。

NoSuchElementException 由 Enumeration 的 nextElement 方法抛出，表明枚举中没有更多的元素。

解决方案：

KeySolution：RuntimeException是发生在程序运行期，预先不可预见的发生。编译器未要求一定要进行捕获，如果运行期没有处理，则RuntimeException会一直往上层抛。最后由JVM来处理，JVM会打印堆栈信息然后结束应用。对于可能发生的RuntimeException，建议根据堆栈信息，检查代码是否有误并进行更改，如果情况复杂无法全部解决，可以对RuntimeException进行捕获并进行业务恢复处理。 代码示例：

try {
   somethingThrowingARuntimeException();
   }catch (RuntimeException e) {
     // Do something with it. At least log it
     e.printStackTrace();
   }
示例一：

java.lang.RuntimeException: Unable to start activity ComponentInfo {com.demo.demo/com.demo.demo.api.MainActivity}: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = com.alibaba.mqc.intentfuzzer.util.SerializableTest)

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.mqc.intentfuzzer.util.SerializableTest" on path: DexPathList[[zip file "/data/app/com.demo.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.demo-1/lib/arm, /data/app/com.demo.demo-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

这个异常是因为Activity\Service\Broadcast没有验证Intent传入的参数类型导致应用崩溃，建议getSerializableExtra获取序列化对象时验证参数类型。

代码示例：

public void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  Intent intent = getIntent();
  Object object = intent.getSerializableExtra("data");
  if (object.getClass() == "xxxx") {
  	// do something
  }
}
示例二：

java.lang.RuntimeException: Unable to start activity ComponentInfo{*}: android.support.v4.app.Fragment$InstantiationException: *: make sure class name exists, is public, and has an empty constructor that is public

当系统因为内存不足杀死非前台进程，用户又将被系统杀掉的非前台应用带回前台，如果这个时候有UI是呈现在Fragment中，那么会因为restore造成fragment需要通过反射实例对象，从而将之前save的状态还原。因此不应该改写构造函数，而应该使用静态方法比如newInstance来构造有参Fragment对象并返回。

代码示例：

步骤一：编写有参静态创建对象函数

public static final AlertFragment newInstance(int title, String message)
{
    AlertFragment f = new AlertFragment();
    Bundle bdl = new Bundle(2);
    bdl.putInt(EXTRA_TITLE, title);
    bdl.putString(EXTRA_MESSAGE, message);
    f.setArguments(bdl);
    return f;
}
步骤二：通过Bundle获取参数

@Override
public void onCreate(Bundle savedInstanceState)
{
    title = getArguments().getInt(EXTRA_TITLE);
    message = getArguments().getString(EXTRA_MESSAGE);
    //...
    //etc
    //...
}
步骤三：通过FragmentManager对Fragment进行管理。

public onCreate(Bundle savedInstanceState) {
    if(savedInstanceState == null){
        getSupportFragmentManager()
            .beginTransaction()
            .replace(R.id.content,AlertFragment.newInstance(
                R.string.alert_title,
                "Oh noes an error occured!")
            )
            .commit();
    }
}
示例三：

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 80, Size: 3 at java.util.ArrayList.rangeCheck(ArrayList.java:635) at java.util.ArrayList.remove(ArrayList.java:474) at com.alibaba.mqc.test.Test.indexOutOfBounds(Test.java:66) at com.alibaba.mqc.test.Test.main(Test.java:32)

问题分析： IndexOutOfBoundsException 指示某排序索引（例如对数组、字符串或向量的排序）引用时超出范围时抛出。请检查是否有对List有越界索引，判断访问数组的索引是否合法。 有误的代码：

public void indexOutOfBounds(){
	ArrayList<Character> a = new ArrayList<Character>();
	 a.add('A');
	 a.add('B');
	 a.add('C');
	 System.out.println(a);
	 //a.remove('A');
	 a.remove(80);	// 抛出此类异常
	 System.out.println(a);
}
建议的代码：

public void indexOutOfBounds(){
	ArrayList<Character> a = new ArrayList<Character>();
	 a.add('A');
	 a.add('B');
	 a.add('C');
	 System.out.println(a);
	 if(a.size()>80){
		 a.remove(80);
	 }
	 System.out.println(a);
}
```

more info about this issue   
https://developer.android.com/reference/java/lang/RuntimeException.html   
http://stackoverflow.com/questions/10450348/do-fragments-really-need-an-empty-constructor    
http://blog.csdn.net/xplee0576/article/details/43057633   
http://stackoverflow.com/questions/2028719/handling-runtimeexceptions-in-java   
http://tool.oschina.net/uploads/apidocs/jdk-zh/java/lang/RuntimeException.html

**Comment by ronocod** [comment]
Closing this, we don't send large items like Bitmaps inside Intents so I don't think this is caused by our SDK.
