### ISSUE TITLE
Can not build with Java 8

### ISSUE THREAD

**Issue by rockerhieu** [intercom/intercom-android#402]
I have to update to 4.* in order to work with support `26.0.0`, but couldn't success at compiling the app.

## Version info
  - Intercom for Android version: 4.0.1 or 4.0.0
  - Same error happen with or without d8

## Logs
```
Exception in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:583)
```

**Comment by DaleCantwell** [comment]
Hi @rockerhieu what version of the gradle plugin are you using?

**Comment by rockerhieu** [comment]
I'm using `3.0.0-beta2`

**Comment by ronocod** [comment]
Can you run `./gradlew dependencies` from your project folder and paste the output here please?

**Comment by rockerhieu** [comment]
Here they are:

```
+--- com.google.firebase:firebase-core:11.0.1
|    \--- com.google.firebase:firebase-analytics:[11.0.1] -> 11.0.1
|         +--- com.google.firebase:firebase-analytics-impl:[11.0.1] -> 11.0.1
|         |    +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4
|         |    |    \--- com.android.support:support-v4:25.2.0 -> 26.0.1
|         |    |         +--- com.android.support:support-compat:26.0.1
|         |    |         |    \--- com.android.support:support-annotations:26.0.1
|         |    |         +--- com.android.support:support-media-compat:26.0.1
|         |    |         |    +--- com.android.support:support-annotations:26.0.1
|         |    |         |    \--- com.android.support:support-compat:26.0.1 (*)
|         |    |         +--- com.android.support:support-core-utils:26.0.1
|         |    |         |    +--- com.android.support:support-annotations:26.0.1
|         |    |         |    \--- com.android.support:support-compat:26.0.1 (*)
|         |    |         +--- com.android.support:support-core-ui:26.0.1
|         |    |         |    +--- com.android.support:support-annotations:26.0.1
|         |    |         |    \--- com.android.support:support-compat:26.0.1 (*)
|         |    |         \--- com.android.support:support-fragment:26.0.1
|         |    |              +--- com.android.support:support-compat:26.0.1 (*)
|         |    |              +--- com.android.support:support-core-ui:26.0.1 (*)
|         |    |              \--- com.android.support:support-core-utils:26.0.1 (*)
|         |    +--- com.google.firebase:firebase-iid:[11.0.1] -> 11.0.4
|         |    |    +--- com.google.android.gms:play-services-basement:[11.0.4] -> 11.0.4 (*)
|         |    |    \--- com.google.firebase:firebase-common:[11.0.4] -> 11.0.4
|         |    |         +--- com.google.android.gms:play-services-basement:[11.0.4] -> 11.0.4 (*)
|         |    |         \--- com.google.android.gms:play-services-tasks:[11.0.4] -> 11.0.4
|         |    |              \--- com.google.android.gms:play-services-basement:[11.0.4] -> 11.0.4 (*)
|         |    +--- com.google.firebase:firebase-common:[11.0.1] -> 11.0.4 (*)
|         |    \--- com.google.android.gms:play-services-tasks:[11.0.1] -> 11.0.4 (*)
|         +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
|         \--- com.google.firebase:firebase-common:[11.0.1] -> 11.0.4 (*)
+--- com.android.databinding:library:1.3.1
|    +--- com.android.support:support-v4:21.0.3 -> 26.0.1 (*)
|    \--- com.android.databinding:baseLibrary:2.3.0-dev -> 3.0.0-beta2
+--- com.android.databinding:baseLibrary:3.0.0-beta2
+--- com.android.databinding:adapters:1.3.1
|    +--- com.android.databinding:library:1.3 -> 1.3.1 (*)
|    \--- com.android.databinding:baseLibrary:2.3.0-dev -> 3.0.0-beta2
+--- project :domain
|    +--- com.google.dagger:dagger:2.11
|    |    \--- javax.inject:javax.inject:1
|    +--- io.reactivex:rxjava:1.3.0
|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.0
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.9.0
|    +--- org.parceler:parceler-api:1.1.8
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.3-2
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.1.3-2
|         |    \--- org.jetbrains:annotations:13.0
|         \--- org.jetbrains.kotlin:kotlin-stdlib-jre7:1.1.3-2
|              \--- org.jetbrains.kotlin:kotlin-stdlib:1.1.3-2 (*)
+--- project :data
|    +--- com.squareup.okhttp3:okhttp:3.5.0 -> 3.8.1
|    |    \--- com.squareup.okio:okio:1.13.0
|    +--- com.squareup.okhttp3:logging-interceptor:3.5.0
|    |    \--- com.squareup.okhttp3:okhttp:3.5.0 -> 3.8.1 (*)
|    +--- org.greenrobot:greendao:3.2.2
|    |    \--- org.greenrobot:greendao-api:3.2.2
|    +--- com.squareup.retrofit2:retrofit:2.1.0 -> 2.3.0
|    |    \--- com.squareup.okhttp3:okhttp:3.8.0 -> 3.8.1 (*)
|    +--- com.squareup.retrofit2:converter-jackson:2.1.0
|    |    +--- com.squareup.retrofit2:retrofit:2.1.0 -> 2.3.0 (*)
|    |    \--- com.fasterxml.jackson.core:jackson-databind:2.7.2 -> 2.9.0 (*)
|    +--- com.squareup.retrofit2:adapter-rxjava:2.1.0
|    |    +--- com.squareup.retrofit2:retrofit:2.1.0 -> 2.3.0 (*)
|    |    \--- io.reactivex:rxjava:1.1.5 -> 1.3.0
|    +--- com.fasterxml.jackson.core:jackson-databind:2.9.0 (*)
|    +--- com.fasterxml.jackson.module:jackson-module-kotlin:2.9.0
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.9.0 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.9.0
|    |    \--- org.jetbrains.kotlin:kotlin-reflect:1.1.3
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.1.3 -> 1.1.3-2 (*)
|    +--- com.jakewharton.rxbinding:rxbinding:0.4.0
|    |    +--- io.reactivex:rxandroid:1.1.0 -> 1.2.1
|    |    |    \--- io.reactivex:rxjava:1.1.6 -> 1.3.0
|    |    +--- io.reactivex:rxjava:1.1.0 -> 1.3.0
|    |    \--- com.android.support:support-annotations:23.1.0 -> 26.0.1
|    +--- com.googlecode.libphonenumber:libphonenumber:8.7.0
|    +--- com.parse:parse-android:1.15.8
|    |    +--- com.android.support:support-annotations:25.3.1 -> 26.0.1
|    |    +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    \--- com.squareup.okhttp3:okhttp:3.8.0 -> 3.8.1 (*)
|    +--- com.parse:parseinterceptors:0.0.2
|    |    \--- com.parse:parse-android:1.12.0 -> 1.15.8 (*)
|    +--- com.parse.bolts:bolts-android:1.3.0 -> 1.4.0
|    |    +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    \--- com.parse.bolts:bolts-applinks:1.4.0
|    |         \--- com.parse.bolts:bolts-tasks:1.4.0
|    +--- com.jonathanfinerty.once:once:0.4.2
|    |    \--- com.android.support:support-annotations:23.1.1 -> 26.0.1
|    +--- de.greenrobot:eventbus:2.4.0
|    +--- com.layer.atlas:layer-atlas:0.4.13
|    |    +--- com.layer.sdk:layer-sdk:0.23.19
|    |    |    +--- org.slf4j:slf4j-nop:1.7.12
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.12
|    |    |    +--- com.google.code.gson:gson:2.8.0
|    |    |    \--- com.firebase:firebase-jobdispatcher:0.6.0 -> 0.7.0
|    |    |         \--- com.android.support:support-v4:25.0.0 -> 26.0.1 (*)
|    |    +--- org.slf4j:slf4j-nop:1.7.2 -> 1.7.12 (*)
|    |    +--- com.squareup.picasso:picasso:2.5.2
|    |    +--- com.davemorrissey.labs:subsampling-scale-image-view:3.4.1
|    |    |    \--- com.android.support:support-annotations:20.0.0 -> 26.0.1
|    |    +--- com.android.support:recyclerview-v7:24.2.1 -> 26.0.1
|    |    |    +--- com.android.support:support-annotations:26.0.1
|    |    |    +--- com.android.support:support-compat:26.0.1 (*)
|    |    |    \--- com.android.support:support-core-ui:26.0.1 (*)
|    |    +--- com.android.support:appcompat-v7:24.2.1 -> 26.0.1
|    |    |    +--- com.android.support:support-annotations:26.0.1
|    |    |    +--- com.android.support:support-v4:26.0.1 (*)
|    |    |    +--- com.android.support:support-vector-drawable:26.0.1
|    |    |    |    +--- com.android.support:support-annotations:26.0.1
|    |    |    |    \--- com.android.support:support-compat:26.0.1 (*)
|    |    |    \--- com.android.support:animated-vector-drawable:26.0.1
|    |    |         +--- com.android.support:support-vector-drawable:26.0.1 (*)
|    |    |         \--- com.android.support:support-core-ui:26.0.1 (*)
|    |    \--- com.android.support:design:24.2.1 -> 26.0.1
|    |         +--- com.android.support:support-v4:26.0.1 (*)
|    |         +--- com.android.support:appcompat-v7:26.0.1 (*)
|    |         +--- com.android.support:recyclerview-v7:26.0.1 (*)
|    |         \--- com.android.support:transition:26.0.1
|    |              +--- com.android.support:support-annotations:26.0.1
|    |              \--- com.android.support:support-v4:26.0.1 (*)
|    +--- com.google.guava:guava:20.0
|    +--- project :domain (*)
|    +--- com.google.dagger:dagger:2.11 (*)
|    +--- io.reactivex:rxjava:1.3.0
|    +--- com.android.support:support-annotations:26.0.1
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.3-2 (*)
+--- com.android.support:multidex:1.0.1 -> 1.0.2
+--- com.google.dagger:dagger:2.11 (*)
+--- com.jakewharton:butterknife:8.6.0
|    +--- com.jakewharton:butterknife-annotations:8.6.0
|    |    \--- com.android.support:support-annotations:25.1.0 -> 26.0.1
|    +--- com.android.support:support-annotations:25.1.0 -> 26.0.1
|    \--- com.android.support:support-compat:25.1.0 -> 26.0.1 (*)
+--- io.reactivex:rxjava:1.3.0
+--- io.reactivex:rxandroid:1.2.1 (*)
+--- com.trello:rxlifecycle:0.3.0
|    +--- com.jakewharton.rxbinding:rxbinding:0.2.0 -> 0.4.0 (*)
|    \--- io.reactivex:rxjava:1.0.14 -> 1.3.0
+--- com.trello:rxlifecycle-components:0.3.0
|    +--- com.android.support:appcompat-v7:23.0.0 -> 26.0.1 (*)
|    +--- com.trello:rxlifecycle:0.3.0 (*)
|    \--- io.reactivex:rxjava:1.0.14 -> 1.3.0
+--- com.android.support:recyclerview-v7:26.0.1 (*)
+--- com.android.support:appcompat-v7:26.0.1 (*)
+--- com.android.support:cardview-v7:26.0.1
|    \--- com.android.support:support-annotations:26.0.1
+--- com.android.support.constraint:constraint-layout:1.1.0-beta1
|    \--- com.android.support.constraint:constraint-layout-solver:1.1.0-beta1
+--- com.android.support:design:26.0.1 (*)
+--- com.android.support:support-annotations:26.0.1
+--- com.android.support:customtabs:26.0.1
|    +--- com.android.support:support-compat:26.0.1 (*)
|    \--- com.android.support:support-annotations:26.0.1
+--- com.squareup.phrase:phrase:1.1.0
|    \--- com.android.support:support-annotations:21.0.3 -> 26.0.1
+--- com.facebook.fresco:fresco:1.3.0
|    +--- com.facebook.fresco:drawee:1.3.0
|    |    \--- com.facebook.fresco:fbcore:1.3.0
|    +--- com.facebook.fresco:fbcore:1.3.0
|    \--- com.facebook.fresco:imagepipeline:1.3.0
|         +--- com.parse.bolts:bolts-tasks:1.4.0
|         +--- com.facebook.fresco:fbcore:1.3.0
|         \--- com.facebook.fresco:imagepipeline-base:1.3.0
|              +--- com.parse.bolts:bolts-tasks:1.4.0
|              \--- com.facebook.fresco:fbcore:1.3.0
+--- com.facebook.fresco:imagepipeline-okhttp:1.3.0
|    +--- com.squareup.okhttp:okhttp:2.7.4
|    |    \--- com.squareup.okio:okio:1.6.0 -> 1.13.0
|    +--- com.facebook.fresco:fbcore:1.3.0
|    \--- com.facebook.fresco:imagepipeline:1.3.0 (*)
+--- com.theartofdev.edmodo:android-image-cropper:2.4.6
|    +--- com.android.support:appcompat-v7:25.3.1 -> 26.0.1 (*)
|    \--- com.android.support:exifinterface:25.3.1 -> 26.0.1
|         \--- com.android.support:support-annotations:26.0.1
+--- org.parceler:parceler-api:1.1.8
+--- com.f2prateek.dart:dart:2.0.2
|    \--- com.f2prateek.dart:dart-annotations:2.0.2
+--- com.hannesdorfmann.fragmentargs:annotation:3.0.2
+--- com.hannesdorfmann.fragmentargs:bundler-parceler:3.0.2
+--- com.hokolinks:hoko:2.3.3
|    \--- com.android.support:support-v4:23.0.1 -> 26.0.1 (*)
+--- org.ocpsoft.prettytime:prettytime:4.0.1.Final
+--- me.leolin:ShortcutBadger:1.1.17
+--- me.tatarka.bindingcollectionadapter2:bindingcollectionadapter:2.1.0
|    +--- com.android.support:support-v4:21.0.3 -> 26.0.1 (*)
|    +--- com.android.databinding:library:1.3.1 (*)
|    +--- com.android.databinding:baseLibrary:2.3.0 -> 3.0.0-beta2
|    \--- com.android.databinding:adapters:1.3.1 (*)
+--- me.tatarka.bindingcollectionadapter2:bindingcollectionadapter-recyclerview:2.1.0
|    +--- me.tatarka.bindingcollectionadapter2:bindingcollectionadapter:2.1.0 (*)
|    +--- com.android.support:recyclerview-v7:24.2.0 -> 26.0.1 (*)
|    +--- com.android.databinding:library:1.3.1 (*)
|    +--- com.android.databinding:baseLibrary:2.3.0 -> 3.0.0-beta2
|    \--- com.android.databinding:adapters:1.3.1 (*)
+--- com.actionbarsherlock:viewpagerindicator:2.4.1
|    \--- com.android.support:support-v4:13.0.0 -> 26.0.1 (*)
+--- com.github.amlcurran.showcaseview:library:5.4.3
|    +--- com.android.support:support-annotations:23.1.1 -> 26.0.1
|    \--- com.android.support:support-v4:23.1.1 -> 26.0.1 (*)
+--- me.henrytao:mdcore:3.3.8
|    +--- com.android.support:appcompat-v7:23.2.0 -> 26.0.1 (*)
|    +--- com.android.support:recyclerview-v7:23.2.0 -> 26.0.1 (*)
|    +--- com.android.support:cardview-v7:23.2.0 -> 26.0.1 (*)
|    \--- com.android.support:design:23.2.0 -> 26.0.1 (*)
+--- com.facebook.android:facebook-android-sdk:4.23.0
|    +--- com.android.support:support-v4:25.3.1 -> 26.0.1 (*)
|    +--- com.android.support:appcompat-v7:25.3.1 -> 26.0.1 (*)
|    +--- com.android.support:cardview-v7:25.3.1 -> 26.0.1 (*)
|    +--- com.android.support:customtabs:25.3.1 -> 26.0.1 (*)
|    \--- com.parse.bolts:bolts-android:1.4.0 (*)
+--- org.apmem.tools:layouts:1.10
+--- com.devbrackets.android:exomedia:4.0.2
|    +--- com.android.support:appcompat-v7:25.3.1 -> 26.0.1 (*)
|    +--- com.google.android.exoplayer:exoplayer-core:r2.4.0
|    |    \--- com.android.support:support-annotations:25.3.1 -> 26.0.1
|    +--- com.google.android.exoplayer:exoplayer-dash:r2.4.0
|    |    +--- com.google.android.exoplayer:exoplayer-core:r2.4.0 (*)
|    |    +--- com.android.support:support-annotations:25.3.1 -> 26.0.1
|    |    \--- com.android.support:support-core-utils:25.3.1 -> 26.0.1 (*)
|    +--- com.google.android.exoplayer:exoplayer-hls:r2.4.0
|    |    +--- com.google.android.exoplayer:exoplayer-core:r2.4.0 (*)
|    |    \--- com.android.support:support-annotations:25.3.1 -> 26.0.1
|    \--- com.google.android.exoplayer:exoplayer-smoothstreaming:r2.4.0
|         +--- com.google.android.exoplayer:exoplayer-core:r2.4.0 (*)
|         \--- com.android.support:support-annotations:25.3.1 -> 26.0.1
+--- me.mvdw.recyclerviewmergeadapter:recyclerviewmergeadapter:2.0.0
|    +--- com.android.support:appcompat-v7:23.0.1 -> 26.0.1 (*)
|    +--- com.android.support:recyclerview-v7:23.0.1 -> 26.0.1 (*)
|    \--- com.android.support:support-annotations:23.0.1 -> 26.0.1
+--- org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.3-2 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core:0.16
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.1.2 -> 1.1.3-2 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:0.16
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:0.16 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.1.2 -> 1.1.3-2 (*)
+--- com.crashlytics.sdk.android:crashlytics:2.6.8
|    +--- com.crashlytics.sdk.android:beta:1.2.5
|    |    \--- io.fabric.sdk.android:fabric:1.3.17
|    +--- io.fabric.sdk.android:fabric:1.3.17
|    +--- com.crashlytics.sdk.android:crashlytics-core:2.3.17
|    |    +--- io.fabric.sdk.android:fabric:1.3.17
|    |    \--- com.crashlytics.sdk.android:answers:1.3.13
|    |         \--- io.fabric.sdk.android:fabric:1.3.17
|    \--- com.crashlytics.sdk.android:answers:1.3.13 (*)
+--- com.google.android.gms:play-services-gcm:11.0.1
|    +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.0.1
|    |    +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
|    |    \--- com.google.android.gms:play-services-tasks:[11.0.1] -> 11.0.4 (*)
|    +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
|    \--- com.google.android.gms:play-services-iid:[11.0.1] -> 11.0.1
|         +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.0.1 (*)
|         \--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
+--- com.google.android.gms:play-services-location:11.0.1
|    +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.0.1 (*)
|    +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
|    \--- com.google.android.gms:play-services-tasks:[11.0.1] -> 11.0.4 (*)
+--- com.google.firebase:firebase-config:11.0.1
|    +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.0.1 (*)
|    +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
|    +--- com.google.firebase:firebase-iid:[11.0.1] -> 11.0.4 (*)
|    +--- com.google.firebase:firebase-common:[11.0.1] -> 11.0.4 (*)
|    \--- com.google.android.gms:play-services-tasks:[11.0.1] -> 11.0.4 (*)
+--- com.google.firebase:firebase-messaging:11.0.1 -> 11.0.4
|    +--- com.google.firebase:firebase-iid:[11.0.4] -> 11.0.4 (*)
|    +--- com.google.android.gms:play-services-basement:[11.0.4] -> 11.0.4 (*)
|    \--- com.google.firebase:firebase-common:[11.0.4] -> 11.0.4 (*)
+--- io.intercom.android:intercom-sdk-base-transitive:4.0.1
|    +--- com.android.support:design:26.0.0 -> 26.0.1 (*)
|    +--- com.android.support:appcompat-v7:26.0.0 -> 26.0.1 (*)
|    +--- com.android.support:animated-vector-drawable:26.0.0 -> 26.0.1 (*)
|    +--- com.android.support:support-vector-drawable:26.0.0 -> 26.0.1 (*)
|    +--- com.android.support:support-v4:26.0.0 -> 26.0.1 (*)
|    +--- com.android.support:support-annotations:26.0.0 -> 26.0.1
|    +--- com.android.support:recyclerview-v7:26.0.0 -> 26.0.1 (*)
|    +--- com.squareup:otto:1.3.8
|    +--- com.squareup.okio:okio:1.13.0
|    +--- com.squareup.okhttp3:okhttp:3.8.1 (*)
|    +--- com.squareup.retrofit2:retrofit:2.3.0 (*)
|    +--- com.squareup.retrofit2:converter-gson:2.3.0
|    |    +--- com.squareup.retrofit2:retrofit:2.3.0 (*)
|    |    \--- com.google.code.gson:gson:2.7 -> 2.8.0
|    +--- com.google.code.gson:gson:2.8.0
|    +--- com.intercom:android-composer:1.3.1
|    \--- com.intercom:android-composer-gallery:1.3.1
|         \--- com.android.support:appcompat-v7:25.3.1 -> 26.0.1 (*)
+--- io.intercom.android:intercom-sdk-fcm:4.0.1
|    +--- io.intercom.android:intercom-sdk-base:4.0.1
|    |    +--- com.android.support:design:26.0.0 -> 26.0.1 (*)
|    |    +--- com.android.support:appcompat-v7:26.0.0 -> 26.0.1 (*)
|    |    +--- com.android.support:animated-vector-drawable:26.0.0 -> 26.0.1 (*)
|    |    +--- com.android.support:support-vector-drawable:26.0.0 -> 26.0.1 (*)
|    |    +--- com.android.support:support-v4:26.0.0 -> 26.0.1 (*)
|    |    +--- com.android.support:support-annotations:26.0.0 -> 26.0.1
|    |    +--- com.android.support:recyclerview-v7:26.0.0 -> 26.0.1 (*)
|    |    +--- com.intercom:android-composer:1.3.1
|    |    \--- com.intercom:android-composer-gallery:1.3.1 (*)
|    \--- com.google.firebase:firebase-messaging:11.0.4 (*)
+--- com.commonsware.cwac:merge:1.1.2
|    \--- com.commonsware.cwac:sacklist:1.0.3
+--- com.evernote:android-job:1.1.3
|    +--- com.android.support:support-annotations:25.0.0 -> 26.0.1
|    \--- net.vrallev.android:cat:1.0.5
|         \--- com.android.support:support-annotations:24.2.0 -> 26.0.1
+--- com.segment.analytics.android:analytics:4.3.0-RC1
|    \--- com.android.support:support-annotations:25.2.0 -> 26.0.1
+--- com.segment.analytics.android.integrations:google-analytics:1.1.3
|    \--- com.google.android.gms:play-services-analytics:10.2.1 -> 11.0.1
|         +--- com.google.android.gms:play-services-analytics-impl:[11.0.1] -> 11.0.1
|         |    +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.0.1 (*)
|         |    \--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
|         +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.0.1 (*)
|         +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
|         \--- com.google.android.gms:play-services-tagmanager-v4-impl:[11.0.1] -> 11.0.1
|              +--- com.google.android.gms:play-services-analytics-impl:[11.0.1] -> 11.0.1 (*)
|              +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.0.1 (*)
|              \--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.0.4 (*)
+--- com.appsflyer:segment-android-integration:1.7
|    +--- com.android.support:appcompat-v7:25.1.1 -> 26.0.1 (*)
|    \--- com.appsflyer:af-android-sdk:4.6.7
+--- net.cachapa.expandablelayout:expandablelayout:2.9.1
+--- com.android.support:multidex:1.0.2
\--- com.squareup.leakcanary:leakcanary-android-no-op:1.5.1
```

**Comment by ronocod** [comment]
Can you update your Firebase and Play Services libraries to 11.0.4? That's the version our SDK uses, and not having all of those libraries on the same version can cause issues.

**Comment by rockerhieu** [comment]
Then I got this error:

```
* What went wrong:
Execution failed for task ':transformClassesWithMultidexlistForDevelopmentDebug'.
> java.io.IOException: Can't write [*******/componentClasses.jar] (Can't read [*********/21.jar] (Duplicate zip entry [21.jar:io/intercom/android/sdk/views/holder/PartType.class]))```

**Comment by ronocod** [comment]
If you're using the `base-transitive` module and the `fcm` module you need to exclude the `base` module as mentioned [here](https://docs.intercom.com/using-transitive-dependencies-with-intercom-for-android-8716-ddc96f)

```groovy
compile('io.intercom.android:intercom-sdk-fcm:4.+') {
    exclude group: 'io.intercom.android', module: 'intercom-sdk-base'
}
```

**Comment by rockerhieu** [comment]
Cool, I'm about to let you know about that too. Thanks a lot!
