### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lio/intercom/android/sdk/twig/Twig

### ISSUE THREAD

**Issue by Bringoff** [intercom/intercom-android#404]
I get crash from intercom during its initialization. Looks like it's similar to [this closed issue](https://github.com/intercom/intercom-android/issues/134)
## Version info
  - Intercom for Android version: 4.0.1 (base transitive)
  - Android OS version: 5.1
  - Android Device: Nexus 5 Emulator

## Logs
```
java.lang.NoClassDefFoundError: Failed resolution of: Lio/intercom/android/sdk/twig/Twig;
      at io.intercom.android.sdk.logger.LumberMill.<clinit>(LumberMill.java:11)
      at io.intercom.android.sdk.logger.LumberMill.getLogger(LumberMill.java:16)
      at io.intercom.android.sdk.Intercom.<clinit>(Intercom.java:48)
      at io.intercom.android.sdk.Intercom.initialize(Intercom.java:66)
      at com.myapp.app.App.initIntercom(App.java:221)
      at com.myapp.app.App.onCreate(App.java:156)
      at com.myapp.app.DebugApp.onCreate(DebugApp.java:12)
      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
      at android.app.ActivityThread.access$1500(ActivityThread.java:151)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5254)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
   Caused by: java.lang.ClassNotFoundException: Didn't find class "io.intercom.android.sdk.twig.Twig" on path: DexPathList[[zip file "/data/app/com.myapp.android.dev-1/base.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.myapp.android.dev-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
      at io.intercom.android.sdk.logger.LumberMill.<clinit>(LumberMill.java:11) 
      at io.intercom.android.sdk.logger.LumberMill.getLogger(LumberMill.java:16) 
      at io.intercom.android.sdk.Intercom.<clinit>(Intercom.java:48) 
      at io.intercom.android.sdk.Intercom.initialize(Intercom.java:66) 
      at com.myapp.app.App.initIntercom(App.java:221) 
      at com.myapp.app.App.onCreate(App.java:156) 
      at com.myapp.app.DebugApp.onCreate(DebugApp.java:12) 
      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) 
      at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:135) 
      at android.app.ActivityThread.main(ActivityThread.java:5254) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at java.lang.reflect.Method.invoke(Method.java:372) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
  	Suppressed: java.lang.ClassNotFoundException: io.intercom.android.sdk.twig.Twig
      at java.lang.Class.classForName(Native Method)
      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
      		... 19 more
   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by Bringoff** [comment]
Looks like it was some conflict with Android Architecture Components. As soon as I removed that dependency problem was gone.

**Comment by ronocod** [comment]
:+1: sounds like this may have been multidex or Instant Run related.
