### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#41]
It's a crash from crashlytics I don't have any more details.

```java
 java.lang.NullPointerException
       at intercom.intercomsdk.ViewManagers.ComposerManager.sanitizeMessage(:229)
       at intercom.intercomsdk.ViewManagers.ComposerManager.sanitizeConversationParts(:219)
       at intercom.intercomsdk.ViewManagers.ComposerManager.restoreMessageList(:236)
       at intercom.intercomsdk.ViewManagers.ComposerManager.setupWithConversation(:747)
       at intercom.intercomsdk.ViewManagers.ComposerManager.getFullConversationSuccess(:768)
       at intercom.intercomsdk.fragment.ComposerHeadlessFragment$2.onResponse(:114)
       at intercom.intercomsdk.fragment.ComposerHeadlessFragment$2.onResponse(:111)
       at intercom.intercomsdk.api.Engine$11.onResponse(:593)
       at intercom.intercomsdk.api.Engine$11.onResponse(:590)
       at intercom.intercomsdk.api.GsonRequest.deliverResponse(:82)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(:99)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Harkin** [comment]
Thanks for logging this one too :+1: I've moved this one to our internal tracker and it will be fixed in our next release

**Comment by danikula** [comment]
Same problem in 0.8.5. Any news about fix ?

**Comment by Harkin** [comment]
@danikula yeah this will be fixed in the next release of the SDK
