### ISSUE TITLE
A crash: Dns.java line 39 io.intercom.okhttp3.Dns$1.lookup

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#413]
## Version info
  - Intercom for Android version: 2.3.10
  - Android OS version: Android 7.0
  - Android Device: LGE / model: LGM-G600K

## Expected behavior

No crash

## Actual behavior

crash

## Steps to reproduce

Not reproducible. occurred only once.

## Logs

Fatal Exception: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
       at java.net.InetAddress.getAllByName(InetAddress.java:752)
       at io.intercom.okhttp3.Dns$1.lookup(Dns.java:39)
       at io.intercom.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:170)
       at io.intercom.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:136)
       at io.intercom.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:81)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at io.intercom.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.ShutdownInterceptor.intercept(ShutdownInterceptor.java:35)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.RetryInterceptor.intercept(RetryInterceptor.java:21)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.UserIdentityInterceptor.intercept(UserIdentityInterceptor.java:29)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:111)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
       at java.net.InetAddress.getAllByName(InetAddress.java:752)
       at io.intercom.okhttp3.Dns$1.lookup(Dns.java:39)
       at io.intercom.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:170)
       at io.intercom.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:136)
       at io.intercom.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:81)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at io.intercom.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.ShutdownInterceptor.intercept(ShutdownInterceptor.java:35)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.RetryInterceptor.intercept(RetryInterceptor.java:21)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.UserIdentityInterceptor.intercept(UserIdentityInterceptor.java:29)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by android.system.ErrnoException: android_getaddrinfo failed: EACCES (Permission denied)
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:111)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
       at java.net.InetAddress.getAllByName(InetAddress.java:752)
       at io.intercom.okhttp3.Dns$1.lookup(Dns.java:39)
       at io.intercom.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:170)
       at io.intercom.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:136)
       at io.intercom.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:81)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at io.intercom.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.ShutdownInterceptor.intercept(ShutdownInterceptor.java:35)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.RetryInterceptor.intercept(RetryInterceptor.java:21)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.android.sdk.api.UserIdentityInterceptor.intercept(UserIdentityInterceptor.java:29)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by bboyle18** [comment]
Hi @osama-taha 👋

The stacktrace seems to indicate that you are missing permissions in your app. 
Can you confirm that your app has the  INTERNET permission?

Brian

**Comment by osama-taha** [comment]
Yes... this permission is already defined in the manifest.

**Comment by DaleCantwell** [comment]
Hi @osama-taha 
Where in the manifest is the permission for Internet granted? Is it possibly inside the application tag? That could be the cause of this. Here is an example of how it should be structured:

```
<manifest>
    <uses-permission android:name="android.permission.INTERNET"/>

    <application>
        <activity/>
    </application>
```

**Comment by DaleCantwell** [comment]
Could you also check if adding the permission below gets rid of the error?
```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
```

**Comment by DaleCantwell** [comment]
I noticed that you said in the issue: "Not reproducible. occurred only once."
That would be strange for a SecurityException. If it truly happened just once it might be a custom rom on that users device that may allow the user to revoke permissions.

**Comment by osama-taha** [comment]
According to Crashlytics, it's not a custom Room.

I will update you if it will happen again.

**Comment by ronocod** [comment]
@osama-taha did the crash happen again? Was it on the same device?

**Comment by osama-taha** [comment]
No, I will close it.
