### ISSUE TITLE
A crash: ChatNotification.java line 200 io.intercom.android.sdk.overlay.ChatNotification$4.onAnimationUpdate

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#414]
Version info

Intercom for Android version: 2.3.10
Android OS version: Android 7.0
Android Device: Galaxy A3(2016)
Expected behavior

No crash

Actual behavior

crash

Steps to reproduce

Not reproducible. occurred only once.

Logs

Fatal Exception: java.lang.ArithmeticException: divide by zero
       at io.intercom.android.sdk.overlay.ChatNotification$4.onAnimationUpdate(ChatNotification.java:200)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1346)
       at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:612)
       at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:578)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1001)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1010)
       at io.intercom.android.sdk.overlay.ChatNotification.expandChat(ChatNotification.java:171)
       at io.intercom.android.sdk.overlay.ChatNotification.moveBackward(ChatNotification.java:83)
       at io.intercom.android.sdk.overlay.InAppNotificationManager.updateNotifications(InAppNotificationManager.java:208)
       at io.intercom.android.sdk.overlay.InAppNotificationManager.displayNotificationsAfterAttach(InAppNotificationManager.java:84)
       at io.intercom.android.sdk.overlay.InAppNotificationManager$1.run(InAppNotificationManager.java:75)
       at io.intercom.android.sdk.utilities.ViewUtils.waitForViewAttachment(ViewUtils.java:38)
       at io.intercom.android.sdk.overlay.InAppNotificationManager.displayNotifications(InAppNotificationManager.java:73)
       at io.intercom.android.sdk.overlay.OverlayManager.displayNotifications(OverlayManager.java:246)
       at io.intercom.android.sdk.overlay.OverlayManager$4.run(OverlayManager.java:204)
       at io.intercom.android.sdk.utilities.AvatarUtils$1.onResourceReady(AvatarUtils.java:29)
       at io.intercom.android.sdk.utilities.AvatarUtils$1.onResourceReady(AvatarUtils.java:27)
       at io.intercom.com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
       at io.intercom.com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
       at io.intercom.com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
       at io.intercom.com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
       at io.intercom.com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by DaleCantwell** [comment]
@osama-taha thank you for reporting this, I'll add in protection here for this crash.

**Comment by ronocod** [comment]
Fixed in 4.0.3
