### ISSUE TITLE
crash - Buffer.java line 759 io.intercom.okio.Buffer.readByteArray

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#422]
-Platform: android
-intercom version: 3.2.10
-OS Version: 7.0
-Device: SM-G950F
-RAM Free: 18.9%
-Disk Free: 80.3%

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 36930405 byte allocation with 8388368 free bytes and 24MB until OOM
       at io.intercom.okio.Buffer.readByteArray(Buffer.java:759)
       at io.intercom.okio.Buffer.readString(Buffer.java:619)
       at io.intercom.okio.Buffer.readUtf8(Buffer.java:590)
       at io.intercom.okio.RealBufferedSource.readUtf8(RealBufferedSource.java:178)
       at io.intercom.android.sdk.metrics.MetricsStore.loadObjectsAsJson(MetricsStore.java:196)
       at io.intercom.android.sdk.metrics.MetricsStore.readMetricsFromDisk(MetricsStore.java:171)
       at io.intercom.android.sdk.metrics.MetricsStore$3.run(MetricsStore.java:95)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Comment by ronocod** [comment]
Thanks, we're looking into this now.

**Comment by ronocod** [comment]
This is fixed in 4.1.4.
