### ISSUE TITLE
crash - InboxFragment.java line 260 io.intercom.android.sdk.inbox.InboxFragment$4.onAnimationEnd

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#423]
-Platform: android
-intercom version: 3.2.10
-OS Version: 7.0
-Device: Moto E (4) Plus

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void io.intercom.android.sdk.inbox.InboxFragment$Listener.onConversationSelected(io.intercom.android.sdk.models.Conversation)' on a null object reference
       at io.intercom.android.sdk.inbox.InboxFragment$4.onAnimationEnd(InboxFragment.java:260)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1142)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1313)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:908)
       at android.view.Choreographer.doCallbacks(Choreographer.java:712)
       at android.view.Choreographer.doFrame(Choreographer.java:643)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:896)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6339)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by ronocod** [comment]
Thanks for reporting this, we're working on a fix now.

**Comment by ronocod** [comment]
This is fixed in 4.0.5.
