### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError -  at io.intercom.android.sdk.metrics.MetricsStore.getMetrics(MetricsStore.java:180)

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#424]
-Platform: android
-intercom version: 3.2.10
-OS Version: 6.0.1
-Device: Galaxy C7

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 235368 byte allocation with 2366560 free bytes and 2MB until OOM; failed due to fragmentation (required continguous free 237568 bytes where largest contiguous free 69632 bytes)
       at java.util.ArrayList.add(ArrayList.java:118)
       at io.intercom.android.sdk.metrics.MetricsStore.getMetrics(MetricsStore.java:180)
       at io.intercom.android.sdk.metrics.MetricsStore.readMetricsFromDisk(MetricsStore.java:171)
       at io.intercom.android.sdk.metrics.MetricsStore$3.run(MetricsStore.java:95)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by DaleCantwell** [comment]
Hi Osama,
I believe this is the same issue as https://github.com/intercom/intercom-android/issues/422
Thank you for reporting it, we are looking into it, I'm going to close this issue to track it in the original.
