### ISSUE TITLE
RequestManagerRetriever.assertNotDestroyed - Fatal Exception: java.lang.IllegalArgumentExceptionYou cannot start a load for a destroyed activity

### ISSUE THREAD

**Issue by Mathbl** [intercom/intercom-android#425]
## Version info
  - Intercom for Android version: 4.0.3
  - Android OS version: Multiples
  - Android Device: Multiples

## Steps to reproduce
Not sure, this is coming from a Fabric crash report

## Logs
```java
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
       at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
       at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
       at io.intercom.com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
       at io.intercom.com.bumptech.glide.Glide.with(Glide.java:629)
       at io.intercom.android.sdk.utilities.AvatarUtils.createAvatar(AvatarUtils.java:51)
       at io.intercom.android.sdk.utilities.AvatarUtils.loadAvatarIntoView(AvatarUtils.java:41)
       at io.intercom.android.sdk.profile.TeammateProfilePresenter.setPresence(TeammateProfilePresenter.java:219)
       at io.intercom.android.sdk.profile.ProfilePresenter.setTeammatePresence(ProfilePresenter.java:107)
       at io.intercom.android.sdk.conversation.ConversationFragment.updateProfileToolbar(ConversationFragment.java:499)
       at io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(ConversationFragment.java:713)
       at io.intercom.android.sdk.conversation.ConversationFragment.onConversationUpdated(ConversationFragment.java:617)
       at io.intercom.android.sdk.conversation.WebViewHostWrapper$1.run(WebViewHostWrapper.java:67)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
--

**Comment by ronocod** [comment]
This is fixed in 4.0.5.
