### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#426]
-Platform: Android
-intercom version: 3.2.10
-OS Version: 5.1.1
-Device: Zenfone Go (ASUS_X00BD)

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:775)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
       at io.intercom.android.sdk.activities.IntercomMessengerActivity.applyBackOrCloseMessenger(IntercomMessengerActivity.java:178)
       at io.intercom.android.sdk.activities.IntercomMessengerActivity.onBackToInboxClicked(IntercomMessengerActivity.java:314)
       at io.intercom.android.sdk.conversation.ConversationFragment.onInboxClicked(ConversationFragment.java:862)
       at io.intercom.android.sdk.views.IntercomToolbar.onClick(IntercomToolbar.java:147)
       at android.view.View.performClick(View.java:4781)
       at android.view.View$PerformClick.run(View.java:19874)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5297)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by ronocod** [comment]
This is a bug from Support Library 25. Version 4.x of our SDK uses Support Library 26 which doesn't have this bug. Upgrading to 4.x will fix this issue for you

**Comment by osama-taha** [comment]
Thanks, we've upgrade the library version to 4.x with the latest build tools and support library.
