### ISSUE TITLE
Could not dispatch event: class io.intercom.android.sdk.models.events.UploadEvent

### ISSUE THREAD

**Issue by ZaydelEduard** [intercom/intercom-android#439]
## Version info
  - Intercom for Android version: 4.+ (4.1.0) 
  - Android OS version: 6.0
  - Android Device: Blackview 6000

## Expected behavior
Work

## Actual behavior
Crash

## Steps to reproduce
 1. Open chat
 2. Upload image

## Logs
  java.lang.RuntimeException: Could not dispatch event: class io.intercom.android.sdk.models.events.UploadEvent to handler [EventHandler public void io.intercom.android.sdk.conversation.NativeConversationContentPresenter.uploadSuccess(io.intercom.android.sdk.models.events.UploadEvent)]: Invalid index 0, size is 0
                                                                     at io.intercom.com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
                                                                     at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:387)
                                                                     at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
                                                                     at io.intercom.com.squareup.otto.Bus.post(Bus.java:337)
                                                                     at io.intercom.android.sdk.MainThreadBus.access$001(MainThreadBus.java:9)
                                                                     at io.intercom.android.sdk.MainThreadBus$1.run(MainThreadBus.java:23)
                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                     at android.os.Looper.loop(Looper.java:207)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5697)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
                                                                  Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
                                                                     at java.util.ArrayList.get(ArrayList.java:313)
                                                                     at io.intercom.android.sdk.conversation.NativeConversationContentPresenter.createBlocksForUpload(NativeConversationContentPresenter.java:586)
                                                                     at io.intercom.android.sdk.conversation.NativeConversationContentPresenter.uploadSuccess(NativeConversationContentPresenter.java:571)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at io.intercom.com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                                                                     at io.intercom.com.squareup.otto.Bus.dispatch(Bus.java:385)
                                                                     at io.intercom.com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) 
                                                                     at io.intercom.com.squareup.otto.Bus.post(Bus.java:337) 
                                                                     at io.intercom.android.sdk.MainThreadBus.access$001(MainThreadBus.java:9) 
                                                                     at io.intercom.android.sdk.MainThreadBus$1.run(MainThreadBus.java:23) 
                                                                     at android.os.Handler.handleCallback(Handler.java:815) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                     at android.os.Looper.loop(Looper.java:207) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5697) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

**Comment by ronocod** [comment]
Thanks for reporting this, we're looking into it now.

**Comment by ronocod** [comment]
This is fixed in 4.1.3.
