### ISSUE TITLE
ChatHeaderService crash

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#44]
```
java.lang.RuntimeException: Unable to start service intercom.intercomsdk.presentation.ChatHeadService@43e9e118 with Intent { cmp=com.selltag/intercom.intercomsdk.presentation.ChatHeadService (has extras) }: java.lang.IllegalStateException: PresentationManager
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2909)
       at android.app.ActivityThread.access$2400(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5271)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:667)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.IllegalStateException: PresentationManager
       at intercom.intercomsdk.presentation.PresentationManager.getInstance(:136)
       at intercom.intercomsdk.ViewManagers.ChatheadManager.(:98)
       at intercom.intercomsdk.presentation.ChatHeadService.onStartCommand(:54)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2872)
       at android.app.ActivityThread.access$2400(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5271)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:667)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Harkin** [comment]
Thanks for logging this one with us. This was caused by a sneaky race condition. I'm confidant that we've already addressed the issue but I'll be sure to double check it now.

**Comment by danikula** [comment]
Same problem in 0.8.5. Any news about fix ?

**Comment by danikula** [comment]
Also have similar crash into ChatHeadService:
```
java.lang.RuntimeException: Unable to start service intercom.intercomsdk.presentation.ChatHeadService@4291f4a0 with null: java.lang.NullPointerException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3007)
       at android.app.ActivityThread.access$2200(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at intercom.intercomsdk.presentation.ChatHeadService.onStartCommand(ChatHeadService.java:52)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2990)
       at android.app.ActivityThread.access$2200(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Waiting for fix...
