### ISSUE TITLE
A crash: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://via.intercom.io/... }

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#449]
## Version info
  - Intercom for Android version: latest
  - Android OS version: 7.1.1
  - Android Device: ONEPLUS A3003

## Steps to reproduce
 1. Not reproducible

## Logs

Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://via.intercom.io/... }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1987)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1696)
       at android.app.Activity.startActivityForResult(Activity.java:4291)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
       at android.app.Activity.startActivityForResult(Activity.java:4249)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
       at android.app.Activity.startActivity(Activity.java:4603)
       at android.app.Activity.startActivity(Activity.java:4563)
       at io.intercom.android.sdk.conversation.ConversationWebViewClient.shouldOverrideUrlLoading(ConversationWebViewClient.java:91)
       at io.intercom.android.sdk.conversation.ConversationWebViewClient.shouldOverrideUrlLoading(ConversationWebViewClient.java:97)
       at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:73)
       at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160)
       at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(SystemMessageHandler.java)
       at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6321)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by ronocod** [comment]
Thanks for reporting this, we'll have a fix in the next release.

**Comment by ronocod** [comment]
This is fixed in version 4.1.5.
