### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.support.v4.app.FragmentActivity.getWindow()

### ISSUE THREAD

**Issue by VeeraAnudeep** [intercom/intercom-android#451]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.+

## Logs
 Crashlytics -
 Organization: Toppr
 Platform: android
 Application: Toppr Doubts
 Version: 1.3.7 (55)
 
 OS Version: 6.0
 Device: Lenovo VIBE X3 Lite
 RAM Free: 31.9%
 Disk Free: 38.1%

 Crashed: main: 0 0 0x0000000000000000
       at io.intercom.android.sdk.conversation.ConversationFragment.updateProfileToolbar(ConversationFragment.java:500)
       at io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(ConversationFragment.java:718)
       at io.intercom.android.sdk.conversation.ConversationFragment.onConversationUpdated(ConversationFragment.java:622)
       at io.intercom.android.sdk.conversation.WebViewHostWrapper$1.run(WebViewHostWrapper.java:67)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.support.v4.app.FragmentActivity.getWindow()' on a null object reference
       at io.intercom.android.sdk.conversation.ConversationFragment.updateProfileToolbar(ConversationFragment.java:500)
       at io.intercom.android.sdk.conversation.ConversationFragment.conversationSuccess(ConversationFragment.java:718)
       at io.intercom.android.sdk.conversation.ConversationFragment.onConversationUpdated(ConversationFragment.java:622)
       at io.intercom.android.sdk.conversation.WebViewHostWrapper$1.run(WebViewHostWrapper.java:67)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by ronocod** [comment]
Thanks for reporting this, we'll have a fix in the next release.

**Comment by ronocod** [comment]
This is fixed in version 4.1.5.
