### ISSUE TITLE
NullPointerException Attempt to invoke virtual method 'java.lang.String io.intercom.android.sdk.metrics.MetricObject.getId()' on a null object reference

### ISSUE THREAD

**Issue by pkovalenko** [intercom/intercom-android#452]
## Version info
  - Intercom for Android version: 4.1.4
  - Android OS version: Android 7.0 & Android 6.0
  - Android Device: LGE

## Actual behavior
According to crashlytics app sometimes crashes with next log
Attempt to invoke virtual method 'java.lang.String io.intercom.android.sdk.metrics.MetricObject.getId()' on a null object reference

It happens on Last Intercom version 4.1.4.

## Logs
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String io.intercom.android.sdk.metrics.MetricObject.getId()' on a null object reference
       at io.intercom.android.sdk.metrics.MetricsStore.getFile(MetricsStore.java:110)
       at io.intercom.android.sdk.metrics.MetricsStore.deleteFilesFor(MetricsStore.java:176)
       at io.intercom.android.sdk.metrics.MetricsStore$4$1.run(MetricsStore.java:136)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)`

**Comment by ronocod** [comment]
This is fixed in version 4.1.5.
