### ISSUE TITLE
A crash: Fatal Exception: java.lang.IllegalStateException: cache is closed        at io.intercom.com.bumptech.glide.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:620)

### ISSUE THREAD

**Issue by osama-taha** [intercom/intercom-android#462]
## Version info
  - Intercom for Android version: 4.1.6
  - Android OS version: 5.1
  - Android Device:Lenovo VIBE X3 Lite

## Expected behavior
No crash
## Actual behavior
crash
## Steps to reproduce
Not reproducible 

## Logs

Fatal Exception: java.lang.IllegalStateException: cache is closed
       at io.intercom.com.bumptech.glide.disklrucache.DiskLruCache.checkNotClosed(DiskLruCache.java:620)
       at io.intercom.com.bumptech.glide.disklrucache.DiskLruCache.get(DiskLruCache.java:409)
       at io.intercom.android.sdk.imageloader.LongTermImageDiskCache.get(LongTermImageDiskCache.java:73)
       at io.intercom.android.sdk.imageloader.LongTermImageLoader.loadImage(LongTermImageLoader.java:59)
       at io.intercom.android.sdk.conversation.ReactionInputView.setUpReactions(ReactionInputView.java:116)
       at io.intercom.android.sdk.conversation.ConversationFragment.configureInputView(ConversationFragment.java:469)
       at io.intercom.android.sdk.conversation.ConversationFragment.onViewCreated(ConversationFragment.java:398)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:855)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2587)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:851)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:794)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:181)
       at io.intercom.android.sdk.activities.IntercomMessengerActivity.applyBackOrCloseMessenger(IntercomMessengerActivity.java:180)
       at io.intercom.android.sdk.activities.IntercomMessengerActivity.onBackPressed(IntercomMessengerActivity.java:169)
       at android.app.Activity.onKeyUp(Activity.java:2591)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2780)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2849)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
       at com.appsee.i.dispatchKeyEvent(p:54)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2442)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4591)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4547)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4044)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4097)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4063)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4218)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4071)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4275)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4044)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4097)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4063)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4071)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4044)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4097)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4063)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4251)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4421)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2285)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1909)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1900)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2262)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:148)
       at android.os.Looper.loop(Looper.java:151)
       at android.app.ActivityThread.main(ActivityThread.java:5763)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by osama-taha** [comment]
did you get a chance to look at it?

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
