### ISSUE TITLE
Dex: Error converting bytecode to dex

### ISSUE THREAD

**Issue by Jp3rd** [intercom/intercom-android#463]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io
Hi I am trying to add the intercom-android, but it is giving this error:

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: field ID not in [0, 0xffff]: 65536
        at com.android.dx.merge.DexMerger$5.updateIndex(DexMerger.java:489)
        at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:272)
        at com.android.dx.merge.DexMerger.mergeFieldIds(DexMerger.java:497)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:163)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:194)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:506)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:336)
        at com.android.dx.command.dexer.Main.runDx(Main.java:291)
        at com.android.dx.command.dexer.Main.main(Main.java:247)
        at com.android.dx.command.Main.main(Main.java:94)

:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.
```
## Version info
  - Intercom for Android version: 4.+
  - Android OS version: 6
  - Android Device: NEXUS 6P

**Comment by ronocod** [comment]
You need to setup Multidex on your app, there's some more information from Google about this here: https://developer.android.com/studio/build/multidex.html
