### ISSUE TITLE
ConversationsActivity IllegalStateException

### ISSUE THREAD

**Issue by PaNaVTEC** [intercom/intercom-android#47]
This is another crash from Fabric, is quite similar to one that I already reported but is not the same:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.selltag/intercom.intercomsdk.activities.ConversationsActivity}: java.lang.IllegalStateException: PresentationManager
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
       at android.app.ActivityThread.access$600(ActivityThread.java:140)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4898)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.IllegalStateException: PresentationManager
       at intercom.intercomsdk.presentation.PresentationManager.getInstance(:136)
       at intercom.intercomsdk.activities.ConversationsActivity.onCreate(:84)
       at android.app.Activity.performCreate(Activity.java:5184)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
       at android.app.ActivityThread.access$600(ActivityThread.java:140)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4898)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by danikula** [comment]
Same problem. I use 0.8.5 version. Waiting for fix...

**Comment by Harkin** [comment]
I've been looking into this one and the most straightforward reason why this might happen is if you're calling something from the `Intercom` class before you've called `Intercom.initialize(ctx)`. Maybe from a flow related to a push notification coming in?

Regardless of that, we've finished a hefty re-architecture of the SDK and will be recommending that you initialize Intercom from the `Application` in the next release to avoid situations like this

**Comment by PaNaVTEC** [comment]
Hi Harkin,

I think thats impossible. In my code I do not touch directly "Intercom" class, instead of this I am using a "IntercomWrapper", is initialized via DI with Dagger and is a Singleton object in the application Module

```java
@Provides @Singleton IntercomWrapper provideIntercom(Application application,
      @IntercomAppKey String intercomAppKey, @IntercomAppId String intercomAppId) {
    return new IntercomWrapperImp(application, intercomAppKey, intercomAppId);
  }
```
InteractorWrapperImp has this constructor:

```java
public IntercomWrapper(Application app, String intercomAppKey, String intercomAppId) {
    Intercom.initialize(app);
    Intercom.setApiKey(intercomAppKey, intercomAppId);
    Intercom.enableChatheadText(true);
  }
```

All my code just uses "IntercomWrapper" Interface and never "Intercom" class directly, so I think is impossible to call something before initialize Intercom.

**Comment by Harkin** [comment]
That's a pretty neat integration!

Yeah the bug is definitely on our side in that case. I suspect it happened when the app came from the background. This isn't going to be an issue in the next version
