### ISSUE TITLE
Unable to register gcm token (MessengerApi.setDeviceToken)

### ISSUE THREAD

**Issue by dbarwacz** [intercom/intercom-android#472]
I'm seeing strange crash:

Android: 7.0
Device: SM-A320FL
Intercom sdk: 4.1.6
Target: 27
```
Fatal Exception: java.lang.IllegalArgumentException: Unable to create call adapter for interface io.intercom.retrofit2.Call
    for method MessengerApi.setDeviceToken
       at io.intercom.retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:752)
       at io.intercom.retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:237)
       at io.intercom.retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:162)
       at io.intercom.retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at io.intercom.retrofit2.Retrofit$1.invoke(Retrofit.java:147)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at io.intercom.android.sdk.api.$Proxy2.setDeviceToken(Unknown Source)
       at io.intercom.android.sdk.api.Api.setDeviceToken(Api.java:120)
       at io.intercom.android.sdk.push.PushHandler.sendTokenToIntercom(PushHandler.java:24)
       at io.intercom.android.sdk.push.IntercomPushClient.sendTokenToIntercom(IntercomPushClient.java:88)
       at io.intercom.android.sdk.gcm.IntercomGcmImplementation.registerToken(IntercomGcmImplementation.java:34)
       at io.intercom.android.sdk.IntercomPushManager.registerGcmToken(IntercomPushManager.java:65)
       at io.intercom.android.sdk.RealIntercom$1.run(RealIntercom.java:123)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```
Caused by 
```
Caused by java.lang.IllegalArgumentException: Call return type must be parameterized as Call<Foo> or Call<? extends Foo>
       at io.intercom.retrofit2.Utils.getCallResponseType(Utils.java:362)
       at io.intercom.retrofit2.ExecutorCallAdapterFactory.get(ExecutorCallAdapterFactory.java:38)
       at io.intercom.retrofit2.Retrofit.nextCallAdapter(Retrofit.java:221)
       at io.intercom.retrofit2.Retrofit.callAdapter(Retrofit.java:205)
       at io.intercom.retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:235)
       at io.intercom.retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:162)
       at io.intercom.retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at io.intercom.retrofit2.Retrofit$1.invoke(Retrofit.java:147)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at io.intercom.android.sdk.api.$Proxy2.setDeviceToken(Unknown Source)
       at io.intercom.android.sdk.api.Api.setDeviceToken(Api.java:120)
       at io.intercom.android.sdk.push.PushHandler.sendTokenToIntercom(PushHandler.java:24)
       at io.intercom.android.sdk.push.IntercomPushClient.sendTokenToIntercom(IntercomPushClient.java:88)
       at io.intercom.android.sdk.gcm.IntercomGcmImplementation.registerToken(IntercomGcmImplementation.java:34)
       at io.intercom.android.sdk.IntercomPushManager.registerGcmToken(IntercomPushManager.java:65)
       at io.intercom.android.sdk.RealIntercom$1.run(RealIntercom.java:123)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

Method clearly has `Call<Void>` as return type so I would assume some bytecode incompatibility. May be that device manufacturer decided to strip `Void` generics but it's just my guess. Have you seen something like it before?

**Comment by skylerwshaw** [comment]
@dbarwacz How many individual users are experiencing this crash? How many times has it occurred?

**Comment by dbarwacz** [comment]
Hey! Thanks for getting back so quick. 
It has just started to appear. We upgraded to 27 and needed to update intercom as well. So far, after ~24h of rather big rollout, I have 1 user with 25 crashes.

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
