### ISSUE TITLE
NPE: MetricsStore getFile

### ISSUE THREAD

**Issue by VisheshVadhera** [intercom/intercom-android#475]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version: 4.1.4
  - Android OS version: 4.4.4
  - Android Device: HTC Desire 820q dual sim

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs
```

Fatal Exception: java.lang.NullPointerException
       at io.intercom.android.sdk.metrics.MetricsStore.getFile(MetricsStore.java:110)
       at io.intercom.android.sdk.metrics.MetricsStore.deleteFilesFor(MetricsStore.java:176)
       at io.intercom.android.sdk.metrics.MetricsStore$4$1.run(MetricsStore.java:136)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:864)
```

**Comment by ronocod** [comment]
This is fixed in version 4.1.5 and above.
