### ISSUE TITLE
Crash in ConversationsActivity

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#48]
version 0.8.5

```
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:3760)
       at android.view.ViewGroup.addView(ViewGroup.java:3613)
       at android.view.ViewGroup.addView(ViewGroup.java:3558)
       at android.view.ViewGroup.addView(ViewGroup.java:3534)
       at intercom.intercomsdk.activities.ConversationsActivity$1.onComplete(ConversationsActivity.java:251)
       at intercom.intercomsdk.ViewManagers.ComposerManager$4.onAnimationEnd(ComposerManager.java:351)
       at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1030)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
       at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
       at android.view.Choreographer.doCallbacks(Choreographer.java:603)
       at android.view.Choreographer.doFrame(Choreographer.java:572)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5356)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by DaleCantwell** [comment]
Hi @danikula 
Thank you for reporting the issue. It was a problem, with one of our animations. It has been fixed and will be included in our next update.
