### ISSUE TITLE
issue on running program linked with Fragments

### ISSUE THREAD

**Issue by akhil1564** [intercom/intercom-android#482]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - Intercom for Android version:
  - Android OS version:
  - Android Device:

## Steps to reproduce
 1. 
 2. 
 3. 

## Logs

**Comment by akhil1564** [comment]
here is my code
  import android.os.Bundle;
  import android.support.annotation.NonNull;
  import android.support.design.widget.BottomNavigationView;
  import android.support.v4.app.FragmentManager;
  import android.support.v4.app.FragmentTransaction;
  import android.support.v7.app.AppCompatActivity;
  import android.view.MenuItem;
  import com.google.android.gms.ads.AdRequest;
  import com.google.android.gms.ads.AdView;

   public class MainActivity extends AppCompatActivity implements BottomNavigationView.OnNavigationItemSelectedListener{


    private BottomNavigationView.OnNavigationItemSelectedListener mOnNavigationItemSelectedListener
            = new BottomNavigationView.OnNavigationItemSelectedListener() {

        FragmentManager fragmentManager=getSupportFragmentManager();
        FragmentTransaction  transaction =fragmentManager.beginTransaction();

        @Override
        public boolean onNavigationItemSelected(@NonNull MenuItem item) {
            switch (item.getItemId()) {
                case R.id.navigation_dashboard:
                    dashboard fragmentq = new dashboard();
                    transaction.replace(R.id.navigation_dashboard,fragmentq);
                    transaction.commit();
                    return true;
                case R.id.navigation_notifications:
                    transaction.replace(R.id.content1, new notifaction()).commit();
                    return true;
                case R.id.navigation_eeeee:
                    transaction.replace(R.id.content1, new eeeee()).commit();
                    return true;
            }
            return false;
        }

    };

    private AdView mAdView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        BottomNavigationView navigation = (BottomNavigationView) findViewById(R.id.navigation);
        navigation.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
        mAdView = findViewById(R.id.adView);
        AdRequest adRequest = new AdRequest.Builder().build();
        mAdView.loadAd(adRequest);

    }



    @Override
    public boolean onNavigationItemSelected(@NonNull MenuItem item) {
        return false;
    }
}




errors
java.lang.RuntimeException: com.example.akhil.cricet.MainActivity@801648e must implement OnFragmentInteractionListener
                                                                              at com.example.akhil.cricet.eeeee.onAttach(eeeee.java:83)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1363)
                                                                              at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
                                                                              at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
                                                                              at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
                                                                              at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                              at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by akhil1564** [comment]
help to resolve the issue

**Comment by ronocod** [comment]
This is an issue in your own code, closing this as it's not related to the Intercom SDK.
