### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #1 An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by kbhat968** [intercom/intercom-android#483]
Dear Expert,

I am downloaind the remote file using ASync, it was working perfectly while I have updated Android Studio 2.3.3 to 3.0.1 amd update the Gradle version to 3.5.

I am able to build but while running its showing me An error occurred while executing doInBackground()

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: cn.leapinfo.mupdfdemo, PID: 16489
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:841)
                   Caused by: java.lang.NullPointerException
                      at java.io.StringReader.<init>(StringReader.java:47)
                   

Could you please let me know

**Comment by ronocod** [comment]
This looks like a `NullPointerException` happening in your code. Closing this as it's not related to the Intercom SDK.
