### ISSUE TITLE
Crash: RuntimeException: Window couldn't find content container view

### ISSUE THREAD

**Issue by pkovalenko** [intercom/intercom-android#486]
## Version info
  - Intercom for Android version: 4.1.5
  - Android OS version: 5.0.1
  - Android Device: LG G3

## Expected behavior
Crash report

## Actual behavior
No crash

## Steps to reproduce
Report from Crashlytics

## Logs
```
Fatal Exception: java.lang.RuntimeException: Window couldn't find content container view
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3623)
       at com.android.internal.policy.impl.PhoneWindowEx.generateLayout(PhoneWindowEx.java:22)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3689)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1967)
       at android.view.Window.findViewById(Window.java:980)
       at android.app.Activity.findViewById(Activity.java:2124)
       at io.intercom.android.sdk.overlay.OverlayPresenter.removeOverlaysIfPresent(OverlayPresenter.java:161)
       at io.intercom.android.sdk.overlay.OverlayPresenter.onStateChange(OverlayPresenter.java:119)
       at io.intercom.android.sdk.overlay.OverlayPresenter.onStateChange(OverlayPresenter.java:55)
       at io.intercom.android.sdk.store.TwoParamChangeSubscriber$1.run(TwoParamChangeSubscriber.java:44)
       at io.intercom.android.sdk.store.ChangeSubscriber.runOnMainThread(ChangeSubscriber.java:44)
       at io.intercom.android.sdk.store.TwoParamChangeSubscriber.onStateChange(TwoParamChangeSubscriber.java:42)
       at io.intercom.android.sdk.store.Store$1.dispatch(Store.java:52)
       at io.intercom.android.sdk.store.Store$2.dispatch(Store.java:66)
       at io.intercom.android.sdk.middleware.OperatorClientConditionsMiddleware.dispatch(OperatorClientConditionsMiddleware.java:41)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.MetricTrackerMiddleware.dispatch(MetricTrackerMiddleware.java:46)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.AppConfigMiddleware.dispatch(AppConfigMiddleware.java:24)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.UserIdentityMiddleware.dispatch(UserIdentityMiddleware.java:19)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.ScreenshotMiddleware.dispatch(ScreenshotMiddleware.java:41)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.FirstMessageMiddleware.dispatch(FirstMessageMiddleware.java:29)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.AudioMiddleware.dispatch(AudioMiddleware.java:32)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.OverlayPresenterMiddleware.dispatch(OverlayPresenterMiddleware.java:61)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.NexusClientMiddleware.dispatch(NexusClientMiddleware.java:30)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.UserUpdateBatcherMiddleware.dispatch(UserUpdateBatcherMiddleware.java:28)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.ApiMiddleware.dispatch(ApiMiddleware.java:20)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.middleware.LoggerMiddleware.dispatch(LoggerMiddleware.java:20)
       at io.intercom.android.sdk.store.Store$3.dispatch(Store.java:74)
       at io.intercom.android.sdk.store.Store.dispatch(Store.java:81)
       at io.intercom.android.sdk.ActivityLifecycleHandler.handleMessage(ActivityLifecycleHandler.java:39)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5297)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by DaleCantwell** [comment]
We are moving all our issues support to our [Intercom Developers Hub available here](https://developers.intercom.com/docs/intercom-mobile-installation). We copied this issue with all the comments to our internal bug tracking tool. Whenever you would like an update, just reach out to us on our [Intercom Developer Hub](https://developers.intercom.com/docs/intercom-mobile-installation) and our Customer Support Engineers will help.

Thanks

Dale
