### ISSUE TITLE
java.lang.NoSuchMethodError: No static method getFont

### ISSUE THREAD

**Issue by buddhasaikia** [intercom/intercom-android#488]
App crashes when I included version 4.+ in build.gradle file. 
## Version info
  - Intercom for Android version: 4.+
  - Android OS version: 7.1.1
  - Android Device: Mototola Moto E4 Plus

## Steps to reproduce
 1. Just append `compile 'io.intercom.android:intercom-sdk-base:4.+'` in app level build.gradle file. Here is my gradle dependency settings-
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/PGSDK_V2.1.jar')
    implementation("com.android.support:support-v4:$rootProject.ext.supportLibrary") {
        force = true
    }
    compile("com.android.support:appcompat-v7:$rootProject.ext.supportLibrary") {
        force = true
    }

    compile("com.android.support:recyclerview-v7:$rootProject.ext.supportLibrary") {
        force = true
    }
    compile("com.android.support:design:$rootProject.ext.supportLibrary") {
        force = true
    }
    compile("com.android.support:cardview-v7:$rootProject.ext.supportLibrary") {
        force = true
    }
    /*Google play service*/
    compile "com.google.android.gms:play-services-analytics:$rootProject.ext.playService"
    compile "com.google.android.gms:play-services-maps:$rootProject.ext.playService"
    compile "com.google.android.gms:play-services-places:$rootProject.ext.playService"
    compile "com.google.android.gms:play-services-location:$rootProject.ext.playService"
    compile "com.google.android.gms:play-services-gcm:$rootProject.ext.playService"
    compile "com.google.android.gms:play-services-plus:$rootProject.ext.playService"
    compile "com.google.android.gms:play-services-ads:$rootProject.ext.playService"
    compile "com.google.firebase:firebase-crash:$rootProject.ext.firebase"
    compile "com.google.firebase:firebase-core:$rootProject.ext.firebase"
    compile "com.google.firebase:firebase-messaging:$rootProject.ext.firebase"
    /*Google play service end*/
    compile "com.squareup.picasso:picasso:$rootProject.ext.picasso"
    compile "com.android.support:multidex:$rootProject.ext.multidex"
    compile "com.facebook.android:facebook-android-sdk:$rootProject.ext.facebookAndroid"
    compile "de.greenrobot:eventbus:$rootProject.ext.eventbus"
    compile "de.hdodenhof:circleimageview:$rootProject.ext.circleImageViewer"

    compile "com.uber.sdk:rides-android:$rootProject.ext.uber"
    compile "com.squareup.retrofit2:retrofit:$rootProject.ext.retrofit"
    compile "com.squareup.retrofit2:converter-gson:$rootProject.ext.retrofit"
    compile "com.squareup.okhttp3:logging-interceptor:$rootProject.ext.loggingInterceptor"
    compile "com.facebook.stetho:stetho:$rootProject.ext.stetho"
    compile "com.facebook.stetho:stetho-okhttp3:$rootProject.ext.stetho"
    //debugCompile "com.squareup.leakcanary:leakcanary-android:$rootProject.ext.leakcanary"
    //releaseCompile "com.squareup.leakcanary:leakcanary-android-no-op:$rootProject.ext.leakcanary"
    //testCompile "com.squareup.leakcanary:leakcanary-android-no-op:$rootProject.ext.leakcanary"
    compile "com.appsflyer:af-android-sdk:$rootProject.ext.appsflyer"
    compile "io.reactivex.rxjava2:rxandroid:$rxandroid"
    compile "io.reactivex.rxjava2:rxjava:$rxandroid"
    compile 'com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0'

    compile "com.google.dagger:dagger-android:$dagger2"
    //compile "com.google.dagger:dagger-android-support:$dagger2" // if you use the support libraries
    annotationProcessor "com.google.dagger:dagger-android-processor:$dagger2"
    annotationProcessor "com.google.dagger:dagger-compiler:$dagger2"

    compile "com.journeyapps:zxing-android-embedded:$rootProject.ext.zxingAndroidEmbedded"
    compile "appice.io.android:sdk:$rootProject.ext.appIce"
    //compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    compile "org.jetbrains.anko:anko:$anko_version"
    //compile 'com.github.amlcurran.showcaseview:library:5.4.3'
    compile 'com.googlecode.libphonenumber:libphonenumber:7.2.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    //compile 'com.github.deano2390:MaterialShowcaseView:1.2.0'
    //compile 'com.github.faruktoptas:FancyShowCaseView:1.0.0'
    testCompile 'junit:junit:4.12'
    compile 'io.intercom.android:intercom-sdk-base:4.+'
}
```
content of "ext"
```
ext {
    // Sdk and tools
    minSdkVersion = 16
    targetSdkVersion = 26
    compileSdkVersion = 26
    buildToolVersion = '26.0.2'


    // App dependencies
    supportLibrary = '26.0.2'
    retrofit = '2.3.0'
    butterknife = '8.5.1'//'8.4.0'
    glide = '3.7.0'//test1
    photoview = '1.3.1'
    stetho = '1.4.1'
    junit = '4.12'
    playService = '11.8.0'//'10.2.4'
    firebase = '11.8.0'
    picasso = '2.5.2'
    multidex = '1.0.1'
    facebookAndroid = '4.26.0'
    eventbus = '2.4.0'
    circleImageViewer = '2.1.0'
    ultimateRecyclerView = '0.4.0'
    constraintLayout = '1.0.2'
    uber = '0.6.1'//'0.5.3'
    loggingInterceptor = '3.4.1'
    stetho = '1.5.0'
    leakcanary = '1.5.1'
    appsflyer = '4.8.6'//'4.7.1'
    rxandroid = '2.0.1'
    dagger2 = '2.12'
    guavaVersion = '18.0'
    zxingAndroidEmbedded = '3.5.0'
    appIce = '2.2.4'//'2.2.2'
    anko_version = '0.10.2'
    objectboxVersion='1.3.2'
    
}
```

## Logs
```
FATAL EXCEPTION: main
                                                                        Process: com.packagename.dev, PID: 23413
                                                                        java.lang.NoSuchMethodError: No static method getFont(Landroid/content/Context;ILandroid/util/TypedValue;ILandroid/widget/TextView;)Landroid/graphics/Typeface; in class Landroid/support/v4/content/res/ResourcesCompat; or its super classes (declaration of 'android.support.v4.content.res.ResourcesCompat' appears in /data/app/com.packagename.dev-2/base.apk:classes2.dex)
                                                                            at android.support.v7.widget.TintTypedArray.getFont(TintTypedArray.java:119)
                                                                            at android.support.v7.widget.AppCompatTextHelper.updateTypefaceAndStyle(AppCompatTextHelper.java:208)
                                                                            at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:110)
                                                                            at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
                                                                            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
                                                                            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
                                                                            at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1024)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1081)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                            at com.packagename.activity.WelcomeActivity.onCreate(WelcomeActivity.java:47)
                                                                            at android.app.Activity.performCreate(Activity.java:6689)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2709)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                            at android.os.Looper.loop(Looper.java:203)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6339)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

**Comment by buddhasaikia** [comment]
Thanks. That solved my issue.
