### ISSUE TITLE
add support for custom url scheme in in-app messages links

### ISSUE THREAD

**Issue by mderazon** [intercom/intercom-android#55]
when trying to use a deeplink (or any custom url scheme i.e. `app://`) the app crashes. I think the crash is coming from your stack ? 

The crash comes from OkHttp. I actually see behind the crash error dialog the "Open with" dialog coming from the system

**Comment by yonatancups** [comment]
stacktrace of a crash:

FATAL EXCEPTION: OkHttp Dispatcher
           Process: [some package], PID: 34567
            java.lang.RuntimeException: Malformed URL: [some complete deeplink]
            at com.squareup.okhttp.Request.url(Request.java:57)
            at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:623)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:218)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.access$100(Call.java:34)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
             Caused by: java.net.MalformedURLException: Unknown protocol: [deeplink prefix]
            at java.net.URL.<init>(URL.java:182)
            at java.net.URL.<init>(URL.java:125)
            at com.squareup.okhttp.Request.url(Request.java:55)
            at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:623)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:218)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.access$100(Call.java:34)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by mderazon** [comment]
any update regarding this ?

I wouldn't mind trying to fix it myself but I don't see the source code anywhere

this is really hindering our ability to send unified in app promotions across IOS and Android, we have to use Mixpanel to send to Android and Intercom to send to IOS.

(We always include a deep link inside our promotions)

**Comment by DaleCantwell** [comment]
Hi @mderazon 
Thanks for reporting this issue. We fixed this issue in version 0.9.4 which is out now. Custom url schemes should no longer cause any crashes. Check out our change log to see any other differences in the new version.
https://github.com/intercom/intercom-android/blob/master/CHANGELOG.md
Let us know if you see any other issues with deep linking.
