### ISSUE TITLE
Intercom dependencies cause other libraries to malfunction or crash on devices below Android v5.0,

### ISSUE THREAD

**Issue by manishkungwani** [intercom/intercom-android#66]
Hi,
I'm using a Intercom v0.9.5 and also other libraries like SweetAlert and RippleView.

When I generate the apk and deploy it on devices, this is the behavior I see:
1. Runs perfectly fine on devices having Android above v5
2. Crashes as soon as the sweetalert library or RippleView library classes are used in the app.
Here is the stack trace:

	java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:cn.pedant.SweetAlert.Rotate3dAnimation
		at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
		at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
		at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
		at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
		at cn.pedant.SweetAlert.SweetAlertDialog.(SweetAlertDialog.java:80)
		at com.sample.app.JoinNeighbourhoodActivity.loginWithFacebook(JoinNeighbourhoodActivity.java:232)
		at com.sample.app.JoinNeighbourhoodActivity.processFacebookUser(JoinNeighbourhoodActivity.java:187)
		at com.sample.app.JoinNeighbourhoodActivity.access$000(JoinNeighbourhoodActivity.java:48)
		at com.sample.app.JoinNeighbourhoodActivity$1$1.onCompleted(JoinNeighbourhoodActivity.java:138)
		at com.facebook.Request$1.onCompleted(Request.java:281)
		at com.facebook.Request$4.run(Request.java:1666)
		at android.os.Handler.handleCallback(Handler.java:733)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at android.os.Looper.loop(Looper.java:157)
		at android.app.ActivityThread.main(ActivityThread.java:5356)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:515)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
		at dalvik.system.NativeStart.main(Native Method)

Another:

	java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.app/com.sample.app.EmailRegistrationActivity_}: android.view.InflateException: Binary XML file line #44: Error inflating class com.andexert.library.RippleView
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
		at android.app.ActivityThread.access$800(ActivityThread.java:139)
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
		at android.os.Handler.dispatchMessage(Handler.java:102)
		at android.os.Looper.loop(Looper.java:136)
		at android.app.ActivityThread.main(ActivityThread.java:5086)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:515)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
		at dalvik.system.NativeStart.main(Native Method)
	Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class com.andexert.library.RippleView
		at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
		at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
		at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
		at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
		at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
		at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
		at android.app.Activity.setContentView(Activity.java:1937)
		at com.sample.app.EmailRegistrationActivity_.setContentView(EmailRegistrationActivity_.java:50)
		at com.sample.app.EmailRegistrationActivity_.onCreate(EmailRegistrationActivity_.java:41)
		at android.app.Activity.performCreate(Activity.java:5248)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: Didn't find class "com.andexert.library.RippleView" on path: DexPathList[[zip file "/data/app/com.sample.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.sample.app-1, /vendor/lib, /system/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
		at android.view.LayoutInflater.createView(LayoutInflater.java:559)
		at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
		... 22 more

Can you please look at this and suggest a way to make this work.
Thanks

PS: Here is my build.gradle

	apply plugin: 'com.android.application'
	apply plugin: 'android-apt'
	def AAVersion = '3.2'

	buildscript {
		repositories {
			mavenCentral()
		}

		dependencies {
			classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
		}
	}

	apt {
		arguments {
			androidManifestFile variant.outputs[0].processResources.manifestFile
			resourcePackageName 'com.sample.app'
		}
	}

	android {
		compileSdkVersion 21
		buildToolsVersion "21.1.2"

		defaultConfig {
			applicationId "com.sample.app"
			minSdkVersion 14
			targetSdkVersion 21
			versionCode 1
			versionName "1.0"
			multiDexEnabled = true
		}
		buildTypes {
			release {
				minifyEnabled false
				proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			}
		}
	}

	dependencies {
		compile fileTree(include: ['*.jar'], dir: 'libs')
		apt "org.androidannotations:androidannotations:$AAVersion"
		compile "org.androidannotations:androidannotations-api:$AAVersion"
	//    compile project(':intercom-sdk-0.9.5')
		compile 'de.greenrobot:eventbus:2.4.0'
		compile 'com.android.support:appcompat-v7:21.0.3'
		compile 'com.edmodo:cropper:1.0.1'
		compile 'com.mobsandgeeks:android-saripaar:1.0.3'
		compile 'cn.pedant.sweetalert:library:1.3'
		compile 'com.github.navasmdc:MaterialDesign:1.+@aar'
		compile 'com.nineoldandroids:library:2.4.0'
		compile 'it.sephiroth.android.library.horizontallistview:hlistview:1.2.2'
		compile 'com.jpardogo.materialtabstrip:library:1.0.9'
		compile 'com.koushikdutta.ion:ion:2.+'
		compile 'com.facebook.android:facebook-android-sdk:3.21.1'
	//    compile 'com.google.android.gms:play-services:6.5.87'
	//    compile 'com.google.android.gms:play-services:3.1.+'
		compile 'org.apmem.tools:layouts:1.8@aar'
		compile 'com.github.traex.rippleeffect:library:1.2.4'
		compile 'com.snappydb:snappydb-lib:0.5.0'
		compile 'com.esotericsoftware.kryo:kryo:2.24.0'
		compile 'com.rockerhieu.emojicon:library:1.0'
		compile 'com.android.support:support-v4:21.0.+'
		compile 'com.google.code.gson:gson:2.3'
	//    compile 'com.squareup:otto:1.3.6'
	//    compile 'com.squareup.okhttp:okhttp:2.3.0'
	//    compile 'com.squareup.retrofit:retrofit:1.9.0'
	//    compile 'com.squareup.picasso:picasso:2.5.2'
		compile 'com.google.android.gms:play-services:7.0.0'
		compile 'com.facebook.fresco:fresco:0.1.0+'
		compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
	}

**Comment by Harkin** [comment]
Obvious question but does everything work correctly when you aren't including the Intercom SDK?

**Comment by manishkungwani** [comment]
Yep, perfectly. 

Sent from Yahoo Mail on Android

**Comment by Harkin** [comment]
Is it just the RippleView and SweetAlert libraries that cause issues when you do include Intercom?

This is definitely unusual, I'm going to look into it and I'll let you know what I find

**Comment by manishkungwani** [comment]
These were the ones, which crashed upon starting, couldn't check every library..  I can try tomorrow.. IST

Sent from Yahoo Mail on Android

**Comment by Harkin** [comment]
Gotcha, any extra information you can provide will help me track this down faster but that's a good starting point

**Comment by manishkungwani** [comment]
One thing I didn't try is comment only Intercom and check your dependencies.. Will try that as well today and get back to you. Cheers 

Sent from Yahoo Mail on Android

**Comment by Harkin** [comment]
@manishkungwani I've found your issue

When I compile a sample project with all the dependencies you have I'm hitting around 60k methods before including the Intercom SDK. When you include our SDK you're going over the 65k method limit. It's worth saying that any library of over 5k methods would cause this issue here, it's not directly caused by the Intercom SDK. Normally you'd get a build error but with `multiDexEnabled true` in your defaultConfig it's still building the apk correctly but it only runs correctly on 5.0+ devices

I'd suggest looking [here](https://developer.android.com/tools/building/multidex.html#mdex-pre-l) for help on multiDexing on < 5.0 devices (there's a support multidex lib) though turning on Proguard would probably eliminate the need to multidex at all

**Comment by danikula** [comment]
@manishkungwani Also you can [reduce size of Google Play services](http://developer.android.com/google/play-services/setup.html) by including only required components instead of whole library which has a lot of methods (> 20K).
For example use 
```
compile 'com.google.android.gms:play-services-base:7.0.0'
compile 'com.google.android.gms:play-services-analytics:7.0.0'
compile 'com.google.android.gms:play-services-gcm:7.0.0'
```
instead of 
```
compile 'com.google.android.gms:play-services:7.0.0'
```
