### ISSUE TITLE
App Crash: java.lang.NoClassDefFoundError: io.intercom.android.nexus.NexusConfig

### ISSUE THREAD

**Issue by ankesh12** [intercom/intercom-android#75]
App was running good on Nexus 5. When tested the same on other devices below is the error I am getting:

05-13 16:38:21.287  23797-23797/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: io.intercom.android.nexus.NexusConfig
            at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:46)
            at io.intercom.android.sdk.identity.AppIdentity.<init>(AppIdentity.java:23)
            at io.intercom.android.sdk.identity.IdentityStore.<init>(IdentityStore.java:19)
            at io.intercom.android.sdk.Bridge.<init>(Bridge.java:33)
            at io.intercom.android.sdk.Bridge.init(Bridge.java:40)
            at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:55)
            at io.intercom.android.sdk.Intercom.initialize(Intercom.java:48)
            at dna.com.getklarity.application.MyApp.onCreate(GKApp.java:34)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
            at android.app.ActivityThread.access$1300(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:5225)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at dalvik.system.NativeStart.main(Native Method)

The app was running perfectly on other devices before the last build and test done on Nexus 5.
Using:
compile('io.intercom.android:intercom-sdk:0.9.+@aar') {
        transitive = true
    }

Have already done Clean project and other options mentioned in different issues.
Request you to guide!

**Comment by Harkin** [comment]
We're investigating this crash at the moment, we'll let you know as soon as we've found something

**Comment by ankesh12** [comment]
Thank you for responding. If there are any work around please let me know. I have tried uninstalling the app and also clean project option. Both have had no success.

**Comment by Harkin** [comment]
I can't reproduce this. It's potentially an upgrade issue but without knowing what version of the integration you went from -> to it's very difficult to track down. 

Our timeline for the past two releases is: 0.9.7 12 days ago and 0.9.8 2 days ago. Is it safe to assume that you build your app between 12-10 days ago and were on 0.9.7 initially? Or did you have any successful builds within the past 2 days on 0.9.8?

Typically we've found that noclassdeffound errors are because someone isn't including a dependency, but that _shouldn't_ be the case here. Do you have any aggressive proguard rules?

I'd suggest trying 1.0.0 and seeing if you still experience the issue

**Comment by ankesh12** [comment]
I have been using 'io.intercom.android:intercom-sdk:0.9.+@aar' as per the suggestion by one of the intercom team guy. And it was working fine till yesterday. So I don't think there should be any problem with the dependency. I am facing the issue starting today morning. Have tried 1.0.0 and it didn't help.

**Comment by ankesh12** [comment]
Below is the error I am getting using 1.0.0 version:

java.lang.RuntimeException: Unable to create application com.my.application.MyApp: java.lang.TypeNotPresentException: Type io.intercom.android.blocks.models.Block not present
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569)
            at android.app.ActivityThread.access$1300(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:5225)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.TypeNotPresentException: Type io.intercom.android.blocks.models.Block not present
            at org.apache.harmony.luni.lang.reflect.ImplForType.getRawType(ImplForType.java:64)
            at org.apache.harmony.luni.lang.reflect.ImplForType.getResolvedType(ImplForType.java:73)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:61)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:53)
            at org.apache.harmony.luni.lang.reflect.ImplForType.getResolvedType(ImplForType.java:72)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:61)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:53)
            at org.apache.harmony.luni.lang.reflect.ImplForType.getResolvedType(ImplForType.java:72)
            at org.apache.harmony.luni.lang.reflect.Types.getType(Types.java:29)
            at java.lang.Class.getGenericSuperclass(Class.java:761)
            at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(TypeToken.java:82)
            at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:62)
            at io.intercom.android.sdk.identity.AppConfig$1.<init>(AppConfig.java:117)
            at io.intercom.android.sdk.identity.AppConfig.setUpWelcomeMessage(AppConfig.java:117)
            at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:60)
            at io.intercom.android.sdk.identity.AppIdentity.<init>(AppIdentity.java:23)
            at io.intercom.android.sdk.identity.IdentityStore.<init>(IdentityStore.java:19)
            at io.intercom.android.sdk.Bridge.<init>(Bridge.java:33)
            at io.intercom.android.sdk.Bridge.init(Bridge.java:40)
            at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:55)
            at io.intercom.android.sdk.Intercom.initialize(Intercom.java:48)
            at com.my.application.MyApp.onCreate(MyApp.java:34)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
            at android.app.ActivityThread.access$1300(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:5225)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: io.intercom.android.blocks.models.Block
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:204)
            at org.apache.harmony.luni.lang.reflect.ImplForType.getRawType(ImplForType.java:62)
            at org.apache.harmony.luni.lang.reflect.ImplForType.getResolvedType(ImplForType.java:73)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:61)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:53)
            at org.apache.harmony.luni.lang.reflect.ImplForType.getResolvedType(ImplForType.java:72)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:61)
            at org.apache.harmony.luni.lang.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:53)
            at org.apache.harmony.luni.lang.reflect.ImplForType.getResolvedType(ImplForType.java:72)
            at org.apache.harmony.luni.lang.reflect.Types.getType(Types.java:29)
            at java.lang.Class.getGenericSuperclass(Class.java:761)
            at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(TypeToken.java:82)
            at com.google.gson.reflect.TypeToken.<init>(TypeToken.java:62)
            at io.intercom.android.sdk.identity.AppConfig$1.<init>(AppConfig.java:117)
            at io.intercom.android.sdk.identity.AppConfig.setUpWelcomeMessage(AppConfig.java:117)
            at io.intercom.android.sdk.identity.AppConfig.<init>(AppConfig.java:60)
            at io.intercom.android.sdk.identity.AppIdentity.<init>(AppIdentity.java:23)
            at io.intercom.android.sdk.identity.IdentityStore.<init>(IdentityStore.java:19)
            at io.intercom.android.sdk.Bridge.<init>(Bridge.java:33)
            at io.intercom.android.sdk.Bridge.init(Bridge.java:40)
            at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:55)
            at io.intercom.android.sdk.Intercom.initialize(Intercom.java:48)
            at com.my.application.MyApp.onCreate(MyApp.java:34)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
            at android.app.ActivityThread.access$1300(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:213)
            at android.app.ActivityThread.main(ActivityThread.java:5225)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
            at dalvik.system.NativeStart.main(Native Method)
     
Which is somewhat the same issue, it seems.

**Comment by Harkin** [comment]
Hm, if we recommended 0.9.+ it was in error, that + just leads to longer build times unreproducible builds when something changes :( 

If it was working yesterday then you would have been pulling 0.9.8 and you were still using that version this morning when it stopped working.

Did you make any changes to your project yesterday or today, like updating the version of gradle you use or the gradle wrapper, updating the build tools etc? Is there anything about your project that you'd consider non standard that might affect a build?

Could you try invalidating the cache in android studio and going again? `File -> Invalidate Caches`

**Comment by Harkin** [comment]
@ankesh12 any updates here?
