### ISSUE TITLE
Crash on Motorola devices

### ISSUE THREAD

**Issue by felipebari** [intercom/intercom-android#79]
I'm getting crash reports on my app that are caused by Intercom. They are mostly from Motorola devices (X, G and E) running Android 4.4 and 4.2.

```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.myapp.MyActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
at android.app.ActivityThread.access$800(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5086)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)

Caused by: java.lang.NullPointerException
at io.intercom.android.sdk.utilities.DeviceUtils.generateMacId(DeviceUtils.java:62)
at io.intercom.android.sdk.utilities.DeviceUtils.generateDeviceId(DeviceUtils.java:37)
at io.intercom.android.sdk.user.DeviceData.generateDeviceData(DeviceData.java:26)
at io.intercom.android.sdk.api.Api.ping(Api.java:133)
at io.intercom.android.sdk.Bridge.ping(Bridge.java:84)
at io.intercom.android.sdk.Bridge.pingAndLaunchChathead(Bridge.java:78)
at io.intercom.android.sdk.Lifecycles.onActivityStarted(Lifecycles.java:85)
at android.app.Application.dispatchActivityStarted(Application.java:199)
at android.app.Activity.onStart(Activity.java:1056)
at android.support.v4.app.p.onStart(FragmentActivity.java:536)
at com.myapp.q.onStart(BaseActivity.java:79)
at com.myapp.MyActivity.onStart(MyActivity.java:286)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1194)
at android.app.Activity.performStart(Activity.java:5258)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
... 11 more
```

The app has Intercom 0.9.4. For the next update I'll have 1.0.2, but I'd like to make sure this crash has been fixed, since users are unable to open the app.

Seems like something is wrong in your DeviceUtils.generateMacId() method, causing the crash.

Was this already addressed on 1.0.2 or do I need to wait for another update of the library? Let me know if you need any extra information.

**Comment by Harkin** [comment]
Thanks for letting us know about this one. We fixed this issue in v0.9.6
