### ISSUE TITLE
App crash - NullPointerException

### ISSUE THREAD

**Issue by richardlay** [intercom/intercom-android#80]
I'm initializing the sdk in the onCreate() method of the Application class. Here is the stack trace of a crash that has been reported to us.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.homepass.agent.app/com.homepass.agent.app.activities.SplashActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2060)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2085)
       at android.app.ActivityThread.access$600(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at io.intercom.android.sdk.utilities.DeviceUtils.generateMacId(SourceFile:62)
       at io.intercom.android.sdk.utilities.DeviceUtils.generateDeviceId(SourceFile:37)
       at io.intercom.android.sdk.user.DeviceData.generateDeviceData(SourceFile:26)
       at io.intercom.android.sdk.api.Api.ping(SourceFile:136)
       at io.intercom.android.sdk.Bridge.ping(SourceFile:84)
       at io.intercom.android.sdk.Bridge.pingAndLaunchChathead(SourceFile:78)
       at io.intercom.android.sdk.Lifecycles.onActivityStarted(SourceFile:85)
       at android.app.Application.dispatchActivityStarted(Application.java:164)
       at android.app.Activity.onStart(Activity.java:1032)
       at com.homepass.agent.app.activities.SplashActivity.onStart(SourceFile:144)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1165)
       at android.app.Activity.performStart(Activity.java:5018)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2033)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2085)
       at android.app.ActivityThread.access$600(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Harkin** [comment]
Hey, thanks for letting us know about this. Are you using v0.9.5 or earlier of the library? We fixed this issue in v0.9.6

**Comment by richardlay** [comment]
Yes we are using 0.9.5. We will upgrade.
