### ISSUE TITLE
NPE crash in intercom. Class- io.intercom.android.sdk.utilities.LinkUtil

### ISSUE THREAD

**Issue by manishkungwani** [intercom/intercom-android#81]
Hi,
Please have a look at this NPE I got in my app:

java.lang.NullPointerException
       at io.intercom.android.sdk.utilities.LinkUtil.openUrl(LinkUtil.java:16)
       at io.intercom.android.sdk.blocks.Button$1.onClick(Button.java:40)
       at android.view.View.performClick(View.java:4633)
       at android.view.View$PerformClick.run(View.java:19330)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5356)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Harkin** [comment]
Hi @manishkungwani 

This crash was fixed in v1.0.1. We weren't handling URLs with a nonstandard scheme correctly
