### ISSUE TITLE
NPE Crash with DeviceUtils#generateMacId()

### ISSUE THREAD

**Issue by brianmuse** [intercom/intercom-android#82]
This crash log popped up today for us. LG-D950 on Android 4.4.2. The crash happens instantly when the first activity is launched. User can not even log in.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{...}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2205)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
       at android.app.ActivityThread.access$800(ActivityThread.java:142)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5118)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at io.intercom.android.sdk.utilities.DeviceUtils.generateMacId(DeviceUtils.java:62)
       at io.intercom.android.sdk.utilities.DeviceUtils.generateDeviceId(DeviceUtils.java:37)
       at io.intercom.android.sdk.user.DeviceData.generateDeviceData(DeviceData.java:26)
       at io.intercom.android.sdk.api.Api.ping(Api.java:133)
       at io.intercom.android.sdk.Bridge.ping(Bridge.java:84)
       at io.intercom.android.sdk.Bridge.pingAndLaunchChathead(Bridge.java:78)
       at io.intercom.android.sdk.Lifecycles.onActivityStarted(Lifecycles.java:85)
       at android.app.Application.dispatchActivityStarted(Application.java:199)
       at android.app.Activity.onStart(Activity.java:1053)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:539)
       at ....onStart(AbstractActivity.java:88)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
       at android.app.Activity.performStart(Activity.java:5285)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
       at android.app.ActivityThread.access$800(ActivityThread.java:142)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5118)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

`WifiInfo#getMacAddress` may return `null`. possibly related? http://stackoverflow.com/a/6192636/190949

**Comment by brianmuse** [comment]
Duplicate of https://github.com/intercom/intercom-android/issues/80. Closing...sorry about that!
