### ISSUE TITLE
IndexOutOfBoundsException crash in intercom. Class- io.intercom.android.sdk.preview

### ISSUE THREAD

**Issue by manishkungwani** [intercom/intercom-android#84]
Hi,
Please have a look at this exception I got in my app:
Using intercom version 0.9.5

java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at io.intercom.android.sdk.preview.PreviewService.onTouch(PreviewService.java:415)
       at android.view.View.dispatchTouchEvent(View.java:7731)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
       at android.view.View.dispatchPointerEvent(View.java:7916)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4023)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3902)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3471)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3479)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3471)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3479)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3452)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5657)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5588)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5559)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5737)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:138)
       at android.os.Looper.loop(Looper.java:123)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Harkin** [comment]
Hi @manishkungwani 

Can you reproduce this? I haven't been able to myself so any extra information you can give would be really helpful in tracking this down.

Are you sure it's version 0.9.5 too that this happened on? The stacktrace doesn't make sense for v0.9.5

Henry

**Comment by manishkungwani** [comment]
Hey Harkin,
Thanks for responding.
I will collect relevant information and update this issue.

**Comment by DaleCantwell** [comment]
@manishkungwani Have you experienced this issue in any of our recent versions? We are now on 1.1.2. I am going to close out this issue for now but reopen if you encounter this crash on the post beta versions.
Thanks,
Dale

**Comment by manishkungwani** [comment]
Didn't experience it again.
Thanks
