### ISSUE TITLE
"Message to a Handler on a dead thread" in ADB logs

### ISSUE THREAD

**Issue by dzeikei** [intercom/intercom-android#89]
I keep getting the following coming up in ADB logs.
Does Intercom need to be called from only the main thread?

```
W/MessageQueue﹕ Handler (android.os.Handler) {3d9a3f45} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {3d9a3f45} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:335)
            at android.os.Handler.enqueueMessage(Handler.java:631)
            at android.os.Handler.sendMessageAtTime(Handler.java:600)
            at android.os.Handler.sendMessageDelayed(Handler.java:570)
            at android.os.Handler.post(Handler.java:326)
            at io.intercom.android.nexus.NexusSocket.fire(NexusSocket.java:82)
            at io.intercom.android.nexus.NexusClient.fire(NexusClient.java:69)
            at io.intercom.android.nexus.NexusClient$1.run(NexusClient.java:119)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by harkin** [comment]
Hi @dzeikei 

That looks like a bug in our real time library. Definitely not great, but also not something that should affect your (apart from annoying logs). Is Intercom working correctly in your app?

**Comment by dzeikei** [comment]
It stopped happening after update, thanks
