### ISSUE TITLE
NullPointerException in io.intercom.android.sdk.gcm.GcmIntentService

### ISSUE THREAD

**Issue by nemezis** [intercom/intercom-android#99]
Received several crashes in my application:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
       at io.intercom.android.sdk.gcm.GcmIntentService.onHandleIntent(GcmIntentService.java:39)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by DaleCantwell** [comment]
@nemezis thanks for reporting this issue. We have resolved this crash in Version 1.0.4 
Let me know if you get any reports of it in version 1.0.4 and we will open a new issue.

**Comment by nemezis** [comment]
@DaleCantwell I encountered this issue in 1.0.4
